"""
Django settings for case_management project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
import sys
from pathlib import Path
from typing import Any

import sentry_sdk
from csp.constants import NONCE, NONE, SELF, UNSAFE_INLINE

# If disabled will fallback to regular django login
ENTRA_ID_ENABLED = os.environ.get("ENTRA_ID_ENABLED", "True") == "True"

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

SERVICE_NAME = "Share Homes for Ukraine data"

# Environment
ENVIRONMENT = os.environ.get("ENVIRONMENT", "production")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = bool(os.environ.get("DEBUG", default=0))

ALLOWED_HOSTS = (os.environ.get("DJANGO_ALLOWED_HOSTS") or "").split(" ")

DEFAULT_CSRF_TRUSTED_ORIGINS = "http://localhost:8010 http://127.0.0.1:8010"

CSRF_TRUSTED_ORIGINS = os.environ.get(
    "CSRF_TRUSTED_ORIGINS", DEFAULT_CSRF_TRUSTED_ORIGINS
).split(" ")

# AWS S3 settings
AWS_REGION = os.environ.get("AWS_REGION", "eu-west-2")
FILE_DOWNLOAD_S3_BUCKET_NAME = os.environ.get("FILE_DOWNLOAD_S3_BUCKET_NAME")

# Google Analytics
GOOGLE_ANALYTICS_ID = os.environ.get("GOOGLE_ANALYTICS_ID", "")
GOOGLE_ANALYTICS_ENABLED = os.environ.get("GOOGLE_ANALYTICS_ENABLED", "Enabled")

# Sentry Error reporting
SENTRY_ENABLED = os.environ.get("SENTRY_ENABLED", "True") == "True"
SENTRY_LOGS_ENABLED = os.environ.get("SENTRY_LOGS_ENABLED", "True") == "True"
SENTRY_CSP_REPORT_URI = os.environ.get("SENTRY_CSP_REPORT_URI", "/csp-report/")

# Feature flag to emit verbose structured Sentry logs for deduplication
ENHANCED_DEDUPLICATION_LOGGING = (
    os.environ.get("ENHANCED_DEDUPLICATION_LOGGING", "False") == "True"
)

# Feature flag to control whether viewing history events is enabled for LA/DA users
LA_HISTORY_TAB_ENABLED = os.environ.get("LA_HISTORY_TAB_ENABLED", "True") == "True"

# Feature flag to control visibility of fix duplicate records feature to non-admin users
FIX_DUPLICATE_RECORDS_ENABLED = (
    os.environ.get("FIX_DUPLICATE_RECORDS_ENABLED", "True") == "True"
)

# Application definition

INSTALLED_APPS = [
    "auditlog",
    "webapp.apps.WebappConfig",
    "user_management.apps.WebappConfig",
    "accommodation_requests.apps.WebappConfig",
    "accommodations.apps.WebappConfig",
    "guests.apps.WebappConfig",
    "safeguarding.apps.WebappConfig",
    "sponsors.apps.WebappConfig",
    "visa_applications.apps.WebappConfig",
    "ontology.apps.OntologyConfig",
    "accounts.apps.AccountsConfig",
    "downloads.apps.DownloadsConfig",
    "reassignment_requests.apps.ReassignmentRequestsConfig",
    "uams.apps.UamsConfig",
    "unassigned_accommodation_requests.apps.UnassignedAccommodationRequestsConfig",
    "deduplication.apps.DeduplicationConfig",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "debug_toolbar",
    "django_tables2",
    "django_filters",
    "crispy_forms",
    "crispy_forms_gds",
    "rules",
    "formtools",
    "csp",
]

CRISPY_ALLOWED_TEMPLATE_PACKS = ["gds"]
CRISPY_TEMPLATE_PACK = "gds"

MIDDLEWARE = [
    "csp.middleware.CSPMiddleware",
    "webapp.middleware.PermissionsPolicyMiddleware",
    "debug_toolbar.middleware.DebugToolbarMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "webapp.middleware.HealthCheckMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "auditlog.middleware.AuditlogMiddleware",
    "webapp.middleware.AdminAreaRestrictionMiddleware",
    "django.contrib.auth.middleware.LoginRequiredMiddleware",
    "webapp.middleware.GoogleAnalyticsMiddleware",
    "webapp.middleware.RequestTimeMiddleware",
]
if ENTRA_ID_ENABLED:
    MIDDLEWARE += [
        "accounts.middleware.EntraMiddleware",
    ]
MIDDLEWARE += [
    "webapp.middleware.LandingPageRedirectMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

INTERNAL_IPS = ["127.0.0.1"]

ROOT_URLCONF = "case_management.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "case_management.context_processors.app_context",
                "webapp.context_processors.available_links",
            ],
        },
    },
]

WSGI_APPLICATION = "case_management.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "HOST": os.environ.get("DB_HOST"),
        "PORT": 5432,
        "NAME": "postgres",
        "USER": os.environ.get("DB_USERNAME"),
        "PASSWORD": os.environ.get("DB_PASSWORD"),
        "CONN_HEALTH_CHECKS": os.environ.get(
            "CONN_HEALTH_CHECK", default="True"
        ).lower()
        == "true",
        "CONN_MAX_AGE": os.environ.get("CONN_MAX_AGE", default=60),
        "OPTIONS": {
            # 59 seconds - (1 seconds less than 60s timeout)
            "options": "-c statement_timeout=59000"
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": (
            "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"
        ),
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Authentication backends
AUTHENTICATION_BACKENDS = []

if ENTRA_ID_ENABLED:
    AUTHENTICATION_BACKENDS += ["accounts.backend.EntraBackend"]

AUTHENTICATION_BACKENDS += [
    "rules.permissions.ObjectPermissionBackend",
    "django.contrib.auth.backends.ModelBackend",
]

AUTH_USER_MODEL = "accounts.User"

# Login redirect
LOGIN_REDIRECT_URL = "/"

SESSION_COOKIE_AGE = int(
    os.environ.get("SESSION_COOKIE_AGE", 60 * 60)
)  # 60 minutes - Must be int
SESSION_SAVE_EVERY_REQUEST = (
    os.environ.get("SESSION_SAVE_EVERY_REQUEST", "True").lower() == "true"
)  # Must be bool

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-gb"

TIME_ZONE = "Europe/London"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

CONTENT_SECURITY_POLICY_REPORT_ONLY = {
    "DIRECTIVES": {
        "default-src": [NONE],
        "img-src": [
            SELF,
            # Google Analytics
            "https://www.googletagmanager.com",
        ],
        "font-src": [SELF],
        "script-src": [
            SELF,
            NONCE,
            # jquery
            "https://code.jquery.com",
            # searchable_select
            "'sha256-K10lU0q0Oi3Wwjp5I3IUreVtxHV5c2e6tUMzazKBxjo='",
            # searchable_select
            "'sha256-SvqgtrmdvMY376buoS0bObmi+nGdnEEbHvJePnMdXa4='",
            # searchable_select
            "'sha256-MXNk1OEwcDStaETBx8zNl9Y061AVFjbowqN8TCN50KQ='",
            # searchable_select
            "'sha256-zxwfckhxf4IOIPf3crNlE7EdgVWHtGFqyGndp/h/0fE='",
            # searchable_select
            "'sha256-YMwcMhkQEhelu2MNRsvB812jMqT/aeLHlLUJ29T7cIw='",
            # searchable_select
            "'sha256-IL1hz2/N+U3AfZl4hpFU67bVZRJMRelB0bv2EuHWiXQ='",
            # multi_value_text_input
            "'sha256-KJRquMJXXF1tDkb5gTZTpZ0Jr5mHLi3mXTTu3UBQzo8='",
            # dynamic-dropdown-search
            "'sha256-uLQsCmEbwl/t20guNF18o9vC6if6d+8Nn7qvtal4VV0='",
            # Google Analytics
            "https://www.googletagmanager.com",
        ],
        "style-src": [
            SELF,
            UNSAFE_INLINE,  # For inline styles in templates
        ],
        "manifest-src": [SELF],
        "connect-src": [
            SELF,
            # Google Analytics
            "https://region1.google-analytics.com",
            "https://www.googletagmanager.com",
        ],
        "form-action": [SELF, "https://login.microsoftonline.com"],
        "frame-ancestors": [
            NONE
        ],  # Prevents clickjacking, is the new X-Frame-Options: DENY
        "report-uri": SENTRY_CSP_REPORT_URI,
    },
}

CONTENT_SECURITY_POLICY = {
    "DIRECTIVES": {
        "default-src": [NONE],
        "img-src": [
            SELF,
            # Google Analytics
            "https://www.googletagmanager.com",
        ],
        "font-src": [SELF],
        "script-src": [
            SELF,
            NONCE,
            # jquery
            "https://code.jquery.com",
            # searchable_select
            "'sha256-K10lU0q0Oi3Wwjp5I3IUreVtxHV5c2e6tUMzazKBxjo='",
            # searchable_select
            "'sha256-SvqgtrmdvMY376buoS0bObmi+nGdnEEbHvJePnMdXa4='",
            # searchable_select
            "'sha256-MXNk1OEwcDStaETBx8zNl9Y061AVFjbowqN8TCN50KQ='",
            # searchable_select
            "'sha256-zxwfckhxf4IOIPf3crNlE7EdgVWHtGFqyGndp/h/0fE='",
            # searchable_select
            "'sha256-YMwcMhkQEhelu2MNRsvB812jMqT/aeLHlLUJ29T7cIw='",
            # searchable_select
            "'sha256-IL1hz2/N+U3AfZl4hpFU67bVZRJMRelB0bv2EuHWiXQ='",
            # multi_value_text_input
            "'sha256-KJRquMJXXF1tDkb5gTZTpZ0Jr5mHLi3mXTTu3UBQzo8='",
            # dynamic-dropdown-search
            "'sha256-uLQsCmEbwl/t20guNF18o9vC6if6d+8Nn7qvtal4VV0='",
            # Google Analytics
            "https://www.googletagmanager.com",
        ],
        "style-src": [
            SELF,
            UNSAFE_INLINE,  # For inline styles in templates
        ],
        "manifest-src": [SELF],
        "connect-src": [
            SELF,
            # Google Analytics
            "https://region1.google-analytics.com",
            "https://www.googletagmanager.com",
        ],
        "form-action": [SELF, "https://login.microsoftonline.com"],
        "frame-ancestors": [
            NONE
        ],  # Prevents clickjacking, is the new X-Frame-Options: DENY
        "report-uri": SENTRY_CSP_REPORT_URI,
    },
}

# Notify API key
NOTIFY_API_KEY = os.environ.get("NOTIFY_API_KEY")

# Notify templates
WARNING_INACTIVE_USERS_TEMPLATE = os.environ.get(
    "WARNING_INACTIVE_USERS_TEMPLATE", "e6ebe47c-cb3f-4323-bc12-6ee1f5ad73a3"
)
SUSPEND_INACTIVE_USERS_TEMPLATE = os.environ.get(
    "SUSPEND_INACTIVE_USERS_TEMPLATE", "7485a142-1966-4273-8cf1-0144e288cca8"
)

# User Authorisation
if ENTRA_ID_ENABLED:
    ENTRA_AUTH = {
        "CLIENT_ID": os.environ.get("ENTRA_CLIENT_ID"),
        "CLIENT_SECRET": os.environ.get("ENTRA_CLIENT_SECRET"),
        "AUTHORITY": os.environ.get("ENTRA_AUTHORITY"),
        "REDIRECT_URI": os.environ.get("ENTRA_REDIRECT_URI"),
        "LOGOUT_REDIRECT": os.environ.get("ENTRA_LOGOUT_REDIRECT"),
        "USERNAME_ATTRIBUTE": os.environ.get("ENTRA_USERNAME_ATTRIBUTE"),
        "SCOPES": ["User.Read"],
        "ALLOWED_TENANTS": str(os.environ.get("ENTRA_ALLOWED_TENANTS")).split(" "),
    }

# Session Settings
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True

# Logging configuration
LOGGING: dict[str, Any] = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": (
                "{asctime} [{levelname}] {name}: "
                "{message} (in {module}.{funcName}:{lineno})"
            ),
            "style": "{",
        },
        "simple": {
            "format": "{levelname} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "stream": sys.stdout,
            "formatter": "verbose",
            "level": "INFO",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "gunicorn.error": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "gunicorn.access": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
    },
}

if "test" in sys.argv:
    LOGGING["root"]["level"] = "CRITICAL"
    for logger in LOGGING.get("loggers", {}).values():
        logger["level"] = "CRITICAL"

    AWS_REGION = "eu-west-2"
    FILE_DOWNLOAD_S3_BUCKET_NAME = "test-bucket"
    SENTRY_LOGS_ENABLED = False

# Sentry Error reporting
if (
    SENTRY_ENABLED
    and os.environ.get("SENTRY_ENVIRONMENT")
    and os.environ.get("SENTRY_DSN")
):
    sentry_sdk.init(
        dsn=os.environ.get("SENTRY_DSN"),
        # setting this to True will include user emails in error logs
        send_default_pii=False,
        enable_logs=SENTRY_LOGS_ENABLED,
        environment=os.environ.get("SENTRY_ENVIRONMENT"),
    )
    sentry_sdk.set_level("warning")
