services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile.local
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8010"
    volumes:
      - ./:/usr/src/app/
    ports:
      - "8010:8010"
    env_file:
      - ./.env
    environment:
      - "DB_HOST=database"
      - "AWS_ACCESS_KEY_ID=test"
      - "AWS_SECRET_ACCESS_KEY=test"
      - "AWS_ENDPOINT_URL=http://localstack:4566/"
  database:
    image: postgres:16.11@sha256:468e1f126ca5af849799cda06ac9b03d8090aae9fa5163408b3e8da44fad0702
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_PASSWORD=${DB_PASSWORD}"
    ports:
      - 5432:5432
  localstack:
    image: localstack/localstack:2026.07.0@sha256:2a81e5da4c32bb53e8d86e92050a12937f9be1915c5a4afad0931f75c112fc7e
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      - DEBUG=${DEBUG:-0}
      - FILE_DOWNLOAD_S3_BUCKET_NAME=test-bucket
      - REGION=eu-west-2
    volumes:
      - "./hfurb_scripts/localstack-script.sh:/etc/localstack/init/ready.d/script.sh"
      - "/var/run/docker.sock:/var/run/docker.sock"
volumes:
  postgres_data:
