# Generated by Django 5.2.7 on 2025-11-26 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("ontology", "0109_alter_mvinteraction_interaction_contact"),
    ]

    operations = [
        migrations.CreateModel(
            name="SponsorDuplicateGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "principal_record",
                    models.ForeignKey(
                        db_column="principal_record_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ontology.mvvolunteer",
                    ),
                ),
                (
                    "sponsors",
                    models.ManyToManyField(
                        db_table="ontology_sponsor_to_duplicate_group",
                        related_name="duplicate_group",
                        to="ontology.mvvolunteer",
                    ),
                ),
            ],
        ),
    ]
