# Generated by Django 5.2.9 on 2026-01-15 16:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("deduplication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sponsorduplicategroup",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
