# Generated by Django 5.2.9 on 2026-01-15 16:30

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("deduplication", "0002_sponsorduplicategroup_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="sponsorduplicategroup",
            name="source_sponsor_ar_mapping",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.JSONField(), default=list, size=None
            ),
        ),
    ]
