# Generated by Django 5.2.9 on 2026-01-27 11:47

import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("deduplication", "0003_sponsorduplicategroup_source_sponsor_ar_mapping"),
        ("ontology", "0115_mvinteraction_linked_sponsor_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GuestDuplicateGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "source_guest_ar_mapping",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.JSONField(), default=list, size=None
                    ),
                ),
                (
                    "guests",
                    models.ManyToManyField(
                        db_table="ontology_guest_to_duplicate_group",
                        related_name="duplicate_group",
                        to="ontology.mvperson",
                    ),
                ),
                (
                    "principal_record",
                    models.ForeignKey(
                        db_column="principal_record_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ontology.mvperson",
                    ),
                ),
            ],
        ),
    ]
