# Generated by Django 5.2.9 on 2026-01-29 09:34

import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("deduplication", "0004_guestduplicategroup"),
        ("ontology", "0116_mvinteraction_linked_accommodation"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccommodationDuplicateGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "source_accommodation_ar_mapping",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.JSONField(), default=list, size=None
                    ),
                ),
                (
                    "accommodations",
                    models.ManyToManyField(
                        db_table="ontology_accommodation_to_duplicate_group",
                        related_name="duplicate_group",
                        to="ontology.mvaccommodation",
                    ),
                ),
                (
                    "principal_record",
                    models.ForeignKey(
                        db_column="principal_record_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ontology.mvaccommodation",
                    ),
                ),
            ],
        ),
    ]
