# Generated by Django 5.2.14 on 2026-07-08 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("deduplication", "0005_accommodationduplicategroup"),
        ("ontology", "0138_mvaccommodation_archived_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="accommodationduplicategroup",
            name="archived_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="accommodationduplicategroup",
            name="is_archived",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="guestduplicategroup",
            name="archived_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="guestduplicategroup",
            name="is_archived",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="sponsorduplicategroup",
            name="archived_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sponsorduplicategroup",
            name="is_archived",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="accommodationduplicategroup",
            name="principal_record",
            field=models.ForeignKey(
                db_column="principal_record_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ontology.mvaccommodation",
            ),
        ),
        migrations.AlterField(
            model_name="guestduplicategroup",
            name="principal_record",
            field=models.ForeignKey(
                db_column="principal_record_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ontology.mvperson",
            ),
        ),
        migrations.AlterField(
            model_name="sponsorduplicategroup",
            name="principal_record",
            field=models.ForeignKey(
                db_column="principal_record_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ontology.mvvolunteer",
            ),
        ),
    ]
