# Generated by Django 5.1.4 on 2025-01-20 15:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "ontology",
            "0002_alter_accommodationmasterrecord_accommodation_availability_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="dataassetforpurpose",
            name="project_permission_ids",
            field=models.ManyToManyField(
                related_name="+", to="ontology.projectpermission"
            ),
        ),
        migrations.AlterField(
            model_name="devcheckv2",
            name="AR_id",
            field=models.ManyToManyField(
                related_name="+", to="ontology.mvaccommodationrequest"
            ),
        ),
        migrations.AlterField(
            model_name="devcheckv2",
            name="accommodation_id",
            field=models.ManyToManyField(
                related_name="+", to="ontology.mvaccommodation"
            ),
        ),
        migrations.AlterField(
            model_name="devcheckv2",
            name="eoi_host_id",
            field=models.ManyToManyField(related_name="+", to="ontology.eoihost"),
        ),
        migrations.AlterField(
            model_name="devcheckv2",
            name="group_id",
            field=models.ManyToManyField(related_name="+", to="ontology.mvgroup"),
        ),
        migrations.AlterField(
            model_name="devcheckv2",
            name="ltla_code",
            field=models.ManyToManyField(
                related_name="+", to="ontology.uklocalauthority"
            ),
        ),
        migrations.AlterField(
            model_name="devcheckv2",
            name="person_id",
            field=models.ManyToManyField(related_name="+", to="ontology.mvperson"),
        ),
        migrations.AlterField(
            model_name="devcheckv2",
            name="sponsor_id",
            field=models.ManyToManyField(related_name="+", to="ontology.mvvolunteer"),
        ),
        migrations.AlterField(
            model_name="eoihost",
            name="sponsor_id",
            field=models.ManyToManyField(related_name="+", to="ontology.mvvolunteer"),
        ),
        migrations.AlterField(
            model_name="estimatedhostrelationship",
            name="accommodation_ids",
            field=models.ManyToManyField(
                related_name="+", to="ontology.mvaccommodation"
            ),
        ),
        migrations.AlterField(
            model_name="estimatedhostrelationship",
            name="sponsor_ids",
            field=models.ManyToManyField(related_name="+", to="ontology.mvvolunteer"),
        ),
        migrations.AlterField(
            model_name="guestevent",
            name="accompanying_person_ids",
            field=models.ManyToManyField(related_name="+", to="ontology.mvperson"),
        ),
        migrations.AlterField(
            model_name="lapbacgroup",
            name="approver_group_ids",
            field=models.ManyToManyField(related_name="+", to="ontology.lapbacgroup"),
        ),
        migrations.AlterField(
            model_name="logbulkupdateestimatedhostrelationship",
            name="host_relationship_v2",
            field=models.ManyToManyField(
                related_name="+", to="ontology.estimatedhostrelationship"
            ),
        ),
        migrations.AlterField(
            model_name="logcreateestimatedhostrelationship",
            name="host_relationship_v2",
            field=models.ManyToManyField(
                related_name="+", to="ontology.estimatedhostrelationship"
            ),
        ),
        migrations.AlterField(
            model_name="logdevbulkapproveprovisionnondisputeddeltaclaims",
            name="delta_claim",
            field=models.ManyToManyField(related_name="+", to="ontology.deltaclaim"),
        ),
        migrations.AlterField(
            model_name="lognewactiona545e0d3ee1026d75a2039d4585d74fd",
            name="delta_claim",
            field=models.ManyToManyField(related_name="+", to="ontology.deltaclaim"),
        ),
        migrations.AlterField(
            model_name="lognewactionb2e61e52169bfd30df795dcd75a4e8fd",
            name="uk_local_authority",
            field=models.ManyToManyField(
                related_name="+", to="ontology.uklocalauthority"
            ),
        ),
        migrations.AlterField(
            model_name="logrestoreestimatedhostrelationship",
            name="host_relationship_v2",
            field=models.ManyToManyField(
                related_name="+", to="ontology.estimatedhostrelationship"
            ),
        ),
        migrations.AlterField(
            model_name="logupdateehrstartdate",
            name="host_relationship_v2",
            field=models.ManyToManyField(
                related_name="+", to="ontology.estimatedhostrelationship"
            ),
        ),
        migrations.AlterField(
            model_name="logupdateestimatedhostrelationship",
            name="host_relationship_v2",
            field=models.ManyToManyField(
                related_name="+", to="ontology.estimatedhostrelationship"
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodation",
            name="sponsorship_certification_number",
            field=models.ManyToManyField(
                related_name="+", to="ontology.sponsorshipcertificationform"
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodationrequest",
            name="ltla_code",
            field=models.ManyToManyField(
                related_name="+", to="ontology.uklocalauthority"
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodationrequest",
            name="previous_accommodation",
            field=models.ManyToManyField(
                related_name="+", to="ontology.mvaccommodation"
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodationrequest",
            name="previous_eoi_hosts",
            field=models.ManyToManyField(related_name="+", to="ontology.eoihost"),
        ),
        migrations.AlterField(
            model_name="mvaccommodationrequest",
            name="sponsorship_certification_number",
            field=models.ManyToManyField(
                related_name="+", to="ontology.sponsorshipcertificationform"
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodationrequest",
            name="utla_code",
            field=models.ManyToManyField(
                related_name="+", to="ontology.uklocalauthority"
            ),
        ),
        migrations.AlterField(
            model_name="mvperson",
            name="previous_group_ids",
            field=models.ManyToManyField(related_name="+", to="ontology.mvgroup"),
        ),
        migrations.AlterField(
            model_name="mvperson",
            name="sponsorship_certification_number",
            field=models.ManyToManyField(
                related_name="+", to="ontology.sponsorshipcertificationform"
            ),
        ),
        migrations.AlterField(
            model_name="mvvolunteer",
            name="sponsorship_certification_number",
            field=models.ManyToManyField(
                related_name="+", to="ontology.sponsorshipcertificationform"
            ),
        ),
        migrations.AlterField(
            model_name="purpose",
            name="purpose_tags",
            field=models.ManyToManyField(related_name="+", to="ontology.purposetags"),
        ),
        migrations.AlterField(
            model_name="reassignmentrequest",
            name="source_ltla_code",
            field=models.ManyToManyField(
                related_name="+", to="ontology.uklocalauthority"
            ),
        ),
        migrations.AlterField(
            model_name="uklocalauthority",
            name="group_ids",
            field=models.ManyToManyField(related_name="+", to="ontology.usergroup"),
        ),
        migrations.AlterField(
            model_name="userinformation",
            name="all_groups",
            field=models.ManyToManyField(related_name="+", to="ontology.lapbacgroup"),
        ),
        migrations.AlterField(
            model_name="userinformation",
            name="immediate_groups",
            field=models.ManyToManyField(related_name="+", to="ontology.lapbacgroup"),
        ),
        migrations.AlterField(
            model_name="usernotification",
            name="recipients",
            field=models.ManyToManyField(related_name="+", to="ontology.foundryusers"),
        ),
        migrations.AlterField(
            model_name="usernotification",
            name="viewer_group_names",
            field=models.ManyToManyField(related_name="+", to="ontology.usergroup"),
        ),
        migrations.AlterField(
            model_name="visainformationrequestcomments",
            name="checks",
            field=models.ManyToManyField(related_name="+", to="ontology.devcheckv2"),
        ),
    ]
