# Generated by Django 5.1.4 on 2025-02-28 15:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ontology", "0003_alter_dataassetforpurpose_project_permission_ids_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="personmasterrecord",
            name="persons",
            field=models.ManyToManyField(
                db_table="person_to_master_record", to="ontology.mvperson"
            ),
        ),
    ]
