# Generated by Django 5.1.4 on 2025-02-16 14:57

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ontology", "0004_personmasterrecord_persons"),
    ]

    operations = [
        migrations.RunSQL(
            """
          create or replace view ops_safeguarding_investigation as
          select ar.id,
                 ar.title,
                 true active_safeguarding_notifications,
                 array_agg(sn.alert_type) alert_types,
                 array(select visa_status from ontology_mvperson p where p.id in (select unnest(ar.person_id))) visa_statuses,
                 array_remove(array_agg(sn.escalation_status), null) escalation_statuses,
                 null deferral_status,
                 array_remove(array_agg(sn.assigned), null) assignees,
                 max(sn.created_at) last_created_at
          from ontology_mvaccommodationrequest ar
                   join ontology_safeguardingnotification sn on sn.ar_id_id = ar.id
          group by ar.id, ar.title;
          """
        ),
        migrations.CreateModel(
            name="OpsSafeguardingInvestigation",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("title", models.TextField(null=True)),
                ("active_safeguarding_notifications", models.BooleanField(null=True)),
                (
                    "alert_types",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), null=True, size=None
                    ),
                ),
                (
                    "visa_statuses",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), null=True, size=None
                    ),
                ),
                (
                    "escalation_statuses",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), null=True, size=None
                    ),
                ),
                ("deferral_status", models.TextField(null=True)),
                (
                    "assignees",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), null=True, size=None
                    ),
                ),
                ("last_created_at", models.DateTimeField(null=True)),
            ],
            options={"db_table": "ops_safeguarding_investigation", "managed": False},
        ),
    ]
