# Generated by Django 5.1.4 on 2025-03-05 12:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ontology", "0008_update_opssafeguardinginvestigation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personmasterrecord",
            name="persons",
            field=models.ManyToManyField(
                db_table="ontology_person_to_master_record", to="ontology.mvperson"
            ),
        ),
    ]
