# Generated by Django 5.1.4 on 2025-03-18 11:41

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ontology", "0009_alter_personmasterrecord_persons"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mvperson",
            name="accommodation_request",
            field=models.ForeignKey(
                db_column="accommodation_request_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="ontology.mvaccommodationrequest",
                verbose_name="Accommodation Request ID",
            ),
        ),
        migrations.AlterField(
            model_name="mvperson",
            name="application_number",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                db_column="application_number",
                null=True,
                size=None,
                verbose_name="Unique Application Number (UAN)",
            ),
        ),
        migrations.AlterField(
            model_name="mvperson",
            name="arrival_date",
            field=models.DateField(
                db_column="arrival_date", null=True, verbose_name="First arrival date"
            ),
        ),
        migrations.AlterField(
            model_name="mvperson",
            name="arrival_port_code",
            field=models.TextField(
                db_column="arrival_port_code",
                null=True,
                verbose_name="First arrival port code",
            ),
        ),
        migrations.AlterField(
            model_name="mvperson",
            name="arrival_port_name",
            field=models.TextField(
                db_column="arrival_port_name",
                null=True,
                verbose_name="First arrival port name",
            ),
        ),
        migrations.AlterField(
            model_name="mvperson",
            name="gender",
            field=models.TextField(db_column="gender", null=True, verbose_name="Sex"),
        ),
        migrations.AlterField(
            model_name="mvperson",
            name="group",
            field=models.ForeignKey(
                db_column="group_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="ontology.mvgroup",
                verbose_name="Group ID",
            ),
        ),
        migrations.AlterField(
            model_name="mvperson",
            name="gwf",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                db_column="gwf",
                null=True,
                size=None,
                verbose_name="Global Web Form number (GWF)",
            ),
        ),
        migrations.AlterField(
            model_name="mvperson",
            name="id",
            field=models.TextField(
                db_column="id", primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="mvperson",
            name="old_group",
            field=models.ForeignKey(
                db_column="old_group_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="ontology.mvgroup",
                verbose_name="Old group ID",
            ),
        ),
        migrations.AlterField(
            model_name="mvperson",
            name="passport_id",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                db_column="passport_id",
                null=True,
                size=None,
                verbose_name="Passport number",
            ),
        ),
        migrations.AlterField(
            model_name="mvperson",
            name="phone",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                db_column="phone",
                null=True,
                size=None,
                verbose_name="Phone number",
            ),
        ),
        migrations.AlterField(
            model_name="mvperson",
            name="previous_group_ids",
            field=models.ManyToManyField(
                db_column="previous_group_ids",
                related_name="+",
                to="ontology.mvgroup",
                verbose_name="Previous group IDs",
            ),
        ),
        migrations.AlterField(
            model_name="mvperson",
            name="sponsorship_certification_number",
            field=models.ManyToManyField(
                db_column="sponsorship_certification_number",
                related_name="+",
                to="ontology.sponsorshipcertificationform",
                verbose_name="Sponsorship certification application number",
            ),
        ),
        migrations.AlterField(
            model_name="mvperson",
            name="travelling_to_uk",
            field=models.BooleanField(
                db_column="travelling_to_uk", null=True, verbose_name="Travelling to UK"
            ),
        ),
        migrations.AlterField(
            model_name="mvperson",
            name="visa_application_date_maximum",
            field=models.DateField(
                db_column="visa_application_date_maximum",
                null=True,
                verbose_name="Latest Visa application date",
            ),
        ),
        migrations.AlterField(
            model_name="mvperson",
            name="visa_status",
            field=models.TextField(
                db_column="visa_status", null=True, verbose_name="Latest visa status"
            ),
        ),
    ]
