# Generated by Django 5.1.4 on 2025-03-18 12:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ontology", "0010_alter_mvperson_accommodation_request_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mvperson",
            name="date_of_first_issue_visa_descision",
            field=models.DateField(
                db_column="date_of_first_issue_visa_descision",
                null=True,
                verbose_name="Earliest issued Visa decision date",
            ),
        ),
        migrations.AddField(
            model_name="mvperson",
            name="upe_visa_status",
            field=models.TextField(
                db_column="upe_visa_status", null=True, verbose_name="UPE Visa status"
            ),
        ),
    ]
