# Generated by Django 5.1.4 on 2025-03-18 12:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ontology", "0011_mvperson_date_of_first_issue_visa_descision_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mvperson",
            name="is_uam",
            field=models.BooleanField(
                db_column="is_uam", null=True, verbose_name="Eligible minor"
            ),
        ),
    ]
