# Generated by Django 5.1.4 on 2025-03-25 16:23

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ontology", "0012_alter_mvperson_is_uam"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mvperson",
            name="accommodation_request",
            field=models.ForeignKey(
                db_column="accommodation_request_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="ontology.mvaccommodationrequest",
                verbose_name="Accommodation request ID",
            ),
        ),
        migrations.AlterField(
            model_name="mvperson",
            name="application_number",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                db_column="application_number",
                null=True,
                size=None,
                verbose_name="Unique application number (UAN)",
            ),
        ),
        migrations.AlterField(
            model_name="mvperson",
            name="date_of_first_issue_visa_descision",
            field=models.DateField(
                db_column="date_of_first_issue_visa_descision",
                null=True,
                verbose_name="Earliest issued visa decision date",
            ),
        ),
        migrations.AlterField(
            model_name="mvperson",
            name="gwf",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                db_column="gwf",
                null=True,
                size=None,
                verbose_name="Global web form number (GWF)",
            ),
        ),
        migrations.AlterField(
            model_name="mvperson",
            name="upe_visa_status",
            field=models.TextField(
                db_column="upe_visa_status", null=True, verbose_name="UPE visa status"
            ),
        ),
        migrations.AlterField(
            model_name="mvperson",
            name="visa_application_date_maximum",
            field=models.DateField(
                db_column="visa_application_date_maximum",
                null=True,
                verbose_name="Latest visa application date",
            ),
        ),
    ]
