# Generated by Django 5.1.4 on 2025-03-25 16:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ontology", "0013_alter_mvperson_accommodation_request_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mvperson",
            name="date_of_first_issue_visa_descision",
        ),
        migrations.AddField(
            model_name="mvperson",
            name="date_of_first_issue_visa_decision",
            field=models.DateField(
                db_column="date_of_first_issue_visa_decision",
                null=True,
                verbose_name="Earliest issued visa decision date",
            ),
        ),
    ]
