# Generated by Django 5.1.4 on 2025-03-27 01:28

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "ontology",
            "0014_remove_mvperson_date_of_first_issue_visa_descision_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="visaapplication",
            name="Q101a_uk_address_staying",
            field=models.TextField(
                db_column="Q101a_uk_address_staying",
                null=True,
                verbose_name="Q101a UK address staying",
            ),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="Q101b_uk_address_staying_local_authority",
            field=models.TextField(
                db_column="Q101b_uk_address_staying_local_authority",
                null=True,
                verbose_name="Q101b UK address staying local authority",
            ),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="Q101c_uk_address_staying_country",
            field=models.TextField(
                db_column="Q101c_uk_address_staying_country",
                null=True,
                verbose_name="Q101c UK address staying country",
            ),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="Q10a_is_one_member_family_ukraine_citizen",
            field=models.TextField(
                db_column="Q10a_is_one_member_family_ukraine_citizen",
                null=True,
                verbose_name="Q10a is one member family Ukraine citizen",
            ),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="Q18a_sponsor_is_in_address_uk",
            field=models.TextField(
                db_column="Q18a_sponsor_is_in_address_uk",
                null=True,
                verbose_name="Q18a sponsor is in address UK",
            ),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="Q18b_sponsor_address_uk",
            field=models.TextField(
                db_column="Q18b_sponsor_address_uk",
                null=True,
                verbose_name="Q18b sponsor address UK",
            ),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="Q18c_sponsor_address_uk_local_authority",
            field=models.TextField(
                db_column="Q18c_sponsor_address_uk_local_authority",
                null=True,
                verbose_name="Q18c sponsor address UK local authority",
            ),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="Q18d_sponsor_address_uk_country",
            field=models.TextField(
                db_column="Q18d_sponsor_address_uk_country",
                null=True,
                verbose_name="Q18d sponsor address UK country",
            ),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="Q22a_sponsor_id_is_valid",
            field=models.TextField(
                db_column="Q22a_sponsor_id_is_valid",
                null=True,
                verbose_name="Q22a sponsor ID is valid",
            ),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="Q22b_sponsor_id_card_number",
            field=models.TextField(
                db_column="Q22b_sponsor_id_card_number",
                null=True,
                verbose_name="Q22b sponsor ID card number",
            ),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="Q22c_sponsor_id_issuing_authority",
            field=models.TextField(
                db_column="Q22c_sponsor_id_issuing_authority",
                null=True,
                verbose_name="Q22c sponsor ID issuing authority",
            ),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="Q22d_sponsor_id_issue_date",
            field=models.DateField(
                db_column="Q22d_sponsor_id_issue_date",
                null=True,
                verbose_name="Q22d sponsor ID issue date",
            ),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="Q22e_sponsor_id_expiry_date",
            field=models.DateField(
                db_column="Q22e_sponsor_id_expiry_date",
                null=True,
                verbose_name="Q22e sponsor ID expiry date",
            ),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="Q2a_living_ukraine_before_jan_22",
            field=models.TextField(
                db_column="Q2a_living_ukraine_before_jan_22",
                null=True,
                verbose_name="Q2a living Ukraine before Jan 22",
            ),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="Q39l_explanation_no_email_communicate_after_application",
            field=models.TextField(
                db_column="Q39l_explanation_no_email_communicate_after_application",
                null=True,
                verbose_name="Q39l explanation no email communicate after applications",
            ),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="Q3a_sponsor_uk_permission",
            field=models.TextField(
                db_column="Q3a_sponsor_uk_permission",
                null=True,
                verbose_name="Q3a sponsor UK permission",
            ),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="Q42a_can_be_contacted_by_telephon",
            field=models.TextField(
                db_column="Q42a_can_be_contacted_by_telephon",
                null=True,
                verbose_name="Q42a can be contacted by telephone",
            ),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="Q47a_lass_ukraine_address",
            field=models.TextField(
                db_column="Q47a_lass_ukraine_address",
                null=True,
                verbose_name="Q47a last Ukraine address",
            ),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="Q64e_is_family_member_travelling_uk",
            field=models.TextField(
                db_column="Q64e_is_family_member_travelling_uk",
                null=True,
                verbose_name="Q64e is family member travelling UK",
            ),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="Q66a_uk_arrival_date",
            field=models.DateField(
                db_column="Q66a_uk_arrival_date",
                null=True,
                verbose_name="Q66a UK arrival date",
            ),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="Q70a_breach_uk_immigration_law",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                db_column="Q70a_breach_uk_immigration_law",
                null=True,
                size=None,
                verbose_name="Q70a breach UK immigration law",
            ),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="Q91b_permission_uk_postcode",
            field=models.TextField(
                db_column="Q91b_permission_uk_postcode",
                null=True,
                verbose_name="Q91b permission UK postcode",
            ),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="Q91c_permission_acl_code",
            field=models.TextField(
                db_column="Q91c_permission_acl_code",
                null=True,
                verbose_name="Q91c permission ACL code",
            ),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="Q91d_permission_brp_collection_location",
            field=models.TextField(
                db_column="Q91d_permission_brp_collection_location",
                null=True,
                verbose_name="Q91d permission BRP collection location",
            ),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="application_unique_application_number",
            field=models.TextField(
                db_column="application_unique_application_number",
                null=True,
                verbose_name="Unique application number (UAN)",
            ),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="gwf",
            field=models.TextField(db_column="gwf", null=True, verbose_name="GWF"),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="ltla_name",
            field=models.TextField(
                db_column="ltla_name", null=True, verbose_name="Lower tier LA name"
            ),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="utla_name",
            field=models.TextField(
                db_column="utla_name", null=True, verbose_name="Upper tier LA name"
            ),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="viewer_group_names_multi_la",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                db_column="viewer_group_names_multi_la",
                null=True,
                size=None,
                verbose_name="Viewer group names multi LA",
            ),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="visa_application_id",
            field=models.TextField(
                db_column="visa_application_id",
                primary_key=True,
                serialize=False,
                verbose_name="Visa application ID",
            ),
        ),
    ]
