# Generated by Django 5.1.4 on 2025-03-31 15:27

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ontology", "0015_alter_visaapplication_q101a_uk_address_staying_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mvvolunteer",
            name="application_unique_application_number",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                db_column="application_unique_application_number",
                null=True,
                size=None,
                verbose_name="Unique application number (UAN)",
            ),
        ),
        migrations.AlterField(
            model_name="mvvolunteer",
            name="expiry_date_id",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                db_column="expiry_date_id",
                null=True,
                size=None,
                verbose_name="Expiry date ID",
            ),
        ),
        migrations.AlterField(
            model_name="mvvolunteer",
            name="gwf",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                db_column="gwf",
                null=True,
                size=None,
                verbose_name="GWF",
            ),
        ),
        migrations.AlterField(
            model_name="mvvolunteer",
            name="id",
            field=models.TextField(
                db_column="id", primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="mvvolunteer",
            name="is_eoi",
            field=models.BooleanField(
                db_column="is_eoi", null=True, verbose_name="Is EOI"
            ),
        ),
        migrations.AlterField(
            model_name="mvvolunteer",
            name="issue_date_id",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                db_column="issue_date_id",
                null=True,
                size=None,
                verbose_name="Issue date ID",
            ),
        ),
        migrations.AlterField(
            model_name="mvvolunteer",
            name="issuing_authority_of_id",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                db_column="issuing_authority_of_id",
                null=True,
                size=None,
                verbose_name="Issuing authority of ID",
            ),
        ),
        migrations.AlterField(
            model_name="mvvolunteer",
            name="previous_id",
            field=models.TextField(
                db_column="previous_id", null=True, verbose_name="Previous ID"
            ),
        ),
        migrations.AlterField(
            model_name="mvvolunteer",
            name="response_id",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                db_column="response_id",
                null=True,
                size=None,
                verbose_name="Response ID",
            ),
        ),
        migrations.AlterField(
            model_name="mvvolunteer",
            name="sponsorship_certification_number",
            field=models.ManyToManyField(
                db_column="sponsorship_certification_number",
                related_name="+",
                to="ontology.sponsorshipcertificationform",
                verbose_name="Sponsorship certification application number",
            ),
        ),
    ]
