# Generated by Django 5.1.4 on 2025-04-02 13:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "ontology",
            "0016_alter_mvvolunteer_application_unique_application_number_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="mvvolunteer",
            name="is_eoi",
            field=models.BooleanField(
                db_column="is_eoi", null=True, verbose_name="Host"
            ),
        ),
        migrations.AlterField(
            model_name="mvvolunteer",
            name="is_sponsor",
            field=models.BooleanField(
                db_column="is_sponsor", null=True, verbose_name="Sponsor"
            ),
        ),
    ]
