# Generated by Django 5.1.8 on 2025-04-07 17:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ontology", "0017_alter_mvvolunteer_is_eoi_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mvaccommodation",
            name="full_address",
            field=models.TextField(
                db_column="full_address", null=True, verbose_name="Address"
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodation",
            name="ltla_name",
            field=models.TextField(
                db_column="ltla_name", null=True, verbose_name="Lower tier LA"
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodation",
            name="utla_name",
            field=models.TextField(
                db_column="utla_name", null=True, verbose_name="Upper tier LA"
            ),
        ),
    ]
