# Generated by Django 5.1.8 on 2025-04-09 10:36

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ontology", "0018_alter_mvaccommodation_full_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mvaccommodationrequest",
            name="accommodation_id",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                db_column="accommodation_id",
                null=True,
                size=None,
                verbose_name="Accommodation ID",
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodationrequest",
            name="active_eoi_host",
            field=models.ForeignKey(
                db_column="active_eoi_host",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="ontology.eoihost",
                verbose_name="Active EOI host",
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodationrequest",
            name="bridging_accommodation_id",
            field=models.TextField(
                db_column="bridging_accommodation_id",
                null=True,
                verbose_name="Bridging accommodation ID",
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodationrequest",
            name="has_uk_consent_doc",
            field=models.BooleanField(
                db_column="has_uk_consent_doc",
                null=True,
                verbose_name="Has UK consent doc",
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodationrequest",
            name="has_ukraine_consent_doc",
            field=models.BooleanField(
                db_column="has_ukraine_consent_doc",
                null=True,
                verbose_name="Has Ukraine consent doc",
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodationrequest",
            name="id",
            field=models.TextField(
                db_column="id", primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodationrequest",
            name="is_eoi_host",
            field=models.BooleanField(
                db_column="is_eoi_host", null=True, verbose_name="Is EOI host"
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodationrequest",
            name="is_uam",
            field=models.BooleanField(
                db_column="is_uam", null=True, verbose_name="Is UAM"
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodationrequest",
            name="is_uam_edited_time",
            field=models.DateTimeField(
                db_column="is_uam_edited_time",
                null=True,
                verbose_name="Is UAM edited time",
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodationrequest",
            name="la_priority",
            field=models.IntegerField(
                db_column="la_priority", null=True, verbose_name="LA priority"
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodationrequest",
            name="la_priority_string",
            field=models.TextField(
                db_column="la_priority_string",
                null=True,
                verbose_name="LA priority string",
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodationrequest",
            name="last_modified_by_org",
            field=models.TextField(
                db_column="last_modified_by_org",
                null=True,
                verbose_name="Last modified by organisation",
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodationrequest",
            name="ltla_code",
            field=models.ManyToManyField(
                db_column="ltla_code",
                related_name="+",
                to="ontology.uklocalauthority",
                verbose_name="LTLA code",
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodationrequest",
            name="ltla_name",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                db_column="ltla_name",
                null=True,
                size=None,
                verbose_name="LTLA name",
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodationrequest",
            name="match_id",
            field=models.TextField(
                db_column="match_id", null=True, verbose_name="Match ID"
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodationrequest",
            name="person_id",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                db_column="person_id",
                null=True,
                size=None,
                verbose_name="Person ID",
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodationrequest",
            name="previous_eoi_hosts",
            field=models.ManyToManyField(
                db_column="previous_eoi_hosts",
                related_name="+",
                to="ontology.eoihost",
                verbose_name="Previous EOI hosts",
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodationrequest",
            name="previous_ids",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                db_column="previous_ids",
                null=True,
                size=None,
                verbose_name="Previous IDs",
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodationrequest",
            name="sponsor_id",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                db_column="sponsor_id",
                null=True,
                size=None,
                verbose_name="Sponsor ID",
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodationrequest",
            name="temporary_accommodation_id",
            field=models.TextField(
                db_column="temporary_accommodation_id",
                null=True,
                verbose_name="Temporary accommodation ID",
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodationrequest",
            name="uk_consent_doc",
            field=models.TextField(
                db_column="uk_consent_doc", null=True, verbose_name="UK consent doc"
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodationrequest",
            name="uk_consent_doc_edited_time",
            field=models.DateTimeField(
                db_column="uk_consent_doc_edited_time",
                null=True,
                verbose_name="UK consent doc edited time",
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodationrequest",
            name="utla_code",
            field=models.ManyToManyField(
                db_column="utla_code",
                related_name="+",
                to="ontology.uklocalauthority",
                verbose_name="UTLA code",
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodationrequest",
            name="utla_name",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                db_column="utla_name",
                null=True,
                size=None,
                verbose_name="UTLA name",
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodationrequest",
            name="will_notify_la_central_case_flag",
            field=models.BooleanField(
                db_column="will_notify_la_central_case_flag",
                null=True,
                verbose_name="Will notify LA central case flag",
            ),
        ),
    ]
