# Generated by Django 5.1.8 on 2025-04-15 15:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ontology", "0019_alter_mvaccommodationrequest_accommodation_id_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mvaccommodation",
            options={"verbose_name": "Accommodation"},
        ),
        migrations.AlterModelOptions(
            name="mvaccommodationrequest",
            options={"verbose_name": "Accommodation Request"},
        ),
        migrations.AlterModelOptions(
            name="mvperson",
            options={"verbose_name": "Guest"},
        ),
        migrations.AlterModelOptions(
            name="mvvolunteer",
            options={"verbose_name": "Host and Sponsor"},
        ),
        migrations.AlterModelOptions(
            name="visaapplication",
            options={"verbose_name": "Visa Application"},
        ),
    ]
