# Generated by Django 5.1.8 on 2025-04-29 16:02

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ontology", "0020_alter_mvaccommodation_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mvaccommodation",
            name="airbnb_avg_rating",
            field=models.FloatField(
                db_column="airbnb_avg_rating",
                null=True,
                verbose_name="Airbnb average rating",
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodation",
            name="airbnb_num_ratings",
            field=models.IntegerField(
                db_column="airbnb_num_ratings",
                null=True,
                verbose_name="Airbnb number of ratings",
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodation",
            name="airbnb_super_host",
            field=models.BooleanField(
                db_column="airbnb_super_host",
                null=True,
                verbose_name="Airbnb Superhost",
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodation",
            name="application_unique_application_number",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                db_column="application_unique_application_number",
                null=True,
                size=None,
                verbose_name="Unique application number (UAN)",
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodation",
            name="google_hotel_num_ratings",
            field=models.IntegerField(
                db_column="google_hotel_num_ratings",
                null=True,
                verbose_name="Google hotel number of ratings",
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodation",
            name="gwf",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                db_column="gwf",
                null=True,
                size=None,
                verbose_name="GWF",
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodation",
            name="host_id",
            field=models.TextField(
                db_column="host_id", null=True, verbose_name="Host ID"
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodation",
            name="id",
            field=models.TextField(
                db_column="id", primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodation",
            name="is_eoi",
            field=models.BooleanField(
                db_column="is_eoi", null=True, verbose_name="Is EOI"
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodation",
            name="response_id",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                db_column="response_id",
                null=True,
                size=None,
                verbose_name="Response ID",
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodation",
            name="submission_guid",
            field=models.TextField(
                db_column="submission_guid", null=True, verbose_name="Submission GUID"
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodation",
            name="submission_guids",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                db_column="submission_guids",
                null=True,
                size=None,
                verbose_name="Submission GUIDs",
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodation",
            name="volunteer_id",
            field=models.TextField(
                db_column="volunteer_id", null=True, verbose_name="Volunteer ID"
            ),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="submission_guid",
            field=models.TextField(
                db_column="submission_guid", null=True, verbose_name="Submission GUID"
            ),
        ),
    ]
