# Generated by Django 5.1.8 on 2025-05-08 10:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ontology", "0021_alter_mvaccommodation_airbnb_avg_rating_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mvaccommodationrequest",
            name="checks_status",
            field=models.TextField(
                choices=[
                    ("CLOSED_LEFT_PROGRAMME", "Closed - Left programme"),
                    ("CHECKS_REQUIRED", "Checks Required"),
                    ("CLOSED_EMPTY", "Closed - Empty"),
                    ("CHECKS_COMPLETED", "Checks Completed"),
                    ("CHECKS_PARTIALLY_COMPLETED", "Checks Partially Completed"),
                    ("SOME_CHECKS_FAILED", "Some Checks Failed"),
                    ("CLOSED_DUPLICATE", "Closed - Duplicate"),
                    ("CANCELLED", "Cancelled"),
                    ("REMATCH_REQUIRED", "Rematch Required"),
                    ("IN_TEMPORARY_ACCOMMODATION", "In Temporary Accommodation"),
                    ("PRE_ARRIVAL_CHECKS_COMPLETE", "Pre-Arrival Checks Complete"),
                ],
                db_column="checks_status",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodationrequest",
            name="safeguarding_status",
            field=models.TextField(
                choices=[
                    ("NO_NOTIFICATIONS", "No Safeguarding Notifications"),
                    ("NO_OPEN_NOTIFICATIONS", "No Open Safeguarding Notifications"),
                    ("ACTIVE_NOTIFICATIONS", "Active Safeguarding Notifications"),
                    (
                        "UNASSIGNED_NOTIFICATIONS",
                        "Unassigned Safeguarding Notifications",
                    ),
                ],
                db_column="safeguarding_status",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodationrequest",
            name="status",
            field=models.TextField(
                choices=[
                    ("ACCOMMODATION_ASSIGNED", "Accommodation Assigned"),
                    ("MISSING_ACCOMMODATION", "Missing Accommodation"),
                    ("ARRIVAL_CONFIRMED", "Arrival Confirmed"),
                ],
                db_column="status",
                null=True,
            ),
        ),
    ]
