# Generated by Django 5.1.8 on 2025-05-08 15:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ontology", "0022_alter_mvaccommodationrequest_checks_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mvaccommodationrequest",
            name="checks_status",
            field=models.TextField(
                choices=[
                    ("Checks Required", "Checks required"),
                    ("Pre-Arrival Checks Complete", "Pre-Arrival checks complete"),
                    ("Checks Partially Completed", "Checks partially completed"),
                    ("Checks Completed", "Checks completed"),
                    ("Some Checks Failed", "Some checks failed"),
                    ("Closed - Duplicate", "Closed - Duplicate"),
                    ("Closed - left programme", "Closed - Left programme"),
                    ("Closed - Empty", "Closed - Empty"),
                    ("Rematch Required", "Rematch required"),
                    ("In Temporary Accommodation", "In temporary accommodation"),
                    ("Cancelled", "Cancelled"),
                ],
                db_column="checks_status",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodationrequest",
            name="safeguarding_status",
            field=models.TextField(
                choices=[
                    ("No Safeguarding Notifications", "No safeguarding notifications"),
                    (
                        "No Open Safeguarding Notifications",
                        "No open safeguarding notifications",
                    ),
                    (
                        "Active Safeguarding Notifications",
                        "Active safeguarding notifications",
                    ),
                    (
                        "Unassigned Safeguarding Notifications",
                        "Unassigned safeguarding notifications",
                    ),
                ],
                db_column="safeguarding_status",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodationrequest",
            name="status",
            field=models.TextField(
                choices=[
                    ("Accommodation Assigned", "Accommodation assigned"),
                    ("Missing Accommodation", "Missing accommodation"),
                    ("Arrival Confirmed", "Arrival confirmed"),
                ],
                db_column="status",
                null=True,
            ),
        ),
    ]
