# Generated by Django 5.1.8 on 2025-05-09 12:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ontology", "0023_alter_mvaccommodationrequest_checks_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="exporttoolobject",
            name="person_earliest_issued_visa_decision_date",
            field=models.DateField(
                db_column="person_earliest_issued_visa_decision_date", null=True
            ),
        ),
        migrations.AddField(
            model_name="exporttoolobject",
            name="person_upe_visa_status",
            field=models.TextField(db_column="person_upe_visa_status", null=True),
        ),
    ]
