# Generated by Django 5.1.8 on 2025-05-09 14:56

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "ontology",
            "0024_exporttoolobject_person_earliest_issued_visa_decision_date_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mvinteraction",
            options={"verbose_name": "Interaction"},
        ),
        migrations.AlterField(
            model_name="mvinteraction",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_column="created_at", null=True
            ),
        ),
        migrations.AlterField(
            model_name="mvinteraction",
            name="created_by",
            field=models.ForeignKey(
                db_column="created_by",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="mvinteraction",
            name="id",
            field=models.TextField(
                db_column="id",
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="mvinteraction",
            name="interaction_contact",
            field=models.TextField(
                choices=[
                    ("Rematch Required", "Rematch Required"),
                    (
                        "Guest is in temporary accommodation",
                        "Rematch Reason Temp Accommodation",
                    ),
                    (
                        "dluhc-PURPOSE-Resettlement_Workflow_USERS-SCOPE-GENERAL-Central Casework Team",
                        "Central Casework Team",
                    ),
                    (
                        "dluhc-PURPOSE-Resettlement_Workflow_USERS-SCOPE-UKVI -UKVI ",
                        "Ukvi Casework Team",
                    ),
                    (
                        "dluhc-PURPOSE-Resettlement_Workflow_USERS-SCOPE-GENERAL-Border Force",
                        "Border Force Purpose",
                    ),
                    (
                        "Rematch Reverted by Central Casework Team",
                        "Rematch Undo Central Case",
                    ),
                    ("Rematch Reverted", "Rematch Undo"),
                    ("Withdrawn Sponsor", "Withdrawn Sponsor"),
                    ("Reverted Sponsor Withdrawal", "Undo Withdraw Sponsor"),
                    ("Indicated End Date", "Indicated End Date"),
                    (
                        "fd6f1237-782b-4879-8718-7aec87de7f7c",
                        "Safeguarding Team Group Id",
                    ),
                    ("Returned To Programme", "Returned To Programme"),
                    ("Leaving Programe", "Leaving Programme"),
                ],
                db_column="interaction_contact",
                null=True,
            ),
        ),
    ]
