# Generated by Django 5.2 on 2025-05-19 11:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ontology", "0025_alter_mvinteraction_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="devcheckv2",
            name="check_status",
            field=models.TextField(
                choices=[
                    ("NOT_STARTED", "Not started"),
                    ("IN_PROGRESS", "In progress"),
                    ("PASSED", "Passed"),
                    ("FAILED", "Failed"),
                    ("NO_LONGER_NEEDED", "No longer needed"),
                ],
                db_column="check_status",
                null=True,
            ),
        ),
    ]
