# Generated by Django 5.1.8 on 2025-05-22 09:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ontology", "0027_rename_devcheckv2_m2m_tables"),
    ]

    operations = [
        migrations.AlterField(
            model_name="checktype",
            name="id",
            field=models.TextField(
                choices=[
                    ("1", "Accomm Exists"),
                    ("2", "Accomm Suitable"),
                    ("3", "Sponsor Dbs"),
                    ("4", "Group Arrived"),
                    ("5", "Sg Checks Complete"),
                    ("6", "Eoi Dbs"),
                    ("7", "Sponsor Accepts Role"),
                    ("8", "Sponsor Arrangements Suitable"),
                    ("9", "Uk Form Uploaded"),
                    ("10", "Ukr Form Uploaded"),
                    ("11", "Ho Checks Household"),
                    ("12", "Ho Checks Sponsor"),
                ],
                db_column="id",
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
