# Generated by Django 5.1.9 on 2025-05-27 16:23

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ontology", "0029_populate_check_type_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mvaccommodationrequest",
            name="accommodation_details_confirmed",
            field=models.BooleanField(
                blank=True, db_column="accommodation_details_confirmed", null=True
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodationrequest",
            name="accommodation_id",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                blank=True,
                db_column="accommodation_id",
                null=True,
                size=None,
                verbose_name="Accommodation ID",
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodationrequest",
            name="active_eoi_host",
            field=models.ForeignKey(
                blank=True,
                db_column="active_eoi_host",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="ontology.eoihost",
                verbose_name="Active EOI host",
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodationrequest",
            name="active_host",
            field=models.ForeignKey(
                blank=True,
                db_column="active_host",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="ontology.mvvolunteer",
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodationrequest",
            name="assignee",
            field=models.TextField(blank=True, db_column="assignee", null=True),
        ),
        migrations.AlterField(
            model_name="mvaccommodationrequest",
            name="bridging_accommodation_id",
            field=models.TextField(
                blank=True,
                db_column="bridging_accommodation_id",
                null=True,
                verbose_name="Bridging accommodation ID",
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodationrequest",
            name="bridging_accommodation_needed",
            field=models.BooleanField(
                blank=True, db_column="bridging_accommodation_needed", null=True
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodationrequest",
            name="cancellation_reason",
            field=models.TextField(
                blank=True, db_column="cancellation_reason", null=True
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodationrequest",
            name="central_case_flag",
            field=models.BooleanField(
                blank=True, db_column="central_case_flag", null=True
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodationrequest",
            name="checks_required",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                blank=True,
                db_column="checks_required",
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodationrequest",
            name="checks_status",
            field=models.TextField(
                blank=True,
                choices=[
                    ("Checks Required", "Checks required"),
                    ("Pre-Arrival Checks Complete", "Pre-Arrival checks complete"),
                    ("Checks Partially Completed", "Checks partially completed"),
                    ("Checks Completed", "Checks completed"),
                    ("Some Checks Failed", "Some checks failed"),
                    ("Closed - Duplicate", "Closed - Duplicate"),
                    ("Closed - left programme", "Closed - Left programme"),
                    ("Closed - Empty", "Closed - Empty"),
                    ("Rematch Required", "Rematch required"),
                    ("In Temporary Accommodation", "In temporary accommodation"),
                    ("Cancelled", "Cancelled"),
                ],
                db_column="checks_status",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodationrequest",
            name="comment",
            field=models.TextField(blank=True, db_column="comment", null=True),
        ),
        migrations.AlterField(
            model_name="mvaccommodationrequest",
            name="confirmed_arrival_date",
            field=models.DateField(
                blank=True, db_column="confirmed_arrival_date", null=True
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodationrequest",
            name="created_at",
            field=models.DateTimeField(blank=True, db_column="created_at", null=True),
        ),
        migrations.AlterField(
            model_name="mvaccommodationrequest",
            name="created_by",
            field=models.TextField(blank=True, db_column="created_by", null=True),
        ),
        migrations.AlterField(
            model_name="mvaccommodationrequest",
            name="date_from",
            field=models.DateField(blank=True, db_column="date_from", null=True),
        ),
        migrations.AlterField(
            model_name="mvaccommodationrequest",
            name="date_till",
            field=models.DateField(blank=True, db_column="date_till", null=True),
        ),
        migrations.AlterField(
            model_name="mvaccommodationrequest",
            name="edited_end_date_at",
            field=models.DateTimeField(
                blank=True, db_column="edited_end_date_at", null=True
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodationrequest",
            name="expected_check_in_date_confirmed",
            field=models.BooleanField(
                blank=True, db_column="expected_check_in_date_confirmed", null=True
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodationrequest",
            name="expected_end_date",
            field=models.DateField(
                blank=True, db_column="expected_end_date", null=True
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodationrequest",
            name="expected_end_date_is_autogenerated",
            field=models.BooleanField(
                blank=True, db_column="expected_end_date_is_autogenerated", null=True
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodationrequest",
            name="first_arrival_date",
            field=models.DateField(
                blank=True, db_column="first_arrival_date", null=True
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodationrequest",
            name="group",
            field=models.ForeignKey(
                blank=True,
                db_column="group_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="ontology.mvgroup",
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodationrequest",
            name="group_details_confirmed",
            field=models.BooleanField(
                blank=True, db_column="group_details_confirmed", null=True
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodationrequest",
            name="has_uk_consent_doc",
            field=models.BooleanField(
                blank=True,
                db_column="has_uk_consent_doc",
                null=True,
                verbose_name="Has UK consent doc",
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodationrequest",
            name="has_ukraine_consent_doc",
            field=models.BooleanField(
                blank=True,
                db_column="has_ukraine_consent_doc",
                null=True,
                verbose_name="Has Ukraine consent doc",
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodationrequest",
            name="have_notified_flag",
            field=models.BooleanField(
                blank=True, db_column="have_notified_flag", null=True
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodationrequest",
            name="is_duplicate",
            field=models.TextField(blank=True, db_column="is_duplicate", null=True),
        ),
        migrations.AlterField(
            model_name="mvaccommodationrequest",
            name="is_eoi_host",
            field=models.BooleanField(
                blank=True,
                db_column="is_eoi_host",
                null=True,
                verbose_name="Is EOI host",
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodationrequest",
            name="is_principal",
            field=models.BooleanField(blank=True, db_column="is_principal", null=True),
        ),
        migrations.AlterField(
            model_name="mvaccommodationrequest",
            name="is_uam",
            field=models.BooleanField(
                blank=True, db_column="is_uam", null=True, verbose_name="Is UAM"
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodationrequest",
            name="is_uam_edited_time",
            field=models.DateTimeField(
                blank=True,
                db_column="is_uam_edited_time",
                null=True,
                verbose_name="Is UAM edited time",
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodationrequest",
            name="la_priority",
            field=models.IntegerField(
                blank=True,
                db_column="la_priority",
                null=True,
                verbose_name="LA priority",
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodationrequest",
            name="la_priority_string",
            field=models.TextField(
                blank=True,
                db_column="la_priority_string",
                null=True,
                verbose_name="LA priority string",
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodationrequest",
            name="last_modified_at",
            field=models.DateTimeField(
                blank=True, db_column="last_modified_at", null=True
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodationrequest",
            name="last_modified_by",
            field=models.TextField(blank=True, db_column="last_modified_by", null=True),
        ),
        migrations.AlterField(
            model_name="mvaccommodationrequest",
            name="last_modified_by_org",
            field=models.TextField(
                blank=True,
                db_column="last_modified_by_org",
                null=True,
                verbose_name="Last modified by organisation",
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodationrequest",
            name="latest_application_date",
            field=models.DateField(
                blank=True, db_column="latest_application_date", null=True
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodationrequest",
            name="linked_adverse_hit",
            field=models.BooleanField(
                blank=True, db_column="linked_adverse_hit", null=True
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodationrequest",
            name="linked_adverse_rematch",
            field=models.BooleanField(
                blank=True, db_column="linked_adverse_rematch", null=True
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodationrequest",
            name="ltla_code",
            field=models.ManyToManyField(
                blank=True,
                db_column="ltla_code",
                related_name="+",
                to="ontology.uklocalauthority",
                verbose_name="LTLA code",
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodationrequest",
            name="ltla_name",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                blank=True,
                db_column="ltla_name",
                null=True,
                size=None,
                verbose_name="LTLA name",
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodationrequest",
            name="match_id",
            field=models.TextField(
                blank=True, db_column="match_id", null=True, verbose_name="Match ID"
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodationrequest",
            name="max_age",
            field=models.IntegerField(blank=True, db_column="max_age", null=True),
        ),
        migrations.AlterField(
            model_name="mvaccommodationrequest",
            name="merged_accommodation_request",
            field=models.ForeignKey(
                blank=True,
                db_column="merged_accommodation_request",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="ontology.mvaccommodationrequest",
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodationrequest",
            name="min_age",
            field=models.IntegerField(blank=True, db_column="min_age", null=True),
        ),
        migrations.AlterField(
            model_name="mvaccommodationrequest",
            name="notional_data",
            field=models.BooleanField(blank=True, db_column="notional_data", null=True),
        ),
        migrations.AlterField(
            model_name="mvaccommodationrequest",
            name="number_of_people",
            field=models.BigIntegerField(
                blank=True, db_column="number_of_people", null=True
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodationrequest",
            name="old_split_accommodation_request",
            field=models.ForeignKey(
                blank=True,
                db_column="old_split_accommodation_request",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="ontology.mvaccommodationrequest",
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodationrequest",
            name="person_id",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                blank=True,
                db_column="person_id",
                null=True,
                size=None,
                verbose_name="Person ID",
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodationrequest",
            name="postcode",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                blank=True,
                db_column="postcode",
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodationrequest",
            name="previous_accommodation",
            field=models.ManyToManyField(
                blank=True,
                db_column="previous_accommodation",
                related_name="+",
                to="ontology.mvaccommodation",
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodationrequest",
            name="previous_eoi_hosts",
            field=models.ManyToManyField(
                blank=True,
                db_column="previous_eoi_hosts",
                related_name="+",
                to="ontology.eoihost",
                verbose_name="Previous EOI hosts",
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodationrequest",
            name="previous_ids",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                blank=True,
                db_column="previous_ids",
                null=True,
                size=None,
                verbose_name="Previous IDs",
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodationrequest",
            name="primary_accommodation",
            field=models.ForeignKey(
                blank=True,
                db_column="primary_accommodation_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="ontology.mvaccommodation",
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodationrequest",
            name="primary_contact_can_be_contacted_by_phone",
            field=models.TextField(
                blank=True,
                db_column="primary_contact_can_be_contacted_by_phone",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodationrequest",
            name="primary_contact_email",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                blank=True,
                db_column="primary_contact_email",
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodationrequest",
            name="primary_contact_email_after_decision",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                blank=True,
                db_column="primary_contact_email_after_decision",
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodationrequest",
            name="primary_contact_email_for_decision",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                blank=True,
                db_column="primary_contact_email_for_decision",
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodationrequest",
            name="primary_contact_email_for_questions",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                blank=True,
                db_column="primary_contact_email_for_questions",
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodationrequest",
            name="primary_contact_first_name",
            field=models.TextField(
                blank=True, db_column="primary_contact_first_name", null=True
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodationrequest",
            name="primary_contact_last_name",
            field=models.TextField(
                blank=True, db_column="primary_contact_last_name", null=True
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodationrequest",
            name="primary_contact_phone",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                blank=True,
                db_column="primary_contact_phone",
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodationrequest",
            name="primary_sponsor",
            field=models.ForeignKey(
                blank=True,
                db_column="primary_sponsor_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="ontology.mvvolunteer",
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodationrequest",
            name="safeguarding_status",
            field=models.TextField(
                blank=True,
                choices=[
                    ("No Safeguarding Notifications", "No safeguarding notifications"),
                    (
                        "No Open Safeguarding Notifications",
                        "No open safeguarding notifications",
                    ),
                    (
                        "Active Safeguarding Notifications",
                        "Active safeguarding notifications",
                    ),
                    (
                        "Unassigned Safeguarding Notifications",
                        "Unassigned safeguarding notifications",
                    ),
                ],
                db_column="safeguarding_status",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodationrequest",
            name="sponsor_background_check_confirmed",
            field=models.BooleanField(
                blank=True, db_column="sponsor_background_check_confirmed", null=True
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodationrequest",
            name="sponsor_id",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                blank=True,
                db_column="sponsor_id",
                null=True,
                size=None,
                verbose_name="Sponsor ID",
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodationrequest",
            name="sponsor_withdrawn",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                blank=True,
                db_column="sponsor_withdrawn",
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodationrequest",
            name="sponsorship_certification_number",
            field=models.ManyToManyField(
                blank=True,
                db_column="sponsorship_certification_number",
                related_name="+",
                to="ontology.sponsorshipcertificationform",
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodationrequest",
            name="status",
            field=models.TextField(
                blank=True,
                choices=[
                    ("Accommodation Assigned", "Accommodation assigned"),
                    ("Missing Accommodation", "Missing accommodation"),
                    ("Arrival Confirmed", "Arrival confirmed"),
                ],
                db_column="status",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodationrequest",
            name="temporary_accommodation_id",
            field=models.TextField(
                blank=True,
                db_column="temporary_accommodation_id",
                null=True,
                verbose_name="Temporary accommodation ID",
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodationrequest",
            name="title",
            field=models.TextField(blank=True, db_column="title", null=True),
        ),
        migrations.AlterField(
            model_name="mvaccommodationrequest",
            name="uk_consent_doc",
            field=models.TextField(
                blank=True,
                db_column="uk_consent_doc",
                null=True,
                verbose_name="UK consent doc",
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodationrequest",
            name="uk_consent_doc_edited_time",
            field=models.DateTimeField(
                blank=True,
                db_column="uk_consent_doc_edited_time",
                null=True,
                verbose_name="UK consent doc edited time",
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodationrequest",
            name="ukraine_consent_doc",
            field=models.TextField(
                blank=True, db_column="ukraine_consent_doc", null=True
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodationrequest",
            name="ukraine_consent_doc_edited_time",
            field=models.DateTimeField(
                blank=True, db_column="ukraine_consent_doc_edited_time", null=True
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodationrequest",
            name="unique_application_number",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                blank=True,
                db_column="unique_application_number",
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodationrequest",
            name="utla_code",
            field=models.ManyToManyField(
                blank=True,
                db_column="utla_code",
                related_name="+",
                to="ontology.uklocalauthority",
                verbose_name="UTLA code",
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodationrequest",
            name="utla_name",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                blank=True,
                db_column="utla_name",
                null=True,
                size=None,
                verbose_name="UTLA name",
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodationrequest",
            name="viewer_group_names",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                blank=True,
                db_column="viewer_group_names",
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodationrequest",
            name="will_notify_la_central_case_flag",
            field=models.BooleanField(
                blank=True,
                db_column="will_notify_la_central_case_flag",
                null=True,
                verbose_name="Will notify LA central case flag",
            ),
        ),
    ]
