# Generated by Django 5.1.9 on 2025-05-29 16:23

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "ontology",
            "0030_alter_mvaccommodationrequest_accommodation_details_confirmed_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="devcheckv2",
            name="AR",
            field=models.ManyToManyField(
                blank=True, db_column="AR_id", to="ontology.mvaccommodationrequest"
            ),
        ),
        migrations.AlterField(
            model_name="devcheckv2",
            name="accommodation",
            field=models.ManyToManyField(
                blank=True,
                db_column="accommodation_id",
                related_name="+",
                to="ontology.mvaccommodation",
            ),
        ),
        migrations.AlterField(
            model_name="devcheckv2",
            name="active",
            field=models.BooleanField(blank=True, db_column="active", null=True),
        ),
        migrations.AlterField(
            model_name="devcheckv2",
            name="check_description",
            field=models.TextField(
                blank=True, db_column="check_description", null=True
            ),
        ),
        migrations.AlterField(
            model_name="devcheckv2",
            name="check_name",
            field=models.TextField(blank=True, db_column="check_name", null=True),
        ),
        migrations.AlterField(
            model_name="devcheckv2",
            name="check_status",
            field=models.TextField(
                blank=True,
                choices=[
                    ("NOT_STARTED", "Not started"),
                    ("IN_PROGRESS", "In progress"),
                    ("PASSED", "Passed"),
                    ("FAILED", "Failed"),
                    ("NO_LONGER_NEEDED", "No longer needed"),
                ],
                db_column="check_status",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="devcheckv2",
            name="check_subtype",
            field=models.TextField(blank=True, db_column="check_subtype", null=True),
        ),
        migrations.AlterField(
            model_name="devcheckv2",
            name="check_type",
            field=models.ForeignKey(
                blank=True,
                db_column="check_type_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="ontology.checktype",
            ),
        ),
        migrations.AlterField(
            model_name="devcheckv2",
            name="create_at",
            field=models.DateTimeField(blank=True, db_column="create_at", null=True),
        ),
        migrations.AlterField(
            model_name="devcheckv2",
            name="create_by",
            field=models.TextField(blank=True, db_column="create_by", null=True),
        ),
        migrations.AlterField(
            model_name="devcheckv2",
            name="document",
            field=models.TextField(blank=True, db_column="document", null=True),
        ),
        migrations.AlterField(
            model_name="devcheckv2",
            name="eoi_host",
            field=models.ManyToManyField(
                blank=True,
                db_column="eoi_host_id",
                related_name="+",
                to="ontology.eoihost",
            ),
        ),
        migrations.AlterField(
            model_name="devcheckv2",
            name="group",
            field=models.ManyToManyField(
                blank=True,
                db_column="group_id",
                related_name="+",
                to="ontology.mvgroup",
            ),
        ),
        migrations.AlterField(
            model_name="devcheckv2",
            name="ltla_code",
            field=models.ManyToManyField(
                blank=True,
                db_column="ltla_code",
                related_name="+",
                to="ontology.uklocalauthority",
            ),
        ),
        migrations.AlterField(
            model_name="devcheckv2",
            name="note",
            field=models.TextField(blank=True, db_column="note", null=True),
        ),
        migrations.AlterField(
            model_name="devcheckv2",
            name="person",
            field=models.ManyToManyField(
                blank=True, db_column="person_id", to="ontology.mvperson"
            ),
        ),
        migrations.AlterField(
            model_name="devcheckv2",
            name="sponsor",
            field=models.ManyToManyField(
                blank=True,
                db_column="sponsor_id",
                related_name="+",
                to="ontology.mvvolunteer",
            ),
        ),
        migrations.AlterField(
            model_name="devcheckv2",
            name="utla_code",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                blank=True,
                db_column="utla_code",
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="devcheckv2",
            name="viewer_group_names",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                blank=True,
                db_column="viewer_group_names",
                null=True,
                size=None,
            ),
        ),
    ]
