# Generated by Django 5.1.9 on 2025-06-04 15:32

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "ontology",
            "0031_alter_devcheckv2_ar_alter_devcheckv2_accommodation_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="mvaccommodation",
            name="accommodation_availability",
            field=models.TextField(
                blank=True, db_column="accommodation_availability", null=True
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodation",
            name="accommodation_provider",
            field=models.TextField(
                blank=True, db_column="accommodation_provider", null=True
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodation",
            name="accommodation_provider_type",
            field=models.TextField(
                blank=True, db_column="accommodation_provider_type", null=True
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodation",
            name="accommodation_type",
            field=models.TextField(
                blank=True, db_column="accommodation_type", null=True
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodation",
            name="airbnb_avg_rating",
            field=models.FloatField(
                blank=True,
                db_column="airbnb_avg_rating",
                null=True,
                verbose_name="Airbnb average rating",
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodation",
            name="airbnb_num_ratings",
            field=models.IntegerField(
                blank=True,
                db_column="airbnb_num_ratings",
                null=True,
                verbose_name="Airbnb number of ratings",
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodation",
            name="airbnb_super_host",
            field=models.BooleanField(
                blank=True,
                db_column="airbnb_super_host",
                null=True,
                verbose_name="Airbnb Superhost",
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodation",
            name="allow_pet",
            field=models.BooleanField(blank=True, db_column="allow_pet", null=True),
        ),
        migrations.AlterField(
            model_name="mvaccommodation",
            name="application_unique_application_number",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                blank=True,
                db_column="application_unique_application_number",
                null=True,
                size=None,
                verbose_name="Unique application number (UAN)",
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodation",
            name="availability_end_date",
            field=models.DateField(
                blank=True, db_column="availability_end_date", null=True
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodation",
            name="availability_start_date",
            field=models.DateField(
                blank=True, db_column="availability_start_date", null=True
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodation",
            name="building_name",
            field=models.TextField(blank=True, db_column="building_name", null=True),
        ),
        migrations.AlterField(
            model_name="mvaccommodation",
            name="building_number",
            field=models.TextField(blank=True, db_column="building_number", null=True),
        ),
        migrations.AlterField(
            model_name="mvaccommodation",
            name="can_be_considered_for_accommodation",
            field=models.BooleanField(
                blank=True, db_column="can_be_considered_for_accommodation", null=True
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodation",
            name="comments",
            field=models.TextField(blank=True, db_column="comments", null=True),
        ),
        migrations.AlterField(
            model_name="mvaccommodation",
            name="country",
            field=models.TextField(blank=True, db_column="country", null=True),
        ),
        migrations.AlterField(
            model_name="mvaccommodation",
            name="created_at",
            field=models.DateTimeField(blank=True, db_column="created_at", null=True),
        ),
        migrations.AlterField(
            model_name="mvaccommodation",
            name="created_by",
            field=models.TextField(blank=True, db_column="created_by", null=True),
        ),
        migrations.AlterField(
            model_name="mvaccommodation",
            name="created_date",
            field=models.DateTimeField(blank=True, db_column="created_date", null=True),
        ),
        migrations.AlterField(
            model_name="mvaccommodation",
            name="current_capacity",
            field=models.IntegerField(
                blank=True, db_column="current_capacity", null=True
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodation",
            name="deliminated_address",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(blank=True, null=True),
                blank=True,
                db_column="deliminated_address",
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodation",
            name="family_friendly",
            field=models.BooleanField(
                blank=True, db_column="family_friendly", null=True
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodation",
            name="full_address",
            field=models.TextField(
                blank=True, db_column="full_address", null=True, verbose_name="Address"
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodation",
            name="geohash",
            field=models.TextField(blank=True, db_column="geohash", null=True),
        ),
        migrations.AlterField(
            model_name="mvaccommodation",
            name="google_hotel_num_ratings",
            field=models.IntegerField(
                blank=True,
                db_column="google_hotel_num_ratings",
                null=True,
                verbose_name="Google hotel number of ratings",
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodation",
            name="google_hotel_rating",
            field=models.FloatField(
                blank=True, db_column="google_hotel_rating", null=True
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodation",
            name="gwf",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                blank=True,
                db_column="gwf",
                null=True,
                size=None,
                verbose_name="GWF",
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodation",
            name="handrails_leading_to_main_entrance",
            field=models.BooleanField(
                blank=True, db_column="handrails_leading_to_main_entrance", null=True
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodation",
            name="host_id",
            field=models.TextField(
                blank=True, db_column="host_id", null=True, verbose_name="Host ID"
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodation",
            name="inspection_date",
            field=models.DateField(blank=True, db_column="inspection_date", null=True),
        ),
        migrations.AlterField(
            model_name="mvaccommodation",
            name="is_accommodation",
            field=models.BooleanField(
                blank=True, db_column="is_accommodation", null=True
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodation",
            name="is_available_for_rematch",
            field=models.BooleanField(
                blank=True, db_column="is_available_for_rematch", null=True
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodation",
            name="is_eoi",
            field=models.BooleanField(
                blank=True, db_column="is_eoi", null=True, verbose_name="Is EOI"
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodation",
            name="is_principal",
            field=models.BooleanField(blank=True, db_column="is_principal", null=True),
        ),
        migrations.AlterField(
            model_name="mvaccommodation",
            name="is_residential",
            field=models.BooleanField(
                blank=True, db_column="is_residential", null=True
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodation",
            name="last_modified_date",
            field=models.DateTimeField(
                blank=True, db_column="last_modified_date", null=True
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodation",
            name="listed_capacity",
            field=models.IntegerField(
                blank=True, db_column="listed_capacity", null=True
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodation",
            name="local_authority",
            field=models.TextField(blank=True, db_column="local_authority", null=True),
        ),
        migrations.AlterField(
            model_name="mvaccommodation",
            name="ltla_name",
            field=models.TextField(
                blank=True,
                db_column="ltla_name",
                null=True,
                verbose_name="Lower tier LA",
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodation",
            name="notional_data",
            field=models.BooleanField(blank=True, db_column="notional_data", null=True),
        ),
        migrations.AlterField(
            model_name="mvaccommodation",
            name="number_adults",
            field=models.BigIntegerField(
                blank=True, db_column="number_adults", null=True
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodation",
            name="number_children",
            field=models.BigIntegerField(
                blank=True, db_column="number_children", null=True
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodation",
            name="number_of_double_rooms_available",
            field=models.BigIntegerField(
                blank=True, db_column="number_of_double_rooms_available", null=True
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodation",
            name="number_of_single_rooms",
            field=models.BigIntegerField(
                blank=True, db_column="number_of_single_rooms", null=True
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodation",
            name="pest_infestation",
            field=models.BooleanField(
                blank=True, db_column="pest_infestation", null=True
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodation",
            name="postcode",
            field=models.ForeignKey(
                blank=True,
                db_column="postcode",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="ontology.mvukpostcode",
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodation",
            name="reference",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                blank=True,
                db_column="reference",
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodation",
            name="requested_checks_latest_date",
            field=models.DateTimeField(
                blank=True, db_column="requested_checks_latest_date", null=True
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodation",
            name="response_id",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                blank=True,
                db_column="response_id",
                null=True,
                size=None,
                verbose_name="Response ID",
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodation",
            name="roof_in_good_shape",
            field=models.BooleanField(
                blank=True, db_column="roof_in_good_shape", null=True
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodation",
            name="source",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                blank=True,
                db_column="source",
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodation",
            name="sponsorship_certification_number",
            field=models.ManyToManyField(
                blank=True,
                db_column="sponsorship_certification_number",
                related_name="+",
                to="ontology.sponsorshipcertificationform",
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodation",
            name="step_free_access",
            field=models.BooleanField(
                blank=True, db_column="step_free_access", null=True
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodation",
            name="street_name_1",
            field=models.TextField(blank=True, db_column="street_name_1", null=True),
        ),
        migrations.AlterField(
            model_name="mvaccommodation",
            name="street_name_2",
            field=models.TextField(blank=True, db_column="street_name_2", null=True),
        ),
        migrations.AlterField(
            model_name="mvaccommodation",
            name="streetview_link",
            field=models.TextField(blank=True, db_column="streetview_link", null=True),
        ),
        migrations.AlterField(
            model_name="mvaccommodation",
            name="submission_guid",
            field=models.TextField(
                blank=True,
                db_column="submission_guid",
                null=True,
                verbose_name="Submission GUID",
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodation",
            name="submission_guids",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                blank=True,
                db_column="submission_guids",
                null=True,
                size=None,
                verbose_name="Submission GUIDs",
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodation",
            name="submitted_date",
            field=models.DateTimeField(
                blank=True, db_column="submitted_date", null=True
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodation",
            name="sufficient_smoke_alarms",
            field=models.BooleanField(
                blank=True, db_column="sufficient_smoke_alarms", null=True
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodation",
            name="town_city",
            field=models.TextField(blank=True, db_column="town_city", null=True),
        ),
        migrations.AlterField(
            model_name="mvaccommodation",
            name="unsubscribed",
            field=models.BooleanField(blank=True, db_column="unsubscribed", null=True),
        ),
        migrations.AlterField(
            model_name="mvaccommodation",
            name="unsuitable",
            field=models.BooleanField(blank=True, db_column="unsuitable", null=True),
        ),
        migrations.AlterField(
            model_name="mvaccommodation",
            name="up_to_code",
            field=models.BooleanField(blank=True, db_column="up_to_code", null=True),
        ),
        migrations.AlterField(
            model_name="mvaccommodation",
            name="uprn_accommodation",
            field=models.ForeignKey(
                blank=True,
                db_column="uprn_accommodation",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="ontology.uprnaddress",
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodation",
            name="utla_name",
            field=models.TextField(
                blank=True,
                db_column="utla_name",
                null=True,
                verbose_name="Upper tier LA",
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodation",
            name="viewer_group_names",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                blank=True,
                db_column="viewer_group_names",
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodation",
            name="volunteer_id",
            field=models.TextField(
                blank=True,
                db_column="volunteer_id",
                null=True,
                verbose_name="Volunteer ID",
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodation",
            name="what_type_of_living_space_can_you_offer",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                blank=True,
                db_column="what_type_of_living_space_can_you_offer",
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodation",
            name="wheelchair_accessible",
            field=models.BooleanField(
                blank=True, db_column="wheelchair_accessible", null=True
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodation",
            name="who_can_you_accommodate",
            field=models.TextField(
                blank=True, db_column="who_can_you_accommodate", null=True
            ),
        ),
    ]
