# Generated by Django 5.2.2 on 2025-06-05 15:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ontology", "0032_alter_mvaccommodation_accommodation_availability_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="devcheckv2",
            name="active",
            field=models.BooleanField(
                blank=True, db_column="active", default=True, null=True
            ),
        ),
    ]
