# Generated by Django 5.1.9 on 2025-06-10 11:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ontology", "0033_alter_devcheckv2_active"),
    ]

    operations = [
        migrations.RenameField(
            model_name="mvaccommodation",
            old_name="host_id",
            new_name="host_id_DEPRECATED",
        ),
        migrations.AddField(
            model_name="mvaccommodation",
            name="hosts",
            field=models.ManyToManyField(
                db_table="ontology_sponsor_to_accommodation",
                related_name="accommodations",
                to="ontology.mvvolunteer",
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodation",
            name="accommodation_type",
            field=models.TextField(
                blank=True,
                choices=[
                    ("Sponsor Accommodation", "Sponsor Accommodation"),
                    ("Temporary Accommodation", "Temporary Accommodation"),
                ],
                db_column="accommodation_type",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="mvvolunteer",
            name="sponsor_type",
            field=models.TextField(
                choices=[
                    ("Individual", "Individual"),
                    ("Local Authority", "Local Authority"),
                    ("Org", "Org"),
                ],
                db_column="sponsor_type",
                null=True,
            ),
        ),
    ]
