# Generated by Django 5.1.9 on 2025-06-10 14:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ontology", "0034_rename_host_id_mvaccommodation_host_id_deprecated_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="devcheckv2",
            name="AR",
            field=models.ManyToManyField(
                blank=True,
                db_column="AR_id",
                related_name="checks",
                to="ontology.mvaccommodationrequest",
            ),
        ),
        migrations.AlterField(
            model_name="devcheckv2",
            name="accommodation",
            field=models.ManyToManyField(
                blank=True,
                db_column="accommodation_id",
                related_name="checks",
                to="ontology.mvaccommodation",
            ),
        ),
        migrations.AlterField(
            model_name="devcheckv2",
            name="check_subtype",
            field=models.TextField(
                blank=True,
                choices=[("Enhanced", "Enhanced"), ("Basic", "Basic")],
                db_column="check_subtype",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="devcheckv2",
            name="eoi_host",
            field=models.ManyToManyField(
                blank=True,
                db_column="eoi_host_id",
                related_name="checks",
                to="ontology.eoihost",
            ),
        ),
        migrations.AlterField(
            model_name="devcheckv2",
            name="group",
            field=models.ManyToManyField(
                blank=True,
                db_column="group_id",
                related_name="checks",
                to="ontology.mvgroup",
            ),
        ),
        migrations.AlterField(
            model_name="devcheckv2",
            name="person",
            field=models.ManyToManyField(
                blank=True,
                db_column="person_id",
                related_name="checks",
                to="ontology.mvperson",
            ),
        ),
        migrations.AlterField(
            model_name="devcheckv2",
            name="sponsor",
            field=models.ManyToManyField(
                blank=True,
                db_column="sponsor_id",
                related_name="checks",
                to="ontology.mvvolunteer",
            ),
        ),
    ]
