# Generated by Django 5.1.8 on 2025-06-16 11:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "ontology",
            "0035_alter_devcheckv2_ar_alter_devcheckv2_accommodation_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="mvperson",
            name="upe_visa_status",
            field=models.TextField(
                choices=[
                    ("NO_OUTCOME", "No UPE visa application outcome"),
                    ("UPE_VISA_ACCEPTED", "UPE visa accepted"),
                    ("UPE_VISA_REFUSED", "UPE visa refused"),
                    ("UPE_VISA_REJECTED", "UPE visa rejected"),
                    ("UPE_VISA_WITHDRAWN", "UPE visa withdrawn"),
                ],
                db_column="upe_visa_status",
                null=True,
                verbose_name="UPE visa status",
            ),
        ),
    ]
