# Generated by Django 5.2.2 on 2025-06-18 09:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ontology", "0036_alter_mvperson_upe_visa_status"),
        ("ontology", "0036_create_host_and_ghost_temp_accom_for_each_ltla"),
    ]

    operations = []
