# Generated by Django 5.2.2 on 2025-06-19 09:16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ontology", "0037_merge_20250618_1023"),
    ]

    operations = [
        migrations.AddField(
            model_name="reassignmentrequest",
            name="person_id",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                blank=True,
                db_column="person_id",
                null=True,
                size=None,
                verbose_name="Person ID",
            ),
        ),
    ]
