# Generated by Django 5.2.2 on 2025-06-19 09:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ontology", "0038_reassignmentrequest_person_id"),
        ("ontology", "0038_simplify_temporary_accommodation_names"),
    ]

    operations = []
