# Generated by Django 5.2.2 on 2025-06-30 08:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ontology", "0039_merge_20250619_1040"),
    ]

    operations = [
        migrations.AlterField(
            model_name="devcheckv2",
            name="check_subtype",
            field=models.TextField(blank=True, db_column="check_subtype", null=True),
        ),
    ]
