# Generated by Django 5.2.2 on 2025-06-24 15:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ontology", "0039_merge_20250619_1040"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reassignmentrequest",
            name="person_id",
        ),
        migrations.AddField(
            model_name="reassignmentrequest",
            name="guests",
            field=models.ManyToManyField(blank=True, to="ontology.mvperson"),
        ),
    ]
