# Generated by Django 5.2.2 on 2025-06-26 12:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ontology", "0040_remove_reassignmentrequest_person_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reassignmentrequest",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_column="created_at", null=True
            ),
        ),
        migrations.AlterField(
            model_name="reassignmentrequest",
            name="outcome",
            field=models.TextField(
                choices=[
                    ("ACCEPTED", "Accepted"),
                    ("REJECTED", "Rejected"),
                    ("PENDING", "Pending"),
                    ("NEEDS_ACCOMMODATION_REQUEST", "Needs Accommodation Request"),
                ],
                db_column="outcome",
                null=True,
            ),
        ),
    ]
