# Generated by Django 5.2.2 on 2025-06-30 09:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ontology", "0040_alter_devcheckv2_check_subtype"),
        ("ontology", "0041_alter_reassignmentrequest_created_at_and_more"),
    ]

    operations = []
