# Generated by Django 5.2.2 on 2025-06-30 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ontology", "0042_merge_20250630_1001"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reassignmentrequest",
            name="accommodation_request",
            field=models.ForeignKey(
                db_column="accommodation_request_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reassignment_requests",
                to="ontology.mvaccommodationrequest",
            ),
        ),
    ]
