# Generated by Django 5.2.2 on 2025-07-02 23:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ontology", "0043_alter_reassignmentrequest_accommodation_request"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reassignmentrequest",
            name="proposed_at",
            field=models.DateTimeField(
                auto_now_add=True, db_column="proposed_at", null=True
            ),
        ),
    ]
