# Generated by Django 5.2.2 on 2025-07-10 14:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ontology", "0044_alter_reassignmentrequest_proposed_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="reassignmentrequest",
            name="created_by",
            field=models.ForeignKey(
                db_column="created_by",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_reassignment_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="reassignmentrequest",
            name="proposed_by",
            field=models.ForeignKey(
                db_column="proposed_by",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="proposed_reassignment_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="reassignmentrequest",
            name="responded_by",
            field=models.ForeignKey(
                db_column="responded_by",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="responded_reassignment_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
