# Generated by Django 5.2.2 on 2025-07-16 18:07

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ontology", "0045_alter_reassignmentrequest_created_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mvaccommodation",
            name="sponsorship_certification_number_id",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                blank=True,
                db_column="sponsorship_certification_number",
                null=True,
                size=None,
                verbose_name="Sponsorship certification application number",
            ),
        ),
        migrations.AddField(
            model_name="mvaccommodationrequest",
            name="in_temporary_accommodation",
            field=models.BooleanField(
                blank=True, db_column="in_temporary_accommodation", null=True
            ),
        ),
        migrations.AddField(
            model_name="mvaccommodationrequest",
            name="ltla_code_id",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                blank=True,
                db_column="ltla_code",
                null=True,
                size=None,
                verbose_name="LTLA code ID",
            ),
        ),
        migrations.AddField(
            model_name="mvaccommodationrequest",
            name="previous_accommodation_id",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                blank=True,
                db_column="previous_accommodation",
                null=True,
                size=None,
                verbose_name="Previous accommodation ID",
            ),
        ),
        migrations.AddField(
            model_name="mvaccommodationrequest",
            name="previous_eoi_host_id",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                blank=True,
                db_column="previous_eoi_hosts",
                null=True,
                size=None,
                verbose_name="Previous EOI host ID",
            ),
        ),
        migrations.AddField(
            model_name="mvaccommodationrequest",
            name="sponsorship_certification_number_id",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                blank=True,
                db_column="sponsorship_certification_number",
                null=True,
                size=None,
                verbose_name="Sponsorship certification application number",
            ),
        ),
        migrations.AddField(
            model_name="mvgroup",
            name="sponsorship_certification_number_id",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                blank=True,
                db_column="sponsorship_certification_number",
                null=True,
                size=None,
                verbose_name="Sponsorship certification application number",
            ),
        ),
        migrations.AddField(
            model_name="mvperson",
            name="is_uam_edited_time",
            field=models.DateTimeField(db_column="is_uam_edited_time", null=True),
        ),
        migrations.AddField(
            model_name="mvperson",
            name="previous_group_id",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                blank=True,
                db_column="previous_group_id",
                null=True,
                size=None,
                verbose_name="Previous group ID",
            ),
        ),
        migrations.AddField(
            model_name="mvperson",
            name="sponsorship_certification_number_id",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                blank=True,
                db_column="sponsorship_certification_number",
                null=True,
                size=None,
                verbose_name="Sponsorship certification application number",
            ),
        ),
        migrations.AddField(
            model_name="mvukpostcode",
            name="ltla_name",
            field=models.TextField(db_column="ltla_name", null=True),
        ),
        migrations.AddField(
            model_name="mvukpostcode",
            name="notional_data",
            field=models.BooleanField(db_column="notional_data", null=True),
        ),
        migrations.AddField(
            model_name="mvukpostcode",
            name="utla_name",
            field=models.TextField(db_column="utla_name", null=True),
        ),
        migrations.AddField(
            model_name="mvvolunteer",
            name="sponsorship_certification_number_id",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                blank=True,
                db_column="sponsorship_certification_number",
                null=True,
                size=None,
                verbose_name="Sponsorship certification application number",
            ),
        ),
        migrations.AddField(
            model_name="uklocalauthority",
            name="checks_passed_series",
            field=models.TextField(db_column="checks_passed_series", null=True),
        ),
        migrations.AddField(
            model_name="uklocalauthority",
            name="group_id",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                db_column="group_ids",
                null=True,
                size=None,
                verbose_name="Group ID",
            ),
        ),
        migrations.AlterField(
            model_name="mvperson",
            name="previous_group_leaving_times",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.DateTimeField(),
                db_column="previous_group_leaving_times",
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="mvperson",
            name="visa_application_dates",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.DateField(),
                db_column="visa_application_dates",
                null=True,
                size=None,
            ),
        ),
    ]
