# Generated by Django 5.2.2 on 2025-07-17 15:30

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "ontology",
            "0046_mvaccommodation_sponsorship_certification_number_id_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="mvaccommodationrequest",
            name="utla_code_id",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                blank=True,
                db_column="utla_code",
                null=True,
                size=None,
                verbose_name="UTLA code",
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodation",
            name="postcode",
            field=models.TextField(blank=True, db_column="postcode", null=True),
        ),
        migrations.AlterField(
            model_name="mvperson",
            name="previous_group_id",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                blank=True,
                db_column="previous_group_ids",
                null=True,
                size=None,
                verbose_name="Previous group ID",
            ),
        ),
    ]
