# Generated by Django 5.2.2 on 2025-07-18 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ontology", "0047_mvaccommodationrequest_utla_code_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mvaccommodation",
            name="postcode",
            field=models.ForeignKey(
                blank=True,
                db_column="postcode",
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="ontology.mvukpostcode",
            ),
        ),
    ]
