# Generated by Django 5.2.2 on 2025-07-28 04:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ontology", "0048_alter_mvaccommodation_postcode"),
    ]

    operations = [
        migrations.AddField(
            model_name="sponsorshipcertificationform",
            name="ltla_name",
            field=models.TextField(
                blank=True,
                db_column="ltla_name",
                null=True,
                verbose_name="Lower tier LA",
            ),
        ),
        migrations.AddField(
            model_name="sponsorshipcertificationform",
            name="utla_name",
            field=models.TextField(
                blank=True,
                db_column="utla_name",
                null=True,
                verbose_name="Upper tier LA",
            ),
        ),
    ]
