# Generated by Django 5.2.2 on 2025-07-22 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ontology", "0048_alter_mvaccommodation_postcode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visainformationrequestcomments",
            name="visa_information_request",
            field=models.ForeignKey(
                db_column="visa_information_request_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vir_comments",
                to="ontology.visainformationrequest",
            ),
        ),
    ]
