# Generated by Django 5.2.2 on 2025-07-23 14:05

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "ontology",
            "0049_alter_visainformationrequestcomments_visa_information_request",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="visainformationrequest",
            name="request_type",
            field=models.TextField(
                choices=[
                    ("GENERAL", "General"),
                    ("CHILD_SPONSORED_BY_PARENTS", "Child sponsored by parents"),
                ],
                db_column="request_type",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="visainformationrequest",
            name="requested_check_type_id",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(
                    choices=[
                        ("ACCOMM_SUITABLE", "Accommodation is suitable"),
                        ("SPONSOR_DBS", "DBS and sponsor is suitable"),
                    ]
                ),
                db_column="requested_check_type_id",
                null=True,
                size=None,
            ),
        ),
    ]
