# Generated by Django 5.2.2 on 2025-07-23 12:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "ontology",
            "0049_alter_visainformationrequestcomments_visa_information_request",
        ),
        ("ontology", "0049_remove_mvaccommodation_volunteer_id_and_more"),
    ]

    operations = []
