# Generated by Django 5.2.2 on 2025-07-23 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ontology", "0050_merge_20250723_1338"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mvaccommodation",
            name="hosts",
            field=models.ManyToManyField(
                db_constraint=False,
                db_table="ontology_sponsor_to_accommodation",
                related_name="accommodations",
                to="ontology.mvvolunteer",
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodation",
            name="uprn_accommodation",
            field=models.ForeignKey(
                blank=True,
                db_column="uprn_accommodation",
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="ontology.uprnaddress",
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodationrequest",
            name="active_eoi_host",
            field=models.ForeignKey(
                blank=True,
                db_column="active_eoi_host",
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="ontology.eoihost",
                verbose_name="Active EOI host",
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodationrequest",
            name="active_host",
            field=models.ForeignKey(
                blank=True,
                db_column="active_host",
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="ontology.mvvolunteer",
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodationrequest",
            name="group",
            field=models.ForeignKey(
                blank=True,
                db_column="group_id",
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="ontology.mvgroup",
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodationrequest",
            name="old_split_accommodation_request",
            field=models.ForeignKey(
                blank=True,
                db_column="old_split_accommodation_request",
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="ontology.mvaccommodationrequest",
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodationrequest",
            name="previous_eoi_hosts",
            field=models.ManyToManyField(
                blank=True,
                db_column="previous_eoi_hosts",
                db_constraint=False,
                related_name="+",
                to="ontology.eoihost",
                verbose_name="Previous EOI hosts",
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodationrequest",
            name="primary_accommodation",
            field=models.ForeignKey(
                blank=True,
                db_column="primary_accommodation_id",
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="ontology.mvaccommodation",
            ),
        ),
        migrations.AlterField(
            model_name="mvaccommodationrequest",
            name="primary_sponsor",
            field=models.ForeignKey(
                blank=True,
                db_column="primary_sponsor_id",
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="ontology.mvvolunteer",
            ),
        ),
    ]
