# Generated by Django 5.2.2 on 2025-07-23 14:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ontology", "0050_alter_visainformationrequest_request_type_and_more"),
        ("ontology", "0050_merge_20250723_1338"),
    ]

    operations = []
