# Generated by Django 5.2.2 on 2025-07-28 04:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ontology", "0049_sponsorshipcertificationform_ltla_name_and_more"),
        ("ontology", "0051_alter_mvaccommodation_hosts_and_more"),
    ]

    operations = []
