# Generated by Django 5.2.2 on 2025-07-23 15:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ontology", "0051_merge_20250723_1512"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visainformationrequest",
            name="request_status",
            field=models.TextField(
                choices=[("OPEN", "Open"), ("CLOSED", "Closed")],
                db_column="request_status",
                default="OPEN",
                null=True,
            ),
        ),
    ]
