# Generated by Django 5.2.2 on 2025-07-28 09:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ontology", "0051_alter_mvaccommodation_hosts_and_more"),
        ("ontology", "0052_alter_visainformationrequest_request_status"),
    ]

    operations = []
