# Generated by Django 5.2.2 on 2025-07-29 09:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ontology", "0053_merge_20250728_1057"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visainformationrequest",
            name="request_status",
            field=models.TextField(
                choices=[
                    ("NOT_STARTED", "Not started"),
                    ("AWAITING_UKVI", "Awaiting UKVI"),
                    ("AWAITING_LA", "Awaiting LA"),
                    ("CLOSED", "Closed"),
                ],
                db_column="request_status",
                null=True,
            ),
        ),
    ]
