# Generated by Django 5.2.2 on 2025-07-29 17:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ontology", "0052_merge_20250728_0546"),
        ("ontology", "0054_alter_visainformationrequest_request_status"),
    ]

    operations = []
