# Generated by Django 5.2.2 on 2025-07-25 13:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ontology", "0055_merge_20250729_1815"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sponsorshipcertificationform",
            options={"verbose_name": "Uam"},
        ),
    ]
