# Generated by Django 5.2.2 on 2025-07-30 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ontology", "0056_alter_sponsorshipcertificationform_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="visainformationrequest",
            name="visa_application",
            field=models.ForeignKey(
                blank=True,
                db_column="visa_application",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="ontology.visaapplication",
            ),
        ),
    ]
