# Generated by Django 5.2.2 on 2025-08-01 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ontology", "0057_visainformationrequest_visa_application"),
    ]

    operations = [
        migrations.AddField(
            model_name="safeguardingnotification",
            name="deferral_status",
            field=models.TextField(db_column="deferral_status", null=True),
        ),
        migrations.AlterField(
            model_name="devcheckv2",
            name="accommodation",
            field=models.ManyToManyField(
                blank=True,
                db_column="accommodation_id",
                db_constraint=False,
                related_name="checks",
                to="ontology.mvaccommodation",
            ),
        ),
        migrations.AlterField(
            model_name="devcheckv2",
            name="group",
            field=models.ManyToManyField(
                blank=True,
                db_column="group_id",
                db_constraint=False,
                related_name="checks",
                to="ontology.mvgroup",
            ),
        ),
        migrations.AlterField(
            model_name="devcheckv2",
            name="ltla_code",
            field=models.ManyToManyField(
                blank=True,
                db_column="ltla_code",
                db_constraint=False,
                related_name="+",
                to="ontology.uklocalauthority",
            ),
        ),
        migrations.AlterField(
            model_name="devcheckv2",
            name="person",
            field=models.ManyToManyField(
                blank=True,
                db_column="person_id",
                db_constraint=False,
                related_name="checks",
                to="ontology.mvperson",
            ),
        ),
        migrations.AlterField(
            model_name="devcheckv2",
            name="sponsor",
            field=models.ManyToManyField(
                blank=True,
                db_column="sponsor_id",
                db_constraint=False,
                related_name="checks",
                to="ontology.mvvolunteer",
            ),
        ),
        migrations.AlterField(
            model_name="mvinteraction",
            name="linked_accommodation_request",
            field=models.ForeignKey(
                db_column="linked_accommodation_request",
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="ontology.mvaccommodationrequest",
            ),
        ),
        migrations.AlterField(
            model_name="mvinteraction",
            name="linked_old_interaction",
            field=models.ForeignKey(
                db_column="linked_old_interaction_id",
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="ontology.mvinteraction",
            ),
        ),
        migrations.AlterField(
            model_name="mvinteraction",
            name="linked_safeguarding_notification",
            field=models.ForeignKey(
                db_column="linked_safeguarding_notification",
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="ontology.safeguardingnotification",
            ),
        ),
    ]
