# Generated by Django 5.2.2 on 2025-08-01 14:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ontology", "0057_visainformationrequest_visa_application"),
    ]

    operations = [
        migrations.AddField(
            model_name="visainformationrequest",
            name="closed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
