# Generated by Django 5.2.2 on 2025-07-31 09:41

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ontology", "0058_safeguardingnotification_deferral_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sponsorshipcertificationform",
            name="certificate_reference",
            field=models.TextField(
                db_column="certificate_reference",
                null=True,
                verbose_name="Child sponsorship approval number",
            ),
        ),
        migrations.AlterField(
            model_name="sponsorshipcertificationform",
            name="cohabitant_nationality",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                db_column="cohabitant_nationality",
                null=True,
                size=None,
                verbose_name="Nationality",
            ),
        ),
        migrations.AlterField(
            model_name="sponsorshipcertificationform",
            name="created_at",
            field=models.DateTimeField(
                db_column="created_at", null=True, verbose_name="Date created"
            ),
        ),
        migrations.AlterField(
            model_name="sponsorshipcertificationform",
            name="email",
            field=models.TextField(
                db_column="email", null=True, verbose_name="Email address"
            ),
        ),
        migrations.AlterField(
            model_name="sponsorshipcertificationform",
            name="family_name",
            field=models.TextField(
                db_column="family_name", null=True, verbose_name="Last name"
            ),
        ),
        migrations.AlterField(
            model_name="sponsorshipcertificationform",
            name="given_name",
            field=models.TextField(
                db_column="given_name", null=True, verbose_name="First name"
            ),
        ),
        migrations.AlterField(
            model_name="sponsorshipcertificationform",
            name="identification_number",
            field=models.TextField(
                db_column="identification_number",
                null=True,
                verbose_name="Identification number",
            ),
        ),
        migrations.AlterField(
            model_name="sponsorshipcertificationform",
            name="identification_type",
            field=models.TextField(
                db_column="identification_type",
                null=True,
                verbose_name="Identification type",
            ),
        ),
        migrations.AlterField(
            model_name="sponsorshipcertificationform",
            name="ltla_name",
            field=models.TextField(
                blank=True,
                db_column="ltla_name",
                null=True,
                verbose_name="Local authority",
            ),
        ),
        migrations.AlterField(
            model_name="sponsorshipcertificationform",
            name="phone_number",
            field=models.TextField(
                db_column="phone_number", null=True, verbose_name="Phone number"
            ),
        ),
        migrations.AlterField(
            model_name="sponsorshipcertificationform",
            name="reference",
            field=models.TextField(
                db_column="reference",
                primary_key=True,
                serialize=False,
                verbose_name="Application Number",
            ),
        ),
        migrations.AlterField(
            model_name="sponsorshipcertificationform",
            name="residential_postcode",
            field=models.TextField(
                db_column="residential_postcode", null=True, verbose_name="Postcode"
            ),
        ),
        migrations.AlterField(
            model_name="sponsorshipcertificationform",
            name="sponsor_date_of_birth",
            field=models.DateField(
                db_column="sponsor_date_of_birth",
                null=True,
                verbose_name="Date of birth",
            ),
        ),
    ]
