# Generated by Django 5.2.2 on 2025-08-01 09:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "ontology",
            "0059_alter_sponsorshipcertificationform_certificate_reference_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="sponsorshipcertificationform",
            name="identification_type",
            field=models.TextField(
                choices=[
                    ("passport", "Passport"),
                    ("national_identity_card", "National Identity Card"),
                    ("biometric_residence", "Biometric Residence Permit or Card"),
                    ("photo_driving_licence", "Photo driving licence"),
                    ("refugee_travel_document", "Refugee Travel Document"),
                    ("none", "None provided"),
                ],
                db_column="identification_type",
                null=True,
                verbose_name="Identification type",
            ),
        ),
    ]
