# Generated by Django 5.2.2 on 2025-08-05 12:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ontology", "0058_visainformationrequest_closed_at"),
        ("ontology", "0060_alter_sponsorshipcertificationform_identification_type"),
    ]

    operations = []
