# Generated by Django 5.2.2 on 2025-08-05 13:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ontology", "0061_merge_20250805_1304"),
    ]

    operations = [
        migrations.AlterField(
            model_name="devcheckv2",
            name="check_status",
            field=models.TextField(
                blank=True,
                choices=[
                    ("NOT_STARTED", "Not started"),
                    ("IN_PROGRESS", "In progress"),
                    ("PASSED", "Passed"),
                    ("FAILED", "Failed"),
                    ("NO_LONGER_NEEDED", "No longer needed"),
                    ("UNAVAILABLE", "Not available"),
                ],
                db_column="check_status",
                null=True,
            ),
        ),
    ]
