# Generated by Django 5.2.2 on 2025-08-06 11:16

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ontology", "0062_alter_devcheckv2_check_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="reassignmentrequest",
            name="actioned_at",
            field=models.DateTimeField(db_column="actioned_at", null=True),
        ),
        migrations.AlterField(
            model_name="mvinteraction",
            name="linked_match",
            field=models.ForeignKey(
                db_column="linked_match_id",
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="ontology.eoihost",
            ),
        ),
        migrations.AlterField(
            model_name="reassignmentrequest",
            name="destination_ltla_code",
            field=models.ForeignKey(
                db_column="destination_ltla_code",
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="ontology.uklocalauthority",
            ),
        ),
        migrations.RemoveField(
            model_name="reassignmentrequest",
            name="source_ltla_code",
        ),
        migrations.AlterField(
            model_name="safeguardingreferral",
            name="person",
            field=models.ForeignKey(
                db_column="person_id",
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="ontology.mvperson",
            ),
        ),
        migrations.AddField(
            model_name="reassignmentrequest",
            name="source_ltla_code",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                db_column="source_ltla_code",
                null=True,
                size=None,
            ),
        ),
    ]
