# Generated by Django 5.2.2 on 2025-08-06 14:12

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ontology", "0063_reassignmentrequest_actioned_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visainformationrequest",
            name="requested_check_type_id",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(
                    choices=[
                        ("ACCOMM_SUITABLE", "Accommodation suitable"),
                        ("SPONSOR_DBS", "DBS check and Sponsor suitable"),
                    ]
                ),
                db_column="requested_check_type_id",
                null=True,
                size=None,
            ),
        ),
    ]
