# Generated by Django 5.2.2 on 2025-08-07 10:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ontology", "0064_alter_visainformationrequest_requested_check_type_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mvaccommodation",
            name="sponsorship_certification_number",
        ),
        migrations.RemoveField(
            model_name="mvaccommodationrequest",
            name="sponsorship_certification_number",
        ),
        migrations.RemoveField(
            model_name="mvperson",
            name="sponsorship_certification_number",
        ),
        migrations.RemoveField(
            model_name="mvvolunteer",
            name="sponsorship_certification_number",
        ),
    ]
