# Generated by Django 5.2.2 on 2025-08-07 11:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "ontology",
            "0065_remove_mvaccommodation_sponsorship_certification_number_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="visainformationrequestcomments",
            name="display_name",
            field=models.TextField(db_column="display_name", null=True),
        ),
        migrations.AlterField(
            model_name="visainformationrequest",
            name="request_status",
            field=models.TextField(
                choices=[
                    ("AWAITING_UKVI", "Awaiting UKVI"),
                    ("AWAITING_LA", "Awaiting LA"),
                    ("CLOSED", "Closed"),
                ],
                db_column="request_status",
                null=True,
            ),
        ),
    ]
