# Generated by Django 5.2.2 on 2025-08-07 13:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ontology", "0066_visainformationrequestcomments_display_name_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="announcement",
            name="attachment",
        ),
        migrations.RemoveField(
            model_name="announcement",
            name="category",
        ),
        migrations.RemoveField(
            model_name="announcement",
            name="created_date",
        ),
        migrations.RemoveField(
            model_name="announcement",
            name="created_timestamp",
        ),
        migrations.RemoveField(
            model_name="announcement",
            name="documentation",
        ),
        migrations.RemoveField(
            model_name="announcement",
            name="excluded_viewer_group_names",
        ),
        migrations.RemoveField(
            model_name="announcement",
            name="foundry_application",
        ),
        migrations.RemoveField(
            model_name="announcement",
            name="notes_markdown",
        ),
        migrations.RemoveField(
            model_name="announcement",
            name="priority",
        ),
        migrations.RemoveField(
            model_name="announcement",
            name="thumbnail",
        ),
        migrations.RemoveField(
            model_name="announcement",
            name="viewer_group_names",
        ),
        migrations.AddField(
            model_name="announcement",
            name="body",
            field=models.TextField(
                default="",
                help_text="Enter the announcement body (max 500 characters)",
                max_length=500,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="announcement",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="announcement",
            name="link",
            field=models.URLField(
                blank=True, help_text="Optional: Add a URL link", null=True
            ),
        ),
        migrations.AddField(
            model_name="announcement",
            name="link_text",
            field=models.CharField(
                blank=True,
                help_text="Optional: Displayed link text to the user (max 47 characters)",
                max_length=47,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="announcement",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="announcement",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="announcement",
            name="title",
            field=models.CharField(
                default="", help_text="Enter a title (max 34 characters)", max_length=34
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="announcement",
            name="type",
            field=models.CharField(
                blank=True,
                help_text="Optional: Type or category of announcement (max 25 characters)",
                max_length=25,
                null=True,
            ),
        ),
    ]
