# Generated by Django 5.2.2 on 2025-08-07 16:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ontology", "0067_remove_announcement_attachment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="announcement",
            name="publish_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="Date and time of the announcement",
            ),
        ),
    ]
