# Generated by Django 5.2.2 on 2025-08-08 11:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ontology", "0068_announcement_publish_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visainformationrequest",
            name="request_status",
            field=models.TextField(
                choices=[
                    ("Awaiting UKVI", "Awaiting UKVI"),
                    ("Awaiting LA", "Awaiting LA"),
                    ("Closed", "Closed"),
                ],
                db_column="request_status",
                null=True,
            ),
        ),
    ]
