# Generated by Django 5.2.2 on 2025-08-11 01:15

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ontology", "0069_alter_visainformationrequest_request_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sponsorshipcertificationform",
            name="ltla_name",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                db_column="ltla_name",
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="sponsorshipcertificationform",
            name="utla_name",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                db_column="utla_name",
                null=True,
                size=None,
            ),
        ),
    ]
