# Generated by Django 5.2.2 on 2025-08-11 08:21

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ontology", "0070_alter_sponsorshipcertificationform_ltla_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sponsorshipcertificationform",
            name="ltla_name",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                db_column="ltla_name",
                null=True,
                size=None,
                verbose_name="Local authority",
            ),
        ),
        migrations.AlterField(
            model_name="sponsorshipcertificationform",
            name="utla_name",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                db_column="utla_name",
                null=True,
                size=None,
                verbose_name="Upper tier LA",
            ),
        ),
    ]
