# Generated by Django 5.2.2 on 2025-08-12 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ontology", "0071_alter_sponsorshipcertificationform_ltla_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reassignmentrequest",
            name="accommodation_request",
            field=models.ForeignKey(
                db_column="accommodation_request_id",
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reassignment_requests",
                to="ontology.mvaccommodationrequest",
            ),
        ),
    ]
