# Generated by Django 5.2.2 on 2025-08-20 08:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ontology", "0072_alter_reassignmentrequest_accommodation_request"),
    ]

    operations = [
        migrations.AlterField(
            model_name="devcheckv2",
            name="check_status",
            field=models.TextField(
                blank=True,
                choices=[
                    ("Not Started", "Not started"),
                    ("In Progress", "In progress"),
                    ("Passed", "Passed"),
                    ("Failed", "Failed"),
                    ("No Longer Required", "No longer needed"),
                    ("Not Available", "Not available"),
                ],
                db_column="check_status",
                null=True,
            ),
        ),
    ]
