# Generated by Django 5.2.2 on 2025-08-22 10:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ontology", "0073_alter_devcheckv2_check_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exporttoolobject",
            name="accommodation_accommodation_provider_type",
            field=models.TextField(
                blank=True,
                db_column="accommodation_accommodation_provider_type",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="exporttoolobject",
            name="accommodation_full_address",
            field=models.TextField(
                blank=True, db_column="accommodation_full_address", null=True
            ),
        ),
        migrations.AlterField(
            model_name="exporttoolobject",
            name="accommodation_id",
            field=models.TextField(blank=True, db_column="accommodation_id", null=True),
        ),
        migrations.AlterField(
            model_name="exporttoolobject",
            name="accommodation_local_authority",
            field=models.TextField(
                blank=True, db_column="accommodation_local_authority", null=True
            ),
        ),
        migrations.AlterField(
            model_name="exporttoolobject",
            name="accommodation_postcode",
            field=models.TextField(
                blank=True, db_column="accommodation_postcode", null=True
            ),
        ),
        migrations.AlterField(
            model_name="exporttoolobject",
            name="accommodation_submission_guid",
            field=models.TextField(
                blank=True, db_column="accommodation_submission_guid", null=True
            ),
        ),
        migrations.AlterField(
            model_name="exporttoolobject",
            name="accommodation_volunteer_id",
            field=models.TextField(
                blank=True, db_column="accommodation_volunteer_id", null=True
            ),
        ),
        migrations.AlterField(
            model_name="exporttoolobject",
            name="case_left_programme_reason",
            field=models.TextField(
                blank=True, db_column="case_left_programme_reason", null=True
            ),
        ),
        migrations.AlterField(
            model_name="exporttoolobject",
            name="central_case_flag",
            field=models.BooleanField(
                blank=True, db_column="central_case_flag", null=True
            ),
        ),
        migrations.AlterField(
            model_name="exporttoolobject",
            name="checks_status",
            field=models.TextField(blank=True, db_column="checks_status", null=True),
        ),
        migrations.AlterField(
            model_name="exporttoolobject",
            name="comment",
            field=models.TextField(blank=True, db_column="comment", null=True),
        ),
        migrations.AlterField(
            model_name="exporttoolobject",
            name="created_at",
            field=models.DateTimeField(blank=True, db_column="created_at", null=True),
        ),
        migrations.AlterField(
            model_name="exporttoolobject",
            name="date_from",
            field=models.DateField(blank=True, db_column="date_from", null=True),
        ),
        migrations.AlterField(
            model_name="exporttoolobject",
            name="expected_end_date",
            field=models.DateField(
                blank=True, db_column="expected_end_date", null=True
            ),
        ),
        migrations.AlterField(
            model_name="exporttoolobject",
            name="expected_end_date_is_autogenerated",
            field=models.BooleanField(
                blank=True, db_column="expected_end_date_is_autogenerated", null=True
            ),
        ),
        migrations.AlterField(
            model_name="exporttoolobject",
            name="group_date_of_arrival",
            field=models.DateField(
                blank=True, db_column="group_date_of_arrival", null=True
            ),
        ),
        migrations.AlterField(
            model_name="exporttoolobject",
            name="group_id",
            field=models.TextField(blank=True, db_column="group_id", null=True),
        ),
        migrations.AlterField(
            model_name="exporttoolobject",
            name="group_max_age",
            field=models.IntegerField(blank=True, db_column="group_max_age", null=True),
        ),
        migrations.AlterField(
            model_name="exporttoolobject",
            name="group_merged_group",
            field=models.TextField(
                blank=True, db_column="group_merged_group", null=True
            ),
        ),
        migrations.AlterField(
            model_name="exporttoolobject",
            name="group_min_age",
            field=models.IntegerField(blank=True, db_column="group_min_age", null=True),
        ),
        migrations.AlterField(
            model_name="exporttoolobject",
            name="group_number_of_people_in_group",
            field=models.BigIntegerField(
                blank=True, db_column="group_number_of_people_in_group", null=True
            ),
        ),
        migrations.AlterField(
            model_name="exporttoolobject",
            name="group_primary_contact_can_be_contacted_by_phone",
            field=models.TextField(
                blank=True,
                db_column="group_primary_contact_can_be_contacted_by_phone",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="exporttoolobject",
            name="group_primary_contact_email",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                blank=True,
                db_column="group_primary_contact_email",
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="exporttoolobject",
            name="group_primary_contact_email_after_decision",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                blank=True,
                db_column="group_primary_contact_email_after_decision",
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="exporttoolobject",
            name="group_primary_contact_email_for_decision",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                blank=True,
                db_column="group_primary_contact_email_for_decision",
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="exporttoolobject",
            name="group_primary_contact_email_for_questions",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                blank=True,
                db_column="group_primary_contact_email_for_questions",
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="exporttoolobject",
            name="group_primary_contact_first_name",
            field=models.TextField(
                blank=True, db_column="group_primary_contact_first_name", null=True
            ),
        ),
        migrations.AlterField(
            model_name="exporttoolobject",
            name="group_primary_contact_last_name",
            field=models.TextField(
                blank=True, db_column="group_primary_contact_last_name", null=True
            ),
        ),
        migrations.AlterField(
            model_name="exporttoolobject",
            name="group_primary_contact_phone",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                blank=True,
                db_column="group_primary_contact_phone",
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="exporttoolobject",
            name="group_title",
            field=models.TextField(blank=True, db_column="group_title", null=True),
        ),
        migrations.AlterField(
            model_name="exporttoolobject",
            name="hash",
            field=models.TextField(blank=True, db_column="hash", null=True),
        ),
        migrations.AlterField(
            model_name="exporttoolobject",
            name="id",
            field=models.TextField(blank=True, db_column="id", null=True),
        ),
        migrations.AlterField(
            model_name="exporttoolobject",
            name="is_multi_la",
            field=models.BooleanField(blank=True, db_column="is_multi_la", null=True),
        ),
        migrations.AlterField(
            model_name="exporttoolobject",
            name="last_updated",
            field=models.DateTimeField(blank=True, db_column="last_updated", null=True),
        ),
        migrations.AlterField(
            model_name="exporttoolobject",
            name="latest_application_date",
            field=models.DateField(
                blank=True, db_column="latest_application_date", null=True
            ),
        ),
        migrations.AlterField(
            model_name="exporttoolobject",
            name="ltla_name",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                blank=True,
                db_column="ltla_name",
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="exporttoolobject",
            name="number_of_people",
            field=models.BigIntegerField(
                blank=True, db_column="number_of_people", null=True
            ),
        ),
        migrations.AlterField(
            model_name="exporttoolobject",
            name="person_age",
            field=models.BigIntegerField(blank=True, db_column="person_age", null=True),
        ),
        migrations.AlterField(
            model_name="exporttoolobject",
            name="person_application_number",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                blank=True,
                db_column="person_application_number",
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="exporttoolobject",
            name="person_arrival_date",
            field=models.DateField(
                blank=True, db_column="person_arrival_date", null=True
            ),
        ),
        migrations.AlterField(
            model_name="exporttoolobject",
            name="person_can_be_contacted_by_phone",
            field=models.TextField(
                blank=True, db_column="person_can_be_contacted_by_phone", null=True
            ),
        ),
        migrations.AlterField(
            model_name="exporttoolobject",
            name="person_date_of_birth",
            field=models.DateField(
                blank=True, db_column="person_date_of_birth", null=True
            ),
        ),
        migrations.AlterField(
            model_name="exporttoolobject",
            name="person_earliest_issued_visa_decision_date",
            field=models.DateField(
                blank=True,
                db_column="person_earliest_issued_visa_decision_date",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="exporttoolobject",
            name="person_email",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                blank=True,
                db_column="person_email",
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="exporttoolobject",
            name="person_email_after_decision",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                blank=True,
                db_column="person_email_after_decision",
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="exporttoolobject",
            name="person_email_for_decision",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                blank=True,
                db_column="person_email_for_decision",
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="exporttoolobject",
            name="person_email_for_questions",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                blank=True,
                db_column="person_email_for_questions",
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="exporttoolobject",
            name="person_full_name",
            field=models.TextField(blank=True, db_column="person_full_name", null=True),
        ),
        migrations.AlterField(
            model_name="exporttoolobject",
            name="person_gender",
            field=models.TextField(blank=True, db_column="person_gender", null=True),
        ),
        migrations.AlterField(
            model_name="exporttoolobject",
            name="person_group_id",
            field=models.TextField(blank=True, db_column="person_group_id", null=True),
        ),
        migrations.AlterField(
            model_name="exporttoolobject",
            name="person_id",
            field=models.TextField(blank=True, db_column="person_id", null=True),
        ),
        migrations.AlterField(
            model_name="exporttoolobject",
            name="person_is_uam",
            field=models.BooleanField(blank=True, db_column="person_is_uam", null=True),
        ),
        migrations.AlterField(
            model_name="exporttoolobject",
            name="person_latest_arrival_date",
            field=models.DateField(
                blank=True, db_column="person_latest_arrival_date", null=True
            ),
        ),
        migrations.AlterField(
            model_name="exporttoolobject",
            name="person_old_group_id",
            field=models.TextField(
                blank=True, db_column="person_old_group_id", null=True
            ),
        ),
        migrations.AlterField(
            model_name="exporttoolobject",
            name="person_passport_id",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                blank=True,
                db_column="person_passport_id",
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="exporttoolobject",
            name="person_phone",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                blank=True,
                db_column="person_phone",
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="exporttoolobject",
            name="person_upe_visa_status",
            field=models.TextField(
                blank=True, db_column="person_upe_visa_status", null=True
            ),
        ),
        migrations.AlterField(
            model_name="exporttoolobject",
            name="person_visa_status",
            field=models.TextField(
                blank=True, db_column="person_visa_status", null=True
            ),
        ),
        migrations.AlterField(
            model_name="exporttoolobject",
            name="rematched_accommodation_request_id",
            field=models.TextField(
                blank=True, db_column="rematched_accommodation_request_id", null=True
            ),
        ),
        migrations.AlterField(
            model_name="exporttoolobject",
            name="rematched_host_contact_number",
            field=models.TextField(
                blank=True, db_column="rematched_host_contact_number", null=True
            ),
        ),
        migrations.AlterField(
            model_name="exporttoolobject",
            name="rematched_host_email",
            field=models.TextField(
                blank=True, db_column="rematched_host_email", null=True
            ),
        ),
        migrations.AlterField(
            model_name="exporttoolobject",
            name="rematched_host_full_name",
            field=models.TextField(
                blank=True, db_column="rematched_host_full_name", null=True
            ),
        ),
        migrations.AlterField(
            model_name="exporttoolobject",
            name="rematched_host_id",
            field=models.TextField(
                blank=True, db_column="rematched_host_id", null=True
            ),
        ),
        migrations.AlterField(
            model_name="exporttoolobject",
            name="sponsor_adverse_hit",
            field=models.BooleanField(
                blank=True, db_column="sponsor_adverse_hit", null=True
            ),
        ),
        migrations.AlterField(
            model_name="exporttoolobject",
            name="sponsor_age",
            field=models.IntegerField(blank=True, db_column="sponsor_age", null=True),
        ),
        migrations.AlterField(
            model_name="exporttoolobject",
            name="sponsor_date_of_birth",
            field=models.DateField(
                blank=True, db_column="sponsor_date_of_birth", null=True
            ),
        ),
        migrations.AlterField(
            model_name="exporttoolobject",
            name="sponsor_email",
            field=models.TextField(blank=True, db_column="sponsor_email", null=True),
        ),
        migrations.AlterField(
            model_name="exporttoolobject",
            name="sponsor_expiry_date_id",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                blank=True,
                db_column="sponsor_expiry_date_id",
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="exporttoolobject",
            name="sponsor_family_situation",
            field=models.TextField(
                blank=True, db_column="sponsor_family_situation", null=True
            ),
        ),
        migrations.AlterField(
            model_name="exporttoolobject",
            name="sponsor_full_name",
            field=models.TextField(
                blank=True, db_column="sponsor_full_name", null=True
            ),
        ),
        migrations.AlterField(
            model_name="exporttoolobject",
            name="sponsor_has_identity_card",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                blank=True,
                db_column="sponsor_has_identity_card",
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="exporttoolobject",
            name="sponsor_id",
            field=models.TextField(blank=True, db_column="sponsor_id", null=True),
        ),
        migrations.AlterField(
            model_name="exporttoolobject",
            name="sponsor_issue_date_id",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                blank=True,
                db_column="sponsor_issue_date_id",
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="exporttoolobject",
            name="sponsor_issuing_authority_of_id",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                blank=True,
                db_column="sponsor_issuing_authority_of_id",
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="exporttoolobject",
            name="sponsor_national_identity_card_number",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                blank=True,
                db_column="sponsor_national_identity_card_number",
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="exporttoolobject",
            name="sponsor_phone_number",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                blank=True,
                db_column="sponsor_phone_number",
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="exporttoolobject",
            name="sponsor_sex",
            field=models.TextField(blank=True, db_column="sponsor_sex", null=True),
        ),
        migrations.AlterField(
            model_name="exporttoolobject",
            name="sponsor_withdrawn",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                blank=True,
                db_column="sponsor_withdrawn",
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="exporttoolobject",
            name="status",
            field=models.TextField(blank=True, db_column="status", null=True),
        ),
        migrations.AlterField(
            model_name="exporttoolobject",
            name="title",
            field=models.TextField(blank=True, db_column="title", null=True),
        ),
        migrations.AlterField(
            model_name="exporttoolobject",
            name="unique_application_number",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                blank=True,
                db_column="unique_application_number",
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="exporttoolobject",
            name="utla_name",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                blank=True,
                db_column="utla_name",
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="exporttoolobject",
            name="viewer_group_names",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                blank=True,
                db_column="viewer_group_names",
                null=True,
                size=None,
            ),
        ),
    ]
