# Generated by Django 5.2.2 on 2025-08-22 11:02

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ontology", "0075_alter_mvinteraction_attachment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mvperson",
            name="accommodation_request",
            field=models.ForeignKey(
                blank=True,
                db_column="accommodation_request_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="ontology.mvaccommodationrequest",
                verbose_name="Accommodation request ID",
            ),
        ),
        migrations.AlterField(
            model_name="mvperson",
            name="adverse_rematch",
            field=models.BooleanField(
                blank=True, db_column="adverse_rematch", null=True
            ),
        ),
        migrations.AlterField(
            model_name="mvperson",
            name="age",
            field=models.BigIntegerField(blank=True, db_column="age", null=True),
        ),
        migrations.AlterField(
            model_name="mvperson",
            name="application_number",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                blank=True,
                db_column="application_number",
                null=True,
                size=None,
                verbose_name="Unique application number (UAN)",
            ),
        ),
        migrations.AlterField(
            model_name="mvperson",
            name="arrival_date",
            field=models.DateField(
                blank=True,
                db_column="arrival_date",
                null=True,
                verbose_name="First arrival date",
            ),
        ),
        migrations.AlterField(
            model_name="mvperson",
            name="arrival_port_code",
            field=models.TextField(
                blank=True,
                db_column="arrival_port_code",
                null=True,
                verbose_name="First arrival port code",
            ),
        ),
        migrations.AlterField(
            model_name="mvperson",
            name="arrival_port_name",
            field=models.TextField(
                blank=True,
                db_column="arrival_port_name",
                null=True,
                verbose_name="First arrival port name",
            ),
        ),
        migrations.AlterField(
            model_name="mvperson",
            name="can_be_contacted_by_phone",
            field=models.TextField(
                blank=True, db_column="can_be_contacted_by_phone", null=True
            ),
        ),
        migrations.AlterField(
            model_name="mvperson",
            name="created_at",
            field=models.DateTimeField(blank=True, db_column="created_at", null=True),
        ),
        migrations.AlterField(
            model_name="mvperson",
            name="created_by",
            field=models.TextField(blank=True, db_column="created_by", null=True),
        ),
        migrations.AlterField(
            model_name="mvperson",
            name="date_of_birth",
            field=models.DateField(blank=True, db_column="date_of_birth", null=True),
        ),
        migrations.AlterField(
            model_name="mvperson",
            name="date_of_first_issue_visa_decision",
            field=models.DateField(
                blank=True,
                db_column="date_of_first_issue_visa_decision",
                null=True,
                verbose_name="Earliest issued visa decision date",
            ),
        ),
        migrations.AlterField(
            model_name="mvperson",
            name="disability_flag",
            field=models.BooleanField(
                blank=True, db_column="disability_flag", null=True
            ),
        ),
        migrations.AlterField(
            model_name="mvperson",
            name="email",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                blank=True,
                db_column="email",
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="mvperson",
            name="email_after_decision",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                blank=True,
                db_column="email_after_decision",
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="mvperson",
            name="email_for_decision",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                blank=True,
                db_column="email_for_decision",
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="mvperson",
            name="email_for_questions",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                blank=True,
                db_column="email_for_questions",
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="mvperson",
            name="first_name",
            field=models.TextField(blank=True, db_column="first_name", null=True),
        ),
        migrations.AlterField(
            model_name="mvperson",
            name="gender",
            field=models.TextField(
                blank=True, db_column="gender", null=True, verbose_name="Sex"
            ),
        ),
        migrations.AlterField(
            model_name="mvperson",
            name="group",
            field=models.ForeignKey(
                blank=True,
                db_column="group_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="ontology.mvgroup",
                verbose_name="Group ID",
            ),
        ),
        migrations.AlterField(
            model_name="mvperson",
            name="gwf",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                blank=True,
                db_column="gwf",
                null=True,
                size=None,
                verbose_name="Global web form number (GWF)",
            ),
        ),
        migrations.AlterField(
            model_name="mvperson",
            name="is_principal",
            field=models.BooleanField(blank=True, db_column="is_principal", null=True),
        ),
        migrations.AlterField(
            model_name="mvperson",
            name="is_uam",
            field=models.BooleanField(
                blank=True, db_column="is_uam", null=True, verbose_name="Eligible minor"
            ),
        ),
        migrations.AlterField(
            model_name="mvperson",
            name="is_uam_edited_time",
            field=models.DateTimeField(
                blank=True, db_column="is_uam_edited_time", null=True
            ),
        ),
        migrations.AlterField(
            model_name="mvperson",
            name="last_edited_at",
            field=models.DateTimeField(
                blank=True, db_column="last_edited_at", null=True
            ),
        ),
        migrations.AlterField(
            model_name="mvperson",
            name="last_edited_by",
            field=models.TextField(blank=True, db_column="last_edited_by", null=True),
        ),
        migrations.AlterField(
            model_name="mvperson",
            name="last_name",
            field=models.TextField(blank=True, db_column="last_name", null=True),
        ),
        migrations.AlterField(
            model_name="mvperson",
            name="latest_arrival_date",
            field=models.DateField(
                blank=True, db_column="latest_arrival_date", null=True
            ),
        ),
        migrations.AlterField(
            model_name="mvperson",
            name="nationality",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                blank=True,
                db_column="nationality",
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="mvperson",
            name="notional_data",
            field=models.BooleanField(blank=True, db_column="notional_data", null=True),
        ),
        migrations.AlterField(
            model_name="mvperson",
            name="old_group",
            field=models.ForeignKey(
                blank=True,
                db_column="old_group_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="ontology.mvgroup",
                verbose_name="Old group ID",
            ),
        ),
        migrations.AlterField(
            model_name="mvperson",
            name="passport_id",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                blank=True,
                db_column="passport_id",
                null=True,
                size=None,
                verbose_name="Passport number",
            ),
        ),
        migrations.AlterField(
            model_name="mvperson",
            name="phone",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                blank=True,
                db_column="phone",
                null=True,
                size=None,
                verbose_name="Phone number",
            ),
        ),
        migrations.AlterField(
            model_name="mvperson",
            name="previous_group_ids",
            field=models.ManyToManyField(
                blank=True,
                db_column="previous_group_ids",
                related_name="+",
                to="ontology.mvgroup",
                verbose_name="Previous group IDs",
            ),
        ),
        migrations.AlterField(
            model_name="mvperson",
            name="previous_group_leaving_times",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.DateTimeField(),
                blank=True,
                db_column="previous_group_leaving_times",
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="mvperson",
            name="primary_application_numbers",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                blank=True,
                db_column="primary_application_numbers",
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="mvperson",
            name="source",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                blank=True,
                db_column="source",
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="mvperson",
            name="title",
            field=models.TextField(blank=True, db_column="title", null=True),
        ),
        migrations.AlterField(
            model_name="mvperson",
            name="travelling_to_uk",
            field=models.BooleanField(
                blank=True,
                db_column="travelling_to_uk",
                null=True,
                verbose_name="Travelling to UK",
            ),
        ),
        migrations.AlterField(
            model_name="mvperson",
            name="upe_visa_status",
            field=models.TextField(
                blank=True,
                choices=[
                    ("NO_OUTCOME", "No UPE visa application outcome"),
                    ("UPE_VISA_ACCEPTED", "UPE visa accepted"),
                    ("UPE_VISA_REFUSED", "UPE visa refused"),
                    ("UPE_VISA_REJECTED", "UPE visa rejected"),
                    ("UPE_VISA_WITHDRAWN", "UPE visa withdrawn"),
                ],
                db_column="upe_visa_status",
                null=True,
                verbose_name="UPE visa status",
            ),
        ),
        migrations.AlterField(
            model_name="mvperson",
            name="viewer_group_names",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                blank=True,
                db_column="viewer_group_names",
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="mvperson",
            name="visa_application_date",
            field=models.DateField(
                blank=True, db_column="visa_application_date", null=True
            ),
        ),
        migrations.AlterField(
            model_name="mvperson",
            name="visa_application_date_maximum",
            field=models.DateField(
                blank=True,
                db_column="visa_application_date_maximum",
                null=True,
                verbose_name="Latest visa application date",
            ),
        ),
        migrations.AlterField(
            model_name="mvperson",
            name="visa_application_dates",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.DateField(),
                blank=True,
                db_column="visa_application_dates",
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="mvperson",
            name="visa_decision_date",
            field=models.DateField(
                blank=True, db_column="visa_decision_date", null=True
            ),
        ),
        migrations.AlterField(
            model_name="mvperson",
            name="visa_status",
            field=models.TextField(
                blank=True,
                db_column="visa_status",
                null=True,
                verbose_name="Latest visa status",
            ),
        ),
        migrations.AlterField(
            model_name="mvperson",
            name="wheelchair_required",
            field=models.BooleanField(
                blank=True, db_column="wheelchair_required", null=True
            ),
        ),
    ]
