# Generated by Django 5.2.2 on 2025-08-22 11:04

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ontology", "0076_alter_mvperson_accommodation_request_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mvvolunteer",
            name="Individual_or_Organisation",
            field=models.TextField(
                blank=True, db_column="Individual_or_Organisation", null=True
            ),
        ),
        migrations.AlterField(
            model_name="mvvolunteer",
            name="adverse_hit",
            field=models.BooleanField(blank=True, db_column="adverse_hit", null=True),
        ),
        migrations.AlterField(
            model_name="mvvolunteer",
            name="age",
            field=models.IntegerField(blank=True, db_column="age", null=True),
        ),
        migrations.AlterField(
            model_name="mvvolunteer",
            name="application_unique_application_number",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                blank=True,
                db_column="application_unique_application_number",
                null=True,
                size=None,
                verbose_name="Unique application number (UAN)",
            ),
        ),
        migrations.AlterField(
            model_name="mvvolunteer",
            name="comments",
            field=models.TextField(blank=True, db_column="comments", null=True),
        ),
        migrations.AlterField(
            model_name="mvvolunteer",
            name="created_date",
            field=models.DateTimeField(blank=True, db_column="created_date", null=True),
        ),
        migrations.AlterField(
            model_name="mvvolunteer",
            name="date_of_birth",
            field=models.DateField(blank=True, db_column="date_of_birth", null=True),
        ),
        migrations.AlterField(
            model_name="mvvolunteer",
            name="email",
            field=models.TextField(blank=True, db_column="email", null=True),
        ),
        migrations.AlterField(
            model_name="mvvolunteer",
            name="expiry_date_id",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                blank=True,
                db_column="expiry_date_id",
                null=True,
                size=None,
                verbose_name="Expiry date ID",
            ),
        ),
        migrations.AlterField(
            model_name="mvvolunteer",
            name="family_situation",
            field=models.TextField(blank=True, db_column="family_situation", null=True),
        ),
        migrations.AlterField(
            model_name="mvvolunteer",
            name="first_name",
            field=models.TextField(blank=True, db_column="first_name", null=True),
        ),
        migrations.AlterField(
            model_name="mvvolunteer",
            name="flag_unsuitable",
            field=models.BooleanField(
                blank=True, db_column="flag_unsuitable", null=True
            ),
        ),
        migrations.AlterField(
            model_name="mvvolunteer",
            name="full_name",
            field=models.TextField(blank=True, db_column="full_name", null=True),
        ),
        migrations.AlterField(
            model_name="mvvolunteer",
            name="gwf",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                blank=True,
                db_column="gwf",
                null=True,
                size=None,
                verbose_name="GWF",
            ),
        ),
        migrations.AlterField(
            model_name="mvvolunteer",
            name="has_background_check",
            field=models.BooleanField(
                blank=True, db_column="has_background_check", null=True
            ),
        ),
        migrations.AlterField(
            model_name="mvvolunteer",
            name="has_identity_card",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                blank=True,
                db_column="has_identity_card",
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="mvvolunteer",
            name="hosting_duration",
            field=models.IntegerField(
                blank=True, db_column="hosting_duration", null=True
            ),
        ),
        migrations.AlterField(
            model_name="mvvolunteer",
            name="is_available_for_rematch",
            field=models.BooleanField(
                blank=True, db_column="is_available_for_rematch", null=True
            ),
        ),
        migrations.AlterField(
            model_name="mvvolunteer",
            name="is_eoi",
            field=models.BooleanField(
                blank=True, db_column="is_eoi", null=True, verbose_name="Host"
            ),
        ),
        migrations.AlterField(
            model_name="mvvolunteer",
            name="is_person_of_interest",
            field=models.BooleanField(
                blank=True, db_column="is_person_of_interest", null=True
            ),
        ),
        migrations.AlterField(
            model_name="mvvolunteer",
            name="is_principal",
            field=models.BooleanField(blank=True, db_column="is_principal", null=True),
        ),
        migrations.AlterField(
            model_name="mvvolunteer",
            name="is_sponsor",
            field=models.BooleanField(
                blank=True, db_column="is_sponsor", null=True, verbose_name="Sponsor"
            ),
        ),
        migrations.AlterField(
            model_name="mvvolunteer",
            name="issue_date_id",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                blank=True,
                db_column="issue_date_id",
                null=True,
                size=None,
                verbose_name="Issue date ID",
            ),
        ),
        migrations.AlterField(
            model_name="mvvolunteer",
            name="issuing_authority_of_id",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                blank=True,
                db_column="issuing_authority_of_id",
                null=True,
                size=None,
                verbose_name="Issuing authority of ID",
            ),
        ),
        migrations.AlterField(
            model_name="mvvolunteer",
            name="last_name",
            field=models.TextField(blank=True, db_column="last_name", null=True),
        ),
        migrations.AlterField(
            model_name="mvvolunteer",
            name="last_updated_date",
            field=models.DateTimeField(
                blank=True, db_column="last_updated_date", null=True
            ),
        ),
        migrations.AlterField(
            model_name="mvvolunteer",
            name="national_identity_card_number",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                blank=True,
                db_column="national_identity_card_number",
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="mvvolunteer",
            name="nationality",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                blank=True,
                db_column="nationality",
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="mvvolunteer",
            name="notional_data",
            field=models.BooleanField(blank=True, db_column="notional_data", null=True),
        ),
        migrations.AlterField(
            model_name="mvvolunteer",
            name="organization_name",
            field=models.TextField(
                blank=True, db_column="organization_name", null=True
            ),
        ),
        migrations.AlterField(
            model_name="mvvolunteer",
            name="organization_type",
            field=models.TextField(
                blank=True, db_column="organization_type", null=True
            ),
        ),
        migrations.AlterField(
            model_name="mvvolunteer",
            name="other_nationalities",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                blank=True,
                db_column="other_nationalities",
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="mvvolunteer",
            name="passport_details",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                blank=True,
                db_column="passport_details",
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="mvvolunteer",
            name="phone_number",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                blank=True,
                db_column="phone_number",
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="mvvolunteer",
            name="previous_id",
            field=models.TextField(
                blank=True,
                db_column="previous_id",
                null=True,
                verbose_name="Previous ID",
            ),
        ),
        migrations.AlterField(
            model_name="mvvolunteer",
            name="requested_checks_latest_date",
            field=models.DateTimeField(
                blank=True, db_column="requested_checks_latest_date", null=True
            ),
        ),
        migrations.AlterField(
            model_name="mvvolunteer",
            name="residential_postcodes",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                blank=True,
                db_column="residential_postcodes",
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="mvvolunteer",
            name="response_id",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                blank=True,
                db_column="response_id",
                null=True,
                size=None,
                verbose_name="Response ID",
            ),
        ),
        migrations.AlterField(
            model_name="mvvolunteer",
            name="sex",
            field=models.TextField(blank=True, db_column="sex", null=True),
        ),
        migrations.AlterField(
            model_name="mvvolunteer",
            name="source",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                blank=True,
                db_column="source",
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="mvvolunteer",
            name="sponsor_status",
            field=models.TextField(blank=True, db_column="sponsor_status", null=True),
        ),
        migrations.AlterField(
            model_name="mvvolunteer",
            name="sponsor_type",
            field=models.TextField(
                blank=True,
                choices=[
                    ("Individual", "Individual"),
                    ("Local Authority", "Local Authority"),
                    ("Org", "Org"),
                ],
                db_column="sponsor_type",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="mvvolunteer",
            name="survey_response",
            field=models.TextField(blank=True, db_column="survey_response", null=True),
        ),
        migrations.AlterField(
            model_name="mvvolunteer",
            name="unsubscribed",
            field=models.BooleanField(blank=True, db_column="unsubscribed", null=True),
        ),
        migrations.AlterField(
            model_name="mvvolunteer",
            name="viewer_group_names",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                blank=True,
                db_column="viewer_group_names",
                null=True,
                size=None,
            ),
        ),
    ]
