# Generated by Django 5.2.2 on 2025-08-22 11:08

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ontology", "0077_alter_mvvolunteer_individual_or_organisation_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="reassignmentrequest",
            name="accommodation_request",
            field=models.ForeignKey(
                blank=True,
                db_column="accommodation_request_id",
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reassignment_requests",
                to="ontology.mvaccommodationrequest",
            ),
        ),
        migrations.AlterField(
            model_name="reassignmentrequest",
            name="accommodation_request_title",
            field=models.TextField(
                blank=True, db_column="accommodation_request_title", null=True
            ),
        ),
        migrations.AlterField(
            model_name="reassignmentrequest",
            name="actioned_at",
            field=models.DateTimeField(blank=True, db_column="actioned_at", null=True),
        ),
        migrations.AlterField(
            model_name="reassignmentrequest",
            name="comments",
            field=models.TextField(blank=True, db_column="comments", null=True),
        ),
        migrations.AlterField(
            model_name="reassignmentrequest",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                db_column="created_by",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_reassignment_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="reassignmentrequest",
            name="destination_country",
            field=models.TextField(
                blank=True, db_column="destination_country", null=True
            ),
        ),
        migrations.AlterField(
            model_name="reassignmentrequest",
            name="destination_ltla_code",
            field=models.ForeignKey(
                blank=True,
                db_column="destination_ltla_code",
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="ontology.uklocalauthority",
            ),
        ),
        migrations.AlterField(
            model_name="reassignmentrequest",
            name="destination_ltla_groupid",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                blank=True,
                db_column="destination_ltla_groupid",
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="reassignmentrequest",
            name="destination_ltla_name",
            field=models.TextField(
                blank=True, db_column="destination_ltla_name", null=True
            ),
        ),
        migrations.AlterField(
            model_name="reassignmentrequest",
            name="destination_utla_code",
            field=models.TextField(
                blank=True, db_column="destination_utla_code", null=True
            ),
        ),
        migrations.AlterField(
            model_name="reassignmentrequest",
            name="destination_utla_groupid",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                blank=True,
                db_column="destination_utla_groupid",
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="reassignmentrequest",
            name="destination_utla_name",
            field=models.TextField(
                blank=True, db_column="destination_utla_name", null=True
            ),
        ),
        migrations.AlterField(
            model_name="reassignmentrequest",
            name="move_date",
            field=models.DateField(blank=True, db_column="move_date", null=True),
        ),
        migrations.AlterField(
            model_name="reassignmentrequest",
            name="outcome",
            field=models.TextField(
                blank=True,
                choices=[
                    ("ACCEPTED", "Accepted"),
                    ("REJECTED", "Rejected"),
                    ("PENDING", "Pending"),
                    ("NEEDS_ACCOMMODATION_REQUEST", "Needs Accommodation Request"),
                ],
                db_column="outcome",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="reassignmentrequest",
            name="proposed_by",
            field=models.ForeignKey(
                blank=True,
                db_column="proposed_by",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="proposed_reassignment_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="reassignmentrequest",
            name="proposed_by_country",
            field=models.TextField(
                blank=True, db_column="proposed_by_country", null=True
            ),
        ),
        migrations.AlterField(
            model_name="reassignmentrequest",
            name="proposed_by_ltla_code",
            field=models.TextField(
                blank=True, db_column="proposed_by_ltla_code", null=True
            ),
        ),
        migrations.AlterField(
            model_name="reassignmentrequest",
            name="reason",
            field=models.TextField(blank=True, db_column="reason", null=True),
        ),
        migrations.AlterField(
            model_name="reassignmentrequest",
            name="responded_at",
            field=models.DateTimeField(blank=True, db_column="responded_at", null=True),
        ),
        migrations.AlterField(
            model_name="reassignmentrequest",
            name="responded_by",
            field=models.ForeignKey(
                blank=True,
                db_column="responded_by",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="responded_reassignment_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="reassignmentrequest",
            name="source_country",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                blank=True,
                db_column="source_country",
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="reassignmentrequest",
            name="source_la_group_ids",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                blank=True,
                db_column="source_la_group_ids",
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="reassignmentrequest",
            name="source_ltla_code",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                blank=True,
                db_column="source_ltla_code",
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="reassignmentrequest",
            name="source_ltla_name",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                blank=True,
                db_column="source_ltla_name",
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="reassignmentrequest",
            name="source_utla_code",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                blank=True,
                db_column="source_utla_code",
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="reassignmentrequest",
            name="source_utla_name",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                blank=True,
                db_column="source_utla_name",
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="reassignmentrequest",
            name="type",
            field=models.TextField(blank=True, db_column="type", null=True),
        ),
        migrations.AlterField(
            model_name="reassignmentrequest",
            name="viewer_groups",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                blank=True,
                db_column="viewer_groups",
                null=True,
                size=None,
            ),
        ),
    ]
