# Generated by Django 5.2.2 on 2025-08-22 11:13

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ontology", "0078_alter_reassignmentrequest_accommodation_request_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="safeguardingnotification",
            name="accommodation_ids",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                blank=True,
                db_column="accommodation_ids",
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="safeguardingnotification",
            name="alert_status",
            field=models.TextField(blank=True, db_column="alert_status", null=True),
        ),
        migrations.AlterField(
            model_name="safeguardingnotification",
            name="alert_type",
            field=models.TextField(blank=True, db_column="rule_name", null=True),
        ),
        migrations.AlterField(
            model_name="safeguardingnotification",
            name="applicant_gwfs",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                blank=True,
                db_column="applicant_gwfs",
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="safeguardingnotification",
            name="applicant_names",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                blank=True,
                db_column="applicant_names",
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="safeguardingnotification",
            name="applicant_person_ids",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                blank=True,
                db_column="applicant_person_ids",
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="safeguardingnotification",
            name="applicant_uans",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                blank=True,
                db_column="applicant_uans",
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="safeguardingnotification",
            name="ar",
            field=models.ForeignKey(
                blank=True,
                db_column="ar_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="ontology.mvaccommodationrequest",
            ),
        ),
        migrations.AlterField(
            model_name="safeguardingnotification",
            name="assigned",
            field=models.TextField(blank=True, db_column="assigned", null=True),
        ),
        migrations.AlterField(
            model_name="safeguardingnotification",
            name="created_at",
            field=models.DateTimeField(blank=True, db_column="created_at", null=True),
        ),
        migrations.AlterField(
            model_name="safeguardingnotification",
            name="deferral_status",
            field=models.TextField(blank=True, db_column="deferral_status", null=True),
        ),
        migrations.AlterField(
            model_name="safeguardingnotification",
            name="description",
            field=models.TextField(blank=True, db_column="description", null=True),
        ),
        migrations.AlterField(
            model_name="safeguardingnotification",
            name="dev_check_v2",
            field=models.ForeignKey(
                blank=True,
                db_column="check_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="ontology.devcheckv2",
            ),
        ),
        migrations.AlterField(
            model_name="safeguardingnotification",
            name="dluhc_id",
            field=models.TextField(blank=True, db_column="dluhc_id", null=True),
        ),
        migrations.AlterField(
            model_name="safeguardingnotification",
            name="escalation_status",
            field=models.TextField(
                blank=True, db_column="escalation_status", null=True
            ),
        ),
        migrations.AlterField(
            model_name="safeguardingnotification",
            name="exported_bf",
            field=models.BooleanField(blank=True, db_column="exported_bf", null=True),
        ),
        migrations.AlterField(
            model_name="safeguardingnotification",
            name="exported_ukvi",
            field=models.BooleanField(blank=True, db_column="exported_ukvi", null=True),
        ),
        migrations.AlterField(
            model_name="safeguardingnotification",
            name="full_addresses",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                blank=True,
                db_column="full_addresses",
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="safeguardingnotification",
            name="ltla",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                blank=True,
                db_column="ltla",
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="safeguardingnotification",
            name="ltla_code",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                blank=True,
                db_column="ltla_code",
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="safeguardingnotification",
            name="modified_at",
            field=models.DateTimeField(blank=True, db_column="modified_at", null=True),
        ),
        migrations.AlterField(
            model_name="safeguardingnotification",
            name="modified_by",
            field=models.TextField(blank=True, db_column="modified_by", null=True),
        ),
        migrations.AlterField(
            model_name="safeguardingnotification",
            name="modified_by_org",
            field=models.TextField(blank=True, db_column="modified_by_org", null=True),
        ),
        migrations.AlterField(
            model_name="safeguardingnotification",
            name="name",
            field=models.TextField(blank=True, db_column="title", null=True),
        ),
        migrations.AlterField(
            model_name="safeguardingnotification",
            name="new_alert_status",
            field=models.TextField(blank=True, db_column="new_alert_status", null=True),
        ),
        migrations.AlterField(
            model_name="safeguardingnotification",
            name="notional_data",
            field=models.BooleanField(blank=True, db_column="notional_data", null=True),
        ),
        migrations.AlterField(
            model_name="safeguardingnotification",
            name="rule_description",
            field=models.TextField(blank=True, db_column="rule_description", null=True),
        ),
        migrations.AlterField(
            model_name="safeguardingnotification",
            name="sponsor_ids",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                blank=True,
                db_column="sponsor_ids",
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="safeguardingnotification",
            name="sponsor_names",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                blank=True,
                db_column="sponsor_names",
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="safeguardingnotification",
            name="taurus_rule_id",
            field=models.TextField(blank=True, db_column="taurus_rule_id", null=True),
        ),
        migrations.AlterField(
            model_name="safeguardingnotification",
            name="updated_at",
            field=models.DateTimeField(blank=True, db_column="updated_at", null=True),
        ),
        migrations.AlterField(
            model_name="safeguardingnotification",
            name="utla",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                blank=True,
                db_column="utla",
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="safeguardingnotification",
            name="utla_code",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                blank=True,
                db_column="utla_code",
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="safeguardingnotification",
            name="viewer_groups",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                blank=True,
                db_column="viewer_groups",
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="safeguardingnotification",
            name="visa_statuses",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                blank=True,
                db_column="visa_statuses",
                null=True,
                size=None,
            ),
        ),
    ]
