# Generated by Django 5.2.2 on 2025-08-22 12:37

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ontology", "0079_alter_safeguardingnotification_accommodation_ids_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="safeguardingreferral",
            name="alerted_status",
            field=models.TextField(blank=True, db_column="alerted_status", null=True),
        ),
        migrations.AlterField(
            model_name="safeguardingreferral",
            name="assignee",
            field=models.TextField(blank=True, db_column="assignee", null=True),
        ),
        migrations.AlterField(
            model_name="safeguardingreferral",
            name="comments",
            field=models.TextField(blank=True, db_column="comments", null=True),
        ),
        migrations.AlterField(
            model_name="safeguardingreferral",
            name="cop_reference",
            field=models.TextField(blank=True, db_column="cop_reference", null=True),
        ),
        migrations.AlterField(
            model_name="safeguardingreferral",
            name="created_at",
            field=models.DateTimeField(blank=True, db_column="created_at", null=True),
        ),
        migrations.AlterField(
            model_name="safeguardingreferral",
            name="deferral_status",
            field=models.TextField(blank=True, db_column="deferral_status", null=True),
        ),
        migrations.AlterField(
            model_name="safeguardingreferral",
            name="included_uans",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                blank=True,
                db_column="included_uans",
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="safeguardingreferral",
            name="last_referred_at",
            field=models.DateTimeField(
                blank=True, db_column="last_referred_at", null=True
            ),
        ),
        migrations.AlterField(
            model_name="safeguardingreferral",
            name="modified_at",
            field=models.DateTimeField(blank=True, db_column="modified_at", null=True),
        ),
        migrations.AlterField(
            model_name="safeguardingreferral",
            name="modified_by",
            field=models.TextField(blank=True, db_column="modified_by", null=True),
        ),
        migrations.AlterField(
            model_name="safeguardingreferral",
            name="notional_data",
            field=models.BooleanField(blank=True, db_column="notional_data", null=True),
        ),
        migrations.AlterField(
            model_name="safeguardingreferral",
            name="person",
            field=models.ForeignKey(
                blank=True,
                db_column="person_id",
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="ontology.mvperson",
            ),
        ),
        migrations.AlterField(
            model_name="safeguardingreferral",
            name="person_has_new_uans",
            field=models.BooleanField(
                blank=True, db_column="person_has_new_uans", null=True
            ),
        ),
        migrations.AlterField(
            model_name="safeguardingreferral",
            name="title_key",
            field=models.TextField(blank=True, db_column="title_key", null=True),
        ),
        migrations.AlterField(
            model_name="safeguardingreferral",
            name="viewer_group_names",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                blank=True,
                db_column="viewer_group_names",
                null=True,
                size=None,
            ),
        ),
    ]
