# Generated by Django 5.2.2 on 2025-08-22 12:41

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ontology", "0080_alter_safeguardingreferral_alerted_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sponsorshipcertificationform",
            name="certificate_reference",
            field=models.TextField(
                blank=True,
                db_column="certificate_reference",
                null=True,
                verbose_name="Child sponsorship approval number",
            ),
        ),
        migrations.AlterField(
            model_name="sponsorshipcertificationform",
            name="cohabitant_date_of_birth",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                blank=True,
                db_column="cohabitant_date_of_birth",
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="sponsorshipcertificationform",
            name="cohabitant_family_name",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                blank=True,
                db_column="cohabitant_family_name",
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="sponsorshipcertificationform",
            name="cohabitant_given_name",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                blank=True,
                db_column="cohabitant_given_name",
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="sponsorshipcertificationform",
            name="cohabitant_id",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                blank=True,
                db_column="cohabitant_id",
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="sponsorshipcertificationform",
            name="cohabitant_id_type_and_number",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                blank=True,
                db_column="cohabitant_id_type_and_number",
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="sponsorshipcertificationform",
            name="cohabitant_nationality",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                blank=True,
                db_column="cohabitant_nationality",
                null=True,
                size=None,
                verbose_name="Nationality",
            ),
        ),
        migrations.AlterField(
            model_name="sponsorshipcertificationform",
            name="created_at",
            field=models.DateTimeField(
                blank=True,
                db_column="created_at",
                null=True,
                verbose_name="Date created",
            ),
        ),
        migrations.AlterField(
            model_name="sponsorshipcertificationform",
            name="different_address",
            field=models.BooleanField(
                blank=True, db_column="different_address", null=True
            ),
        ),
        migrations.AlterField(
            model_name="sponsorshipcertificationform",
            name="email",
            field=models.TextField(
                blank=True, db_column="email", null=True, verbose_name="Email address"
            ),
        ),
        migrations.AlterField(
            model_name="sponsorshipcertificationform",
            name="family_name",
            field=models.TextField(
                blank=True, db_column="family_name", null=True, verbose_name="Last name"
            ),
        ),
        migrations.AlterField(
            model_name="sponsorshipcertificationform",
            name="foundry_time",
            field=models.DateTimeField(blank=True, db_column="foundry_time", null=True),
        ),
        migrations.AlterField(
            model_name="sponsorshipcertificationform",
            name="given_name",
            field=models.TextField(
                blank=True, db_column="given_name", null=True, verbose_name="First name"
            ),
        ),
        migrations.AlterField(
            model_name="sponsorshipcertificationform",
            name="has_other_names",
            field=models.BooleanField(
                blank=True, db_column="has_other_names", null=True
            ),
        ),
        migrations.AlterField(
            model_name="sponsorshipcertificationform",
            name="has_other_nationalities",
            field=models.BooleanField(
                blank=True, db_column="has_other_nationalities", null=True
            ),
        ),
        migrations.AlterField(
            model_name="sponsorshipcertificationform",
            name="has_parental_consent",
            field=models.BooleanField(
                blank=True, db_column="has_parental_consent", null=True
            ),
        ),
        migrations.AlterField(
            model_name="sponsorshipcertificationform",
            name="identification_number",
            field=models.TextField(
                blank=True,
                db_column="identification_number",
                null=True,
                verbose_name="Identification number",
            ),
        ),
        migrations.AlterField(
            model_name="sponsorshipcertificationform",
            name="identification_type",
            field=models.TextField(
                blank=True,
                choices=[
                    ("passport", "Passport"),
                    ("national_identity_card", "National Identity Card"),
                    ("biometric_residence", "Biometric Residence Permit or Card"),
                    ("photo_driving_licence", "Photo driving licence"),
                    ("refugee_travel_document", "Refugee Travel Document"),
                    ("none", "None provided"),
                ],
                db_column="identification_type",
                null=True,
                verbose_name="Identification type",
            ),
        ),
        migrations.AlterField(
            model_name="sponsorshipcertificationform",
            name="is_committed",
            field=models.BooleanField(blank=True, db_column="is_committed", null=True),
        ),
        migrations.AlterField(
            model_name="sponsorshipcertificationform",
            name="is_consent",
            field=models.BooleanField(blank=True, db_column="is_consent", null=True),
        ),
        migrations.AlterField(
            model_name="sponsorshipcertificationform",
            name="is_living_december",
            field=models.BooleanField(
                blank=True, db_column="is_living_december", null=True
            ),
        ),
        migrations.AlterField(
            model_name="sponsorshipcertificationform",
            name="is_permitted",
            field=models.BooleanField(blank=True, db_column="is_permitted", null=True),
        ),
        migrations.AlterField(
            model_name="sponsorshipcertificationform",
            name="is_unaccompanied",
            field=models.BooleanField(
                blank=True, db_column="is_unaccompanied", null=True
            ),
        ),
        migrations.AlterField(
            model_name="sponsorshipcertificationform",
            name="is_under_18",
            field=models.BooleanField(blank=True, db_column="is_under_18", null=True),
        ),
        migrations.AlterField(
            model_name="sponsorshipcertificationform",
            name="ltla_name",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                blank=True,
                db_column="ltla_name",
                null=True,
                size=None,
                verbose_name="Local authority",
            ),
        ),
        migrations.AlterField(
            model_name="sponsorshipcertificationform",
            name="minor_contact_type",
            field=models.TextField(
                blank=True, db_column="minor_contact_type", null=True
            ),
        ),
        migrations.AlterField(
            model_name="sponsorshipcertificationform",
            name="minor_date_of_birth",
            field=models.DateField(
                blank=True, db_column="minor_date_of_birth", null=True
            ),
        ),
        migrations.AlterField(
            model_name="sponsorshipcertificationform",
            name="minor_email",
            field=models.TextField(blank=True, db_column="minor_email", null=True),
        ),
        migrations.AlterField(
            model_name="sponsorshipcertificationform",
            name="minor_family_name",
            field=models.TextField(
                blank=True, db_column="minor_family_name", null=True
            ),
        ),
        migrations.AlterField(
            model_name="sponsorshipcertificationform",
            name="minor_given_name",
            field=models.TextField(blank=True, db_column="minor_given_name", null=True),
        ),
        migrations.AlterField(
            model_name="sponsorshipcertificationform",
            name="minor_phone_number",
            field=models.TextField(
                blank=True, db_column="minor_phone_number", null=True
            ),
        ),
        migrations.AlterField(
            model_name="sponsorshipcertificationform",
            name="nationality",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                blank=True,
                db_column="nationality",
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="sponsorshipcertificationform",
            name="notification_sent",
            field=models.BooleanField(
                blank=True, db_column="notification_sent", null=True
            ),
        ),
        migrations.AlterField(
            model_name="sponsorshipcertificationform",
            name="notification_timestamp",
            field=models.DateTimeField(
                blank=True, db_column="notification_timestamp", null=True
            ),
        ),
        migrations.AlterField(
            model_name="sponsorshipcertificationform",
            name="notional_data",
            field=models.BooleanField(blank=True, db_column="notional_data", null=True),
        ),
        migrations.AlterField(
            model_name="sponsorshipcertificationform",
            name="other_adults_address",
            field=models.BooleanField(
                blank=True, db_column="other_adults_address", null=True
            ),
        ),
        migrations.AlterField(
            model_name="sponsorshipcertificationform",
            name="other_names",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                blank=True,
                db_column="other_names",
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="sponsorshipcertificationform",
            name="phone_number",
            field=models.TextField(
                blank=True,
                db_column="phone_number",
                null=True,
                verbose_name="Phone number",
            ),
        ),
        migrations.AlterField(
            model_name="sponsorshipcertificationform",
            name="residential_line_1",
            field=models.TextField(
                blank=True, db_column="residential_line_1", null=True
            ),
        ),
        migrations.AlterField(
            model_name="sponsorshipcertificationform",
            name="residential_line_2",
            field=models.TextField(
                blank=True, db_column="residential_line_2", null=True
            ),
        ),
        migrations.AlterField(
            model_name="sponsorshipcertificationform",
            name="residential_postcode",
            field=models.TextField(
                blank=True,
                db_column="residential_postcode",
                null=True,
                verbose_name="Postcode",
            ),
        ),
        migrations.AlterField(
            model_name="sponsorshipcertificationform",
            name="residential_town",
            field=models.TextField(blank=True, db_column="residential_town", null=True),
        ),
        migrations.AlterField(
            model_name="sponsorshipcertificationform",
            name="sponsor_date_of_birth",
            field=models.DateField(
                blank=True,
                db_column="sponsor_date_of_birth",
                null=True,
                verbose_name="Date of birth",
            ),
        ),
        migrations.AlterField(
            model_name="sponsorshipcertificationform",
            name="sponsor_declaration",
            field=models.TextField(
                blank=True, db_column="sponsor_declaration", null=True
            ),
        ),
        migrations.AlterField(
            model_name="sponsorshipcertificationform",
            name="started_at",
            field=models.DateTimeField(blank=True, db_column="started_at", null=True),
        ),
        migrations.AlterField(
            model_name="sponsorshipcertificationform",
            name="uk_parental_consent_file_size",
            field=models.BigIntegerField(
                blank=True, db_column="uk_parental_consent_file_size", null=True
            ),
        ),
        migrations.AlterField(
            model_name="sponsorshipcertificationform",
            name="uk_parental_consent_file_type",
            field=models.TextField(
                blank=True, db_column="uk_parental_consent_file_type", null=True
            ),
        ),
        migrations.AlterField(
            model_name="sponsorshipcertificationform",
            name="uk_parental_consent_filename",
            field=models.TextField(
                blank=True, db_column="uk_parental_consent_filename", null=True
            ),
        ),
        migrations.AlterField(
            model_name="sponsorshipcertificationform",
            name="uk_parental_consent_saved_filename",
            field=models.TextField(
                blank=True, db_column="uk_parental_consent_saved_filename", null=True
            ),
        ),
        migrations.AlterField(
            model_name="sponsorshipcertificationform",
            name="ukraine_parental_consent_file_size",
            field=models.BigIntegerField(
                blank=True, db_column="ukraine_parental_consent_file_size", null=True
            ),
        ),
        migrations.AlterField(
            model_name="sponsorshipcertificationform",
            name="ukraine_parental_consent_file_type",
            field=models.TextField(
                blank=True, db_column="ukraine_parental_consent_file_type", null=True
            ),
        ),
        migrations.AlterField(
            model_name="sponsorshipcertificationform",
            name="ukraine_parental_consent_filename",
            field=models.TextField(
                blank=True, db_column="ukraine_parental_consent_filename", null=True
            ),
        ),
        migrations.AlterField(
            model_name="sponsorshipcertificationform",
            name="ukraine_parental_consent_saved_filename",
            field=models.TextField(
                blank=True,
                db_column="ukraine_parental_consent_saved_filename",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="sponsorshipcertificationform",
            name="utla_name",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                blank=True,
                db_column="utla_name",
                null=True,
                size=None,
                verbose_name="Upper tier LA",
            ),
        ),
        migrations.AlterField(
            model_name="sponsorshipcertificationform",
            name="viewer_group_names",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                blank=True,
                db_column="viewer_group_names",
                null=True,
                size=None,
            ),
        ),
    ]
