# Generated by Django 5.2.2 on 2025-08-22 12:44

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "ontology",
            "0081_alter_sponsorshipcertificationform_certificate_reference_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="visaapplication",
            name="Q101a_uk_address_staying",
            field=models.TextField(
                blank=True,
                db_column="Q101a_uk_address_staying",
                null=True,
                verbose_name="Q101a UK address staying",
            ),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="Q101b_uk_address_staying_local_authority",
            field=models.TextField(
                blank=True,
                db_column="Q101b_uk_address_staying_local_authority",
                null=True,
                verbose_name="Q101b UK address staying local authority",
            ),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="Q101c_uk_address_staying_country",
            field=models.TextField(
                blank=True,
                db_column="Q101c_uk_address_staying_country",
                null=True,
                verbose_name="Q101c UK address staying country",
            ),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="Q10a_is_one_member_family_ukraine_citizen",
            field=models.TextField(
                blank=True,
                db_column="Q10a_is_one_member_family_ukraine_citizen",
                null=True,
                verbose_name="Q10a is one member family Ukraine citizen",
            ),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="Q11b_applicant_date_of_birth",
            field=models.DateField(
                blank=True, db_column="Q11b_applicant_date_of_birth", null=True
            ),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="Q12a_applicant_known_passport_travel_number",
            field=models.TextField(
                blank=True,
                db_column="Q12a_applicant_known_passport_travel_number",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="Q12b_applicant_passport_travel_number",
            field=models.TextField(
                blank=True, db_column="Q12b_applicant_passport_travel_number", null=True
            ),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="Q13a_applicant_passport_issuing_authority",
            field=models.TextField(
                blank=True,
                db_column="Q13a_applicant_passport_issuing_authority",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="Q13b_applicant_passport_issue_date",
            field=models.DateField(
                blank=True, db_column="Q13b_applicant_passport_issue_date", null=True
            ),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="Q13c_applicant_passport_expiry_date",
            field=models.DateField(
                blank=True, db_column="Q13c_applicant_passport_expiry_date", null=True
            ),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="Q14b_applicant_email_address",
            field=models.TextField(
                blank=True, db_column="Q14b_applicant_email_address", null=True
            ),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="Q15a_sponsor_other_name",
            field=models.TextField(
                blank=True, db_column="Q15a_sponsor_other_name", null=True
            ),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="Q16a_sponsor_other_name_details",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                blank=True,
                db_column="Q16a_sponsor_other_name_details",
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="Q18a_sponsor_is_in_address_uk",
            field=models.TextField(
                blank=True,
                db_column="Q18a_sponsor_is_in_address_uk",
                null=True,
                verbose_name="Q18a sponsor is in address UK",
            ),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="Q18b_sponsor_address_uk",
            field=models.TextField(
                blank=True,
                db_column="Q18b_sponsor_address_uk",
                null=True,
                verbose_name="Q18b sponsor address UK",
            ),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="Q18c_sponsor_address_uk_local_authority",
            field=models.TextField(
                blank=True,
                db_column="Q18c_sponsor_address_uk_local_authority",
                null=True,
                verbose_name="Q18c sponsor address UK local authority",
            ),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="Q18d_sponsor_address_uk_country",
            field=models.TextField(
                blank=True,
                db_column="Q18d_sponsor_address_uk_country",
                null=True,
                verbose_name="Q18d sponsor address UK country",
            ),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="Q18f_sponsor_address_started_living_at",
            field=models.DateField(
                blank=True,
                db_column="Q18f_sponsor_address_started_living_at",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="Q19a_sponsor_addresses_2_years",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                blank=True,
                db_column="Q19a_sponsor_addresses_2_years",
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="Q21a_application_sex",
            field=models.TextField(
                blank=True, db_column="Q21a_application_sex", null=True
            ),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="Q21b_applicant_relationship_status",
            field=models.TextField(
                blank=True, db_column="Q21b_applicant_relationship_status", null=True
            ),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="Q22a_sponsor_id_is_valid",
            field=models.TextField(
                blank=True,
                db_column="Q22a_sponsor_id_is_valid",
                null=True,
                verbose_name="Q22a sponsor ID is valid",
            ),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="Q22b_sponsor_id_card_number",
            field=models.TextField(
                blank=True,
                db_column="Q22b_sponsor_id_card_number",
                null=True,
                verbose_name="Q22b sponsor ID card number",
            ),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="Q22c_sponsor_id_issuing_authority",
            field=models.TextField(
                blank=True,
                db_column="Q22c_sponsor_id_issuing_authority",
                null=True,
                verbose_name="Q22c sponsor ID issuing authority",
            ),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="Q22d_sponsor_id_issue_date",
            field=models.DateField(
                blank=True,
                db_column="Q22d_sponsor_id_issue_date",
                null=True,
                verbose_name="Q22d sponsor ID issue date",
            ),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="Q22e_sponsor_id_expiry_date",
            field=models.DateField(
                blank=True,
                db_column="Q22e_sponsor_id_expiry_date",
                null=True,
                verbose_name="Q22e sponsor ID expiry date",
            ),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="Q25a_sponsor_other_nationality_details",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                blank=True,
                db_column="Q25a_sponsor_other_nationality_details",
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="Q29a_applicant_will_stay_at_sponsor_address",
            field=models.TextField(
                blank=True,
                db_column="Q29a_applicant_will_stay_at_sponsor_address",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="Q2a_living_ukraine_before_jan_22",
            field=models.TextField(
                blank=True,
                db_column="Q2a_living_ukraine_before_jan_22",
                null=True,
                verbose_name="Q2a living Ukraine before Jan 22",
            ),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="Q31a_other_people_will_live_at_address",
            field=models.TextField(
                blank=True,
                db_column="Q31a_other_people_will_live_at_address",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="Q32a_other_household_member_given_name",
            field=models.TextField(
                blank=True,
                db_column="Q32a_other_household_member_given_name",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="Q32b_other_household_member_family_name",
            field=models.TextField(
                blank=True,
                db_column="Q32b_other_household_member_family_name",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="Q32c_other_household_member_date_of_birth",
            field=models.DateField(
                blank=True,
                db_column="Q32c_other_household_member_date_of_birth",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="Q32d_other_household_member_nationality",
            field=models.TextField(
                blank=True,
                db_column="Q32d_other_household_member_nationality",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="Q32e_other_household_member_passport",
            field=models.TextField(
                blank=True, db_column="Q32e_other_household_member_passport", null=True
            ),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="Q33a_other_people_will_live_at_address",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                blank=True,
                db_column="Q33a_other_people_will_live_at_address",
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="Q34a_email_owner",
            field=models.TextField(blank=True, db_column="Q34a_email_owner", null=True),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="Q34b_email_address",
            field=models.TextField(
                blank=True, db_column="Q34b_email_address", null=True
            ),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="Q35a_has_email_address",
            field=models.TextField(
                blank=True, db_column="Q35a_has_email_address", null=True
            ),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="Q35b_email_address",
            field=models.TextField(
                blank=True, db_column="Q35b_email_address", null=True
            ),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="Q36a_has_other_email_address",
            field=models.TextField(
                blank=True, db_column="Q36a_has_other_email_address", null=True
            ),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="Q36b_which_email_contact_applicant",
            field=models.TextField(
                blank=True, db_column="Q36b_which_email_contact_applicant", null=True
            ),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="Q36d_which_email_application_decision",
            field=models.TextField(
                blank=True, db_column="Q36d_which_email_application_decision", null=True
            ),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="Q36f_which_email_communicate_after_application",
            field=models.TextField(
                blank=True,
                db_column="Q36f_which_email_communicate_after_application",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="Q37a_add_other_email",
            field=models.TextField(
                blank=True, db_column="Q37a_add_other_email", null=True
            ),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="Q37b_email_address_owner",
            field=models.TextField(
                blank=True, db_column="Q37b_email_address_owner", null=True
            ),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="Q39b_which_email_contact_applicant",
            field=models.TextField(
                blank=True, db_column="Q39b_which_email_contact_applicant", null=True
            ),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="Q39d_explanation_no_email_questions",
            field=models.TextField(
                blank=True, db_column="Q39d_explanation_no_email_questions", null=True
            ),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="Q39f_which_email_application_decision",
            field=models.TextField(
                blank=True, db_column="Q39f_which_email_application_decision", null=True
            ),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="Q39h_explanation_no_email_application_decision",
            field=models.TextField(
                blank=True,
                db_column="Q39h_explanation_no_email_application_decision",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="Q39j_which_email_communicate_after_application",
            field=models.TextField(
                blank=True,
                db_column="Q39j_which_email_communicate_after_application",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="Q39l_explanation_no_email_communicate_after_application",
            field=models.TextField(
                blank=True,
                db_column="Q39l_explanation_no_email_communicate_after_application",
                null=True,
                verbose_name="Q39l explanation no email communicate after applications",
            ),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="Q3a_sponsor_uk_permission",
            field=models.TextField(
                blank=True,
                db_column="Q3a_sponsor_uk_permission",
                null=True,
                verbose_name="Q3a sponsor UK permission",
            ),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="Q3b_sponsor_description",
            field=models.TextField(
                blank=True, db_column="Q3b_sponsor_description", null=True
            ),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="Q3c_sponsor_immigration_status",
            field=models.TextField(
                blank=True, db_column="Q3c_sponsor_immigration_status", null=True
            ),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="Q40a_telephone_number_details",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                blank=True,
                db_column="Q40a_telephone_number_details",
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="Q42a_can_be_contacted_by_telephon",
            field=models.TextField(
                blank=True,
                db_column="Q42a_can_be_contacted_by_telephon",
                null=True,
                verbose_name="Q42a can be contacted by telephone",
            ),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="Q42b_explanation_no_contact_sms",
            field=models.TextField(
                blank=True, db_column="Q42b_explanation_no_contact_sms", null=True
            ),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="Q42c_explanation_no_contact_call",
            field=models.TextField(
                blank=True, db_column="Q42c_explanation_no_contact_call", null=True
            ),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="Q42d_explanation_no_contact_call_or_text",
            field=models.TextField(
                blank=True,
                db_column="Q42d_explanation_no_contact_call_or_text",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="Q43a_preferred_contact_number",
            field=models.TextField(
                blank=True, db_column="Q43a_preferred_contact_number", null=True
            ),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="Q44b_given_name",
            field=models.TextField(blank=True, db_column="Q44b_given_name", null=True),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="Q44c_family_name",
            field=models.TextField(blank=True, db_column="Q44c_family_name", null=True),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="Q44g_full_name",
            field=models.TextField(blank=True, db_column="Q44g_full_name", null=True),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="Q45a_other_name_details",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                blank=True,
                db_column="Q45a_other_name_details",
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="Q47a_lass_ukraine_address",
            field=models.TextField(
                blank=True,
                db_column="Q47a_lass_ukraine_address",
                null=True,
                verbose_name="Q47a last Ukraine address",
            ),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="Q52c_place_of_birth",
            field=models.TextField(
                blank=True, db_column="Q52c_place_of_birth", null=True
            ),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="Q52d_date_of_birth",
            field=models.DateField(
                blank=True, db_column="Q52d_date_of_birth", null=True
            ),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="Q54a_other_nationality_details",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                blank=True,
                db_column="Q54a_other_nationality_details",
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="Q5b_applicant_email_address",
            field=models.TextField(
                blank=True, db_column="Q5b_applicant_email_address", null=True
            ),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="Q5c_applicant_repeat_email_address",
            field=models.TextField(
                blank=True, db_column="Q5c_applicant_repeat_email_address", null=True
            ),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="Q5f_applicant_email_creation_date",
            field=models.DateTimeField(
                blank=True, db_column="Q5f_applicant_email_creation_date", null=True
            ),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="Q5g_application_email_creation_person",
            field=models.TextField(
                blank=True, db_column="Q5g_application_email_creation_person", null=True
            ),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="Q63a_has_family_members_applying",
            field=models.TextField(
                blank=True, db_column="Q63a_has_family_members_applying", null=True
            ),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="Q64a_relationship_with_applicant",
            field=models.TextField(
                blank=True, db_column="Q64a_relationship_with_applicant", null=True
            ),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="Q64b_family_member_names",
            field=models.TextField(
                blank=True, db_column="Q64b_family_member_names", null=True
            ),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="Q64c_family_member_family_name",
            field=models.TextField(
                blank=True, db_column="Q64c_family_member_family_name", null=True
            ),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="Q64d_family_member_date_of_birth",
            field=models.DateField(
                blank=True, db_column="Q64d_family_member_date_of_birth", null=True
            ),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="Q64e_is_family_member_travelling_uk",
            field=models.TextField(
                blank=True,
                db_column="Q64e_is_family_member_travelling_uk",
                null=True,
                verbose_name="Q64e is family member travelling UK",
            ),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="Q64f_family_member_country_of_nationality",
            field=models.TextField(
                blank=True,
                db_column="Q64f_family_member_country_of_nationality",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="Q64g_family_member_passport_number",
            field=models.TextField(
                blank=True, db_column="Q64g_family_member_passport_number", null=True
            ),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="Q66a_uk_arrival_date",
            field=models.DateField(
                blank=True,
                db_column="Q66a_uk_arrival_date",
                null=True,
                verbose_name="Q66a UK arrival date",
            ),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="Q68a_immigration_problem_details",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                blank=True,
                db_column="Q68a_immigration_problem_details",
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="Q6c_person_joining_given_name",
            field=models.TextField(
                blank=True, db_column="Q6c_person_joining_given_name", null=True
            ),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="Q6d_person_joining_family_name",
            field=models.TextField(
                blank=True, db_column="Q6d_person_joining_family_name", null=True
            ),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="Q6e_person_joining_full_name",
            field=models.TextField(
                blank=True, db_column="Q6e_person_joining_full_name", null=True
            ),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="Q70a_breach_uk_immigration_law",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                blank=True,
                db_column="Q70a_breach_uk_immigration_law",
                null=True,
                size=None,
                verbose_name="Q70a breach UK immigration law",
            ),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="Q73a_conviction_and_other_penalties",
            field=models.TextField(
                blank=True, db_column="Q73a_conviction_and_other_penalties", null=True
            ),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="Q86a_data_sharing_permission",
            field=models.TextField(
                blank=True, db_column="Q86a_data_sharing_permission", null=True
            ),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="Q89a_third_party_capacity_representing",
            field=models.TextField(
                blank=True,
                db_column="Q89a_third_party_capacity_representing",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="Q89b_third_party_relation_to_applicant",
            field=models.TextField(
                blank=True,
                db_column="Q89b_third_party_relation_to_applicant",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="Q89c_third_party_capacity_details",
            field=models.TextField(
                blank=True, db_column="Q89c_third_party_capacity_details", null=True
            ),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="Q90a_third_party_full_name",
            field=models.TextField(
                blank=True, db_column="Q90a_third_party_full_name", null=True
            ),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="Q90b_third_party_name",
            field=models.TextField(
                blank=True, db_column="Q90b_third_party_name", null=True
            ),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="Q90c_third_party_telephone_number",
            field=models.TextField(
                blank=True, db_column="Q90c_third_party_telephone_number", null=True
            ),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="Q90d_third_party_email_address",
            field=models.TextField(
                blank=True, db_column="Q90d_third_party_email_address", null=True
            ),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="Q90e_third_party_address",
            field=models.TextField(
                blank=True, db_column="Q90e_third_party_address", null=True
            ),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="Q90f_third_party_state",
            field=models.TextField(
                blank=True, db_column="Q90f_third_party_state", null=True
            ),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="Q90g_third_party_country",
            field=models.TextField(
                blank=True, db_column="Q90g_third_party_country", null=True
            ),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="Q91b_permission_uk_postcode",
            field=models.TextField(
                blank=True,
                db_column="Q91b_permission_uk_postcode",
                null=True,
                verbose_name="Q91b permission UK postcode",
            ),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="Q91c_permission_acl_code",
            field=models.TextField(
                blank=True,
                db_column="Q91c_permission_acl_code",
                null=True,
                verbose_name="Q91c permission ACL code",
            ),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="Q91d_permission_brp_collection_location",
            field=models.TextField(
                blank=True,
                db_column="Q91d_permission_brp_collection_location",
                null=True,
                verbose_name="Q91d permission BRP collection location",
            ),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="Q95a_external_reference",
            field=models.TextField(
                blank=True, db_column="Q95a_external_reference", null=True
            ),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="Q96a_enrollment_organisation",
            field=models.TextField(
                blank=True, db_column="Q96a_enrollment_organisation", null=True
            ),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="Q97a_sponsor_given_name",
            field=models.TextField(
                blank=True, db_column="Q97a_sponsor_given_name", null=True
            ),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="Q97b_sponsor_family_name",
            field=models.TextField(
                blank=True, db_column="Q97b_sponsor_family_name", null=True
            ),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="Q97c_sponsor_name",
            field=models.TextField(
                blank=True, db_column="Q97c_sponsor_name", null=True
            ),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="Q98a_sponsoring_organisation",
            field=models.TextField(
                blank=True, db_column="Q98a_sponsoring_organisation", null=True
            ),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="Q99a_sponsor_relationship_status",
            field=models.TextField(
                blank=True, db_column="Q99a_sponsor_relationship_status", null=True
            ),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="Q99b_sponsor_relationship_sex",
            field=models.TextField(
                blank=True, db_column="Q99b_sponsor_relationship_sex", null=True
            ),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="address_preference",
            field=models.TextField(
                blank=True, db_column="address_preference", null=True
            ),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="applicant_arrival_time",
            field=models.DateTimeField(
                blank=True, db_column="applicant_arrival_time", null=True
            ),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="applicant_final_address",
            field=models.TextField(
                blank=True, db_column="applicant_final_address", null=True
            ),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="application_event_datetime",
            field=models.DateTimeField(
                blank=True, db_column="application_event_datetime", null=True
            ),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="application_unique_application_number",
            field=models.TextField(
                blank=True,
                db_column="application_unique_application_number",
                null=True,
                verbose_name="Unique application number (UAN)",
            ),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="country",
            field=models.TextField(blank=True, db_column="country", null=True),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="foundry_time",
            field=models.DateTimeField(blank=True, db_column="foundry_time", null=True),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="gwf",
            field=models.TextField(
                blank=True, db_column="gwf", null=True, verbose_name="GWF"
            ),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="is_notional",
            field=models.BooleanField(blank=True, db_column="is_notional", null=True),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="ltla_name",
            field=models.TextField(
                blank=True,
                db_column="ltla_name",
                null=True,
                verbose_name="Lower tier LA name",
            ),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="mapping_postcode",
            field=models.TextField(blank=True, db_column="mapping_postcode", null=True),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="mapping_postcode_FL",
            field=models.TextField(
                blank=True, db_column="mapping_postcode_FL", null=True
            ),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="source",
            field=models.TextField(blank=True, db_column="source", null=True),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="submission_guid",
            field=models.TextField(
                blank=True,
                db_column="submission_guid",
                null=True,
                verbose_name="Submission GUID",
            ),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="title",
            field=models.TextField(blank=True, db_column="title", null=True),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="utla_name",
            field=models.TextField(
                blank=True,
                db_column="utla_name",
                null=True,
                verbose_name="Upper tier LA name",
            ),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="viewer_group_names",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                blank=True,
                db_column="viewer_group_names",
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="viewer_group_names_multi_la",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                blank=True,
                db_column="viewer_group_names_multi_la",
                null=True,
                size=None,
                verbose_name="Viewer group names multi LA",
            ),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="visa_decision_date",
            field=models.DateTimeField(
                blank=True, db_column="visa_decision_date", null=True
            ),
        ),
        migrations.AlterField(
            model_name="visaapplication",
            name="visa_status",
            field=models.TextField(blank=True, db_column="visa_status", null=True),
        ),
    ]
