# Generated by Django 5.2.2 on 2025-08-22 12:46

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ontology", "0082_alter_visaapplication_q101a_uk_address_staying_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visainformationrequestcomments",
            name="check_id",
            field=models.TextField(blank=True, db_column="check_id", null=True),
        ),
        migrations.AlterField(
            model_name="visainformationrequestcomments",
            name="comment",
            field=models.TextField(blank=True, db_column="comment", null=True),
        ),
        migrations.AlterField(
            model_name="visainformationrequestcomments",
            name="comment_type",
            field=models.TextField(blank=True, db_column="comment_type", null=True),
        ),
        migrations.AlterField(
            model_name="visainformationrequestcomments",
            name="created_at",
            field=models.DateTimeField(blank=True, db_column="created_at", null=True),
        ),
        migrations.AlterField(
            model_name="visainformationrequestcomments",
            name="created_by_organisation",
            field=models.TextField(
                blank=True, db_column="created_by_organisation", null=True
            ),
        ),
        migrations.AlterField(
            model_name="visainformationrequestcomments",
            name="created_by_uid",
            field=models.TextField(blank=True, db_column="created_by_uid", null=True),
        ),
        migrations.AlterField(
            model_name="visainformationrequestcomments",
            name="current_status",
            field=models.TextField(blank=True, db_column="current_status", null=True),
        ),
        migrations.AlterField(
            model_name="visainformationrequestcomments",
            name="display_name",
            field=models.TextField(blank=True, db_column="display_name", null=True),
        ),
        migrations.AlterField(
            model_name="visainformationrequestcomments",
            name="interaction_id",
            field=models.TextField(blank=True, db_column="interaction_id", null=True),
        ),
        migrations.AlterField(
            model_name="visainformationrequestcomments",
            name="is_notional",
            field=models.BooleanField(blank=True, db_column="is_notional", null=True),
        ),
        migrations.AlterField(
            model_name="visainformationrequestcomments",
            name="previous_status",
            field=models.TextField(blank=True, db_column="previous_status", null=True),
        ),
        migrations.AlterField(
            model_name="visainformationrequestcomments",
            name="viewer_group_names",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                blank=True,
                db_column="viewer_group_names",
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="visainformationrequestcomments",
            name="visa_information_request",
            field=models.ForeignKey(
                blank=True,
                db_column="visa_information_request_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vir_comments",
                to="ontology.visainformationrequest",
            ),
        ),
    ]
