# Generated by Django 5.2.2 on 2025-08-22 12:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ontology", "0083_alter_visainformationrequestcomments_check_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visainformationrequest",
            name="bulk_foreign_key",
            field=models.TextField(blank=True, db_column="bulk_foreign_key", null=True),
        ),
        migrations.AlterField(
            model_name="visainformationrequest",
            name="created_at",
            field=models.DateTimeField(blank=True, db_column="created_at", null=True),
        ),
        migrations.AlterField(
            model_name="visainformationrequest",
            name="created_by",
            field=models.TextField(blank=True, db_column="created_by", null=True),
        ),
        migrations.AlterField(
            model_name="visainformationrequest",
            name="forwarded_to_dluhc",
            field=models.BooleanField(
                blank=True, db_column="forwarded_to_dluhc", null=True
            ),
        ),
        migrations.AlterField(
            model_name="visainformationrequest",
            name="is_notional",
            field=models.BooleanField(blank=True, db_column="is_notional", null=True),
        ),
        migrations.AlterField(
            model_name="visainformationrequest",
            name="ltla_name",
            field=models.TextField(blank=True, db_column="ltla_name", null=True),
        ),
        migrations.AlterField(
            model_name="visainformationrequest",
            name="modified_at",
            field=models.DateTimeField(blank=True, db_column="modified_at", null=True),
        ),
        migrations.AlterField(
            model_name="visainformationrequest",
            name="modified_by",
            field=models.TextField(blank=True, db_column="modified_by", null=True),
        ),
        migrations.AlterField(
            model_name="visainformationrequest",
            name="request_details",
            field=models.TextField(blank=True, db_column="request_details", null=True),
        ),
        migrations.AlterField(
            model_name="visainformationrequest",
            name="request_status",
            field=models.TextField(
                blank=True,
                choices=[
                    ("Awaiting UKVI", "Awaiting UKVI"),
                    ("Awaiting LA", "Awaiting LA"),
                    ("Closed", "Closed"),
                ],
                db_column="request_status",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="visainformationrequest",
            name="request_title",
            field=models.TextField(blank=True, db_column="request_title", null=True),
        ),
        migrations.AlterField(
            model_name="visainformationrequest",
            name="request_type",
            field=models.TextField(
                blank=True,
                choices=[
                    ("GENERAL", "General"),
                    ("CHILD_SPONSORED_BY_PARENTS", "Child sponsored by parents"),
                ],
                db_column="request_type",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="visainformationrequest",
            name="requested_at",
            field=models.DateTimeField(blank=True, db_column="requested_at", null=True),
        ),
        migrations.AlterField(
            model_name="visainformationrequest",
            name="requested_check_type_id",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(
                    choices=[
                        ("ACCOMM_SUITABLE", "Accommodation suitable"),
                        ("SPONSOR_DBS", "DBS check and Sponsor suitable"),
                    ]
                ),
                blank=True,
                db_column="requested_check_type_id",
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="visainformationrequest",
            name="utla_name",
            field=models.TextField(blank=True, db_column="utla_name", null=True),
        ),
        migrations.AlterField(
            model_name="visainformationrequest",
            name="viewer_group_names",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                blank=True,
                db_column="viewer_group_names",
                null=True,
                size=None,
            ),
        ),
    ]
