# Generated by Django 5.2.2 on 2025-08-26 14:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ontology", "0084_alter_visainformationrequest_bulk_foreign_key_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MvInteractionAttachmentMetadata",
            fields=[
                (
                    "id",
                    models.TextField(db_column="id", primary_key=True, serialize=False),
                ),
                ("type", models.TextField(blank=True, db_column="type", null=True)),
                ("size_bytes", models.TextField(db_column="size_bytes", null=True)),
                ("media_type", models.TextField(db_column="media_type", null=True)),
                ("rid", models.TextField(db_column="rid", null=True)),
                ("filename", models.TextField(db_column="filename", null=True)),
                ("file_path", models.TextField(db_column="file_path", null=True)),
                ("error", models.TextField(blank=True, db_column="error", null=True)),
                (
                    "status_code",
                    models.TextField(blank=True, db_column="status_code", null=True),
                ),
                (
                    "object_type",
                    models.TextField(blank=True, db_column="object_type", null=True),
                ),
                (
                    "attachment_property",
                    models.TextField(
                        blank=True, db_column="attachment_property", null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Interaction Attachment Metadata",
            },
        ),
        migrations.CreateModel(
            name="SponsorshipCertificationAttachmentMetadata",
            fields=[
                (
                    "id",
                    models.TextField(db_column="id", primary_key=True, serialize=False),
                ),
                ("type", models.TextField(blank=True, db_column="type", null=True)),
                ("size_bytes", models.TextField(db_column="size_bytes", null=True)),
                ("media_type", models.TextField(db_column="media_type", null=True)),
                ("rid", models.TextField(db_column="rid", null=True)),
                ("filename", models.TextField(db_column="filename", null=True)),
                ("file_path", models.TextField(db_column="file_path", null=True)),
                ("error", models.TextField(blank=True, db_column="error", null=True)),
                (
                    "status_code",
                    models.TextField(blank=True, db_column="status_code", null=True),
                ),
                (
                    "object_type",
                    models.TextField(blank=True, db_column="object_type", null=True),
                ),
                (
                    "attachment_property",
                    models.TextField(
                        blank=True, db_column="attachment_property", null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Sponsorship Certification Attachment Metadata",
            },
        ),
    ]
