# Generated by Django 5.2.2 on 2025-08-27 10:02

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ontology", "0085_mvinteractionattachmentmetadata_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommentAttachmentMetadata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attachmentLocator",
                    models.TextField(
                        blank=True, db_column="attachmentLocator", null=True
                    ),
                ),
                (
                    "attachment_key",
                    models.TextField(blank=True, db_column="attachment_key", null=True),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, db_column="error_message", null=True),
                ),
                (
                    "file_name",
                    models.TextField(blank=True, db_column="file_name", null=True),
                ),
                (
                    "file_size",
                    models.BigIntegerField(
                        blank=True, db_column="file_size", null=True
                    ),
                ),
                (
                    "resourceId",
                    models.TextField(blank=True, db_column="resourceId", null=True),
                ),
                (
                    "s3_ETag",
                    models.TextField(blank=True, db_column="s3_Etag", null=True),
                ),
                (
                    "s3_error_message",
                    models.TextField(
                        blank=True, db_column="s3_error_message", null=True
                    ),
                ),
                (
                    "s3_status_code",
                    models.TextField(blank=True, db_column="s3_status_code", null=True),
                ),
                (
                    "status_code",
                    models.IntegerField(blank=True, db_column="status_code", null=True),
                ),
                (
                    "processed_timestamp",
                    models.DateTimeField(
                        blank=True, db_column="processed_timestamp", null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Comment Attachment Metadata",
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_column="id",
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "created_by",
                    models.TextField(blank=True, db_column="created_by", null=True),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True, db_column="created_at", null=True
                    ),
                ),
                (
                    "modified_by",
                    models.TextField(blank=True, db_column="modified_by", null=True),
                ),
                (
                    "modified_date",
                    models.DateTimeField(
                        auto_now=True, db_column="modified_at", null=True
                    ),
                ),
                (
                    "content",
                    models.TextField(blank=True, db_column="content", null=True),
                ),
                (
                    "attached_accommodation_request_id",
                    models.ForeignKey(
                        db_column="attached_accommodation_request_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="ontology.mvaccommodationrequest",
                    ),
                ),
                (
                    "attached_reassignment_request_id",
                    models.ForeignKey(
                        db_column="attached_reassignment_request_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="ontology.reassignmentrequest",
                    ),
                ),
            ],
            options={
                "verbose_name": "Comment",
            },
        ),
        migrations.CreateModel(
            name="CommentAttachment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_column="id",
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("key", models.TextField(blank=True, db_column="key", null=True)),
                (
                    "media_type",
                    models.TextField(blank=True, db_column="media_type", null=True),
                ),
                (
                    "filename",
                    models.TextField(blank=True, db_column="filename", null=True),
                ),
                (
                    "comment_id",
                    models.ForeignKey(
                        db_column="comment_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="ontology.comment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Comment Attachment",
            },
        ),
    ]
