# Generated by Django 5.2.2 on 2025-08-28 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ontology", "0086_commentattachmentmetadata_comment_commentattachment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="created_date",
            new_name="created_at",
        ),
        migrations.AlterField(
            model_name="comment",
            name="attached_accommodation_request_id",
            field=models.ForeignKey(
                blank=True,
                db_column="attached_accommodation_request_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="ontology.mvaccommodationrequest",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="attached_reassignment_request_id",
            field=models.ForeignKey(
                blank=True,
                db_column="attached_reassignment_request_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="ontology.reassignmentrequest",
            ),
        ),
    ]
