# Generated by Django 5.2.2 on 2025-09-01 19:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ontology", "0087_rename_created_date_comment_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="devcheckv2",
            name="AR",
            field=models.ManyToManyField(
                blank=True,
                db_column="AR_id",
                db_constraint=False,
                related_name="checks",
                to="ontology.mvaccommodationrequest",
            ),
        ),
    ]
