# Generated by Django 5.2.2 on 2025-09-02 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ontology", "0088_alter_devcheckv2_ar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mvgroup",
            name="merged_group",
            field=models.ForeignKey(
                db_column="merged_group",
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="ontology.mvgroup",
            ),
        ),
        migrations.AlterField(
            model_name="mvgroup",
            name="old_split_group",
            field=models.ForeignKey(
                db_column="old_split_group",
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="ontology.mvgroup",
            ),
        ),
    ]
