# Generated by Django 5.2.2 on 2025-09-02 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ontology", "0089_alter_mvgroup_merged_group_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mvperson",
            name="old_group",
            field=models.ForeignKey(
                blank=True,
                db_column="old_group_id",
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="ontology.mvgroup",
                verbose_name="Old group ID",
            ),
        ),
    ]
