# Generated by Django 5.2.2 on 2025-09-02 16:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ontology", "0090_alter_mvperson_old_group"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="visainformationrequestcomments",
            options={"verbose_name_plural": "Visa information request comments"},
        ),
    ]
