# Generated by Django 5.2.2 on 2025-09-03 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ontology", "0091_alter_visainformationrequestcomments_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mvperson",
            name="accommodation_request",
            field=models.ForeignKey(
                blank=True,
                db_column="accommodation_request_id",
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="ontology.mvaccommodationrequest",
                verbose_name="Accommodation request ID",
            ),
        ),
    ]
