# Generated by Django 5.2.2 on 2025-09-08 17:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ontology", "0092_alter_mvperson_accommodation_request"),
    ]

    operations = [
        migrations.AddField(
            model_name="mvaccommodation",
            name="edited_in_app",
            field=models.BooleanField(db_column="edited_in_app", default=False),
        ),
        migrations.AddField(
            model_name="mvaccommodationrequest",
            name="edited_in_app",
            field=models.BooleanField(db_column="edited_in_app", default=False),
        ),
        migrations.AddField(
            model_name="mvgroup",
            name="edited_in_app",
            field=models.BooleanField(db_column="edited_in_app", default=False),
        ),
        migrations.AddField(
            model_name="mvperson",
            name="edited_in_app",
            field=models.BooleanField(db_column="edited_in_app", default=False),
        ),
        migrations.AddField(
            model_name="mvvolunteer",
            name="edited_in_app",
            field=models.BooleanField(db_column="edited_in_app", default=False),
        ),
    ]
