# Generated by Django 5.2.2 on 2025-09-09 14:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ontology", "0093_mvaccommodation_edited_in_app_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mvaccommodation",
            name="edited_in_app",
            field=models.BooleanField(blank=True, db_column="edited_in_app", null=True),
        ),
        migrations.AlterField(
            model_name="mvaccommodationrequest",
            name="edited_in_app",
            field=models.BooleanField(blank=True, db_column="edited_in_app", null=True),
        ),
        migrations.AlterField(
            model_name="mvgroup",
            name="edited_in_app",
            field=models.BooleanField(blank=True, db_column="edited_in_app", null=True),
        ),
        migrations.AlterField(
            model_name="mvperson",
            name="edited_in_app",
            field=models.BooleanField(blank=True, db_column="edited_in_app", null=True),
        ),
        migrations.AlterField(
            model_name="mvvolunteer",
            name="edited_in_app",
            field=models.BooleanField(blank=True, db_column="edited_in_app", null=True),
        ),
    ]
