# Generated by Django 5.2.2 on 2025-09-08 16:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ontology", "0094_alter_mvaccommodation_edited_in_app_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mvaccommodation",
            name="is_editable",
            field=models.BooleanField(blank=True, db_column="is_editable", null=True),
        ),
        migrations.AddField(
            model_name="mvvolunteer",
            name="is_editable",
            field=models.BooleanField(blank=True, db_column="is_editable", null=True),
        ),
    ]
