# Generated by Django 5.2.2 on 2025-09-10 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "ontology",
            "0096_create_ltla_temporary_accommodations_and_link_to_ltla_sponsor",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="visainformationrequest",
            name="visa_application",
            field=models.ForeignKey(
                blank=True,
                db_column="visa_application",
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="ontology.visaapplication",
            ),
        ),
        migrations.AlterField(
            model_name="visainformationrequestcomments",
            name="visa_information_request",
            field=models.ForeignKey(
                blank=True,
                db_column="visa_information_request_id",
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vir_comments",
                to="ontology.visainformationrequest",
            ),
        ),
    ]
