# Generated by Django 5.2.2 on 2025-09-10 15:56

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ontology", "0097_alter_visainformationrequest_visa_application_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="visainformationrequestcomments",
            name="checks",
        ),
        migrations.AddField(
            model_name="visainformationrequestcomments",
            name="checks",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                blank=True,
                db_column="checks",
                null=True,
                size=None,
            ),
        ),
    ]
