# Generated by Django 5.2.2 on 2025-09-11 09:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ontology", "0098_remove_visainformationrequestcomments_checks_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reassignmentrequest",
            name="outcome",
            field=models.TextField(
                blank=True,
                choices=[
                    ("Accepted", "Accepted"),
                    ("Rejected", "Rejected"),
                    ("Pending", "Pending"),
                    ("Needs Accommodation Request", "Needs Accommodation Request"),
                ],
                db_column="outcome",
                null=True,
            ),
        ),
    ]
