# Generated by Django 5.2.6 on 2025-09-22 20:48
from django.db import migrations

from ontology.migrations.scripts.script_0029 import populate_checktypes
from ontology.migrations.scripts.script_0096 import (
    create_ltla_hosts_and_ghost_temporary_accommodations,
)


class Migration(migrations.Migration):
    # In reality this migration replaces 0029 and 0096
    # But to keep things simple we add these at the end of the chain

    dependencies = [("ontology", "0001_initial_squashed_0099_rename_m2m")]

    operations = [
        migrations.RunPython(populate_checktypes),
        migrations.RunPython(create_ltla_hosts_and_ghost_temporary_accommodations),
    ]
