# Generated by Django 5.2.2 on 2025-09-11 16:27

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ontology", "0001_initial_squashed_0099_runpython"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visainformationrequest",
            name="request_status",
            field=models.TextField(
                blank=True,
                choices=[
                    ("Waiting on UKVI", "Awaiting UKVI"),
                    ("Waiting on LA", "Awaiting LA"),
                    ("Closed", "Closed"),
                    ("Awaiting UKVI", "Awaiting UKVI Deprecated"),
                    ("Awaiting LA", "Awaiting LA Deprecated"),
                    ("Waiting on MHCLG", "Waiting on MHCLG Deprecated"),
                    ("Waiting on DLUHC", "Waiting on DLUHC Deprecated"),
                    ("Closed - Not needed", "Closed - Not needed Deprecated"),
                    ("Closed - Resolved", "Closed - Resolved Deprecated"),
                ],
                db_column="request_status",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="visainformationrequest",
            name="request_type",
            field=models.TextField(
                blank=True,
                choices=[
                    ("General", "General"),
                    ("Child Sponsored by Parent", "Child sponsored by parents"),
                ],
                db_column="request_type",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="visainformationrequest",
            name="requested_check_type_id",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(
                    choices=[
                        ("1", "Accomm Exists"),
                        ("2", "Accomm Suitable"),
                        ("3", "Sponsor Dbs"),
                        ("4", "Group Arrived"),
                        ("5", "Sg Checks Complete"),
                        ("6", "Eoi Dbs"),
                        ("7", "Sponsor Accepts Role"),
                        ("8", "Sponsor Arrangements Suitable"),
                        ("9", "Uk Form Uploaded"),
                        ("10", "Ukr Form Uploaded"),
                        ("11", "Ho Checks Household"),
                        ("12", "Ho Checks Sponsor"),
                    ]
                ),
                blank=True,
                db_column="requested_check_type_id",
                null=True,
                size=None,
            ),
        ),
    ]
