# Generated by Django 5.2.6 on 2025-09-29 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ontology", "0100_alter_visainformationrequest_request_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sponsorshipcertificationattachmentmetadata",
            name="sponsorship_certification_form",
            field=models.ForeignKey(
                blank=True,
                db_column="sponsorship_certification_form_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attachments_metadata",
                to="ontology.sponsorshipcertificationform",
                verbose_name="Sponsorship Certification Form",
            ),
        ),
    ]
