# Generated by Django 5.2.7 on 2025-10-10 10:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "ontology",
            "0101_sponsorshipcertificationattachmentmetadata_sponsorship_certification_form",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="accommodationmasterrecord",
            name="accommodations",
            field=models.ManyToManyField(
                db_table="ontology_accommodation_to_master_record",
                related_name="master_record",
                to="ontology.mvaccommodation",
            ),
        ),
        migrations.AddField(
            model_name="sponsormasterrecord",
            name="sponsors",
            field=models.ManyToManyField(
                db_table="ontology_sponsor_to_master_record",
                related_name="master_record",
                to="ontology.mvvolunteer",
            ),
        ),
    ]
