# Generated by Django 5.2.7 on 2025-10-29 17:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ontology", "0102_accommodationmasterrecord_accommodations_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commentattachment",
            name="comment_id",
            field=models.UUIDField(db_column="comment_id"),
        ),
    ]
