# Generated by Django 5.2.8 on 2025-11-07 12:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ontology", "0103_alter_commentattachment_comment_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="announcement",
            name="hidden",
            field=models.BooleanField(
                default=False, help_text="Check to hide the announcement from users"
            ),
        ),
    ]
