# Generated by Django 5.2.8 on 2025-11-11 10:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ontology", "0104_announcement_hidden"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commentattachmentmetadata",
            name="id",
            field=models.TextField(db_column="id", primary_key=True, serialize=False),
        ),
    ]
