# Generated by Django 5.2.7 on 2025-11-13 11:45

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ontology", "0105_alter_commentattachmentmetadata_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="id",
            field=models.TextField(
                db_column="id",
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="commentattachment",
            name="id",
            field=models.TextField(
                db_column="id",
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="commentattachment",
            name="comment_id",
            field=models.ForeignKey(
                blank=True,
                db_column="comment_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attachments",
                to="ontology.comment",
                verbose_name="Comment ID",
            ),
        ),
        migrations.RenameField(
            model_name="commentattachment",
            old_name="comment_id",
            new_name="comment",
        ),
    ]
