# Generated by Django 5.2.8 on 2025-11-17 09:28

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "ontology",
            "0106_alter_comment_id_alter_commentattachment_comment_id_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="checktype",
            name="id",
            field=models.TextField(
                choices=[
                    ("1", "Accommodation exists"),
                    ("2", "Accommodation suitable"),
                    ("3", "DBS check and Sponsor suitable"),
                    ("4", "Guests have arrived in their accommodation"),
                    ("5", "Sg Checks Complete"),
                    ("6", "Eoi Dbs"),
                    ("7", "Sponsor Accepts Role"),
                    ("8", "Sponsor Arrangements Suitable"),
                    ("9", "Uk Form Uploaded"),
                    ("10", "Ukr Form Uploaded"),
                    ("11", "Ho Checks Household"),
                    ("12", "Ho Checks Sponsor"),
                ],
                db_column="id",
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="mvinteraction",
            name="interaction_contact",
            field=models.TextField(
                blank=True,
                choices=[
                    ("Rematch Required", "Rematch Required"),
                    (
                        "Guest is in temporary accommodation",
                        "Rematch Reason Temp Accommodation",
                    ),
                    (
                        "dluhc-PURPOSE-Resettlement_Workflow_USERS-SCOPE-GENERAL-Central Casework Team",
                        "Central Casework Team",
                    ),
                    (
                        "dluhc-PURPOSE-Resettlement_Workflow_USERS-SCOPE-UKVI -UKVI ",
                        "Ukvi Casework Team",
                    ),
                    (
                        "dluhc-PURPOSE-Resettlement_Workflow_USERS-SCOPE-GENERAL-Border Force",
                        "Border Force Purpose",
                    ),
                    (
                        "Rematch Reverted by Central Casework Team",
                        "Rematch Undo Central Case",
                    ),
                    ("Rematch Reverted", "Rematch Undo"),
                    ("Withdrawn Sponsor", "Withdrawn Sponsor"),
                    ("Reverted Sponsor Withdrawal", "Undo Withdraw Sponsor"),
                    ("Indicated End Date", "Indicated End Date"),
                    (
                        "fd6f1237-782b-4879-8718-7aec87de7f7c",
                        "Safeguarding Team Group Id",
                    ),
                    ("Returned To Programme", "Returned To Programme"),
                    ("Leaving Programe", "Leaving Programme"),
                    ("Rematch Recorded", "Rematch Recorded"),
                    ("Safeguarding check updated", "Safeguarding Check Updated"),
                ],
                db_column="interaction_contact",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="visainformationrequest",
            name="requested_check_type_id",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(
                    choices=[
                        ("1", "Accommodation exists"),
                        ("2", "Accommodation suitable"),
                        ("3", "DBS check and Sponsor suitable"),
                        ("4", "Guests have arrived in their accommodation"),
                        ("5", "Sg Checks Complete"),
                        ("6", "Eoi Dbs"),
                        ("7", "Sponsor Accepts Role"),
                        ("8", "Sponsor Arrangements Suitable"),
                        ("9", "Uk Form Uploaded"),
                        ("10", "Ukr Form Uploaded"),
                        ("11", "Ho Checks Household"),
                        ("12", "Ho Checks Sponsor"),
                    ]
                ),
                blank=True,
                db_column="requested_check_type_id",
                null=True,
                size=None,
            ),
        ),
    ]
