# Generated by Django 5.2.8 on 2025-12-02 13:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ontology", "0109_alter_mvinteraction_interaction_contact"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="devcheckv2",
            name="last_updated_at",
            field=models.DateTimeField(
                blank=True, db_column="last_updated_at", null=True
            ),
        ),
        migrations.AddField(
            model_name="devcheckv2",
            name="last_updated_by",
            field=models.ForeignKey(
                blank=True,
                db_column="last_updated_by",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="checks_last_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
