# Generated by Django 5.2.7 on 2025-12-08 17:11

from django.db import migrations, models

from ontology.models.MvVolunteer import generate_id


class Migration(migrations.Migration):
    dependencies = [
        ("ontology", "0112_alter_mvinteraction_interaction_contact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mvvolunteer",
            name="id",
            field=models.TextField(
                db_column="id",
                default=generate_id,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
        ),
    ]
