# Generated by Django 5.2.7 on 2025-12-08 17:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ontology", "0113_alter_mvvolunteer_id"),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE ontology_eoihost_sponsor_id RENAME TO ontology_eoihost_sponsor;",
            "ALTER TABLE ontology_eoihost_sponsor RENAME TO ontology_eoihost_sponsor_id;",
        ),
    ]
