# Generated by Django 5.2.9 on 2026-01-27 00:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ontology", "0115_mvinteraction_linked_sponsor_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mvinteraction",
            name="linked_accommodation",
            field=models.ForeignKey(
                blank=True,
                db_column="linked_accommodation_id",
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="ontology.mvaccommodation",
            ),
        ),
    ]
