# Generated by Django 5.2.9 on 2026-02-06 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ontology", "0116_mvinteraction_linked_accommodation"),
    ]

    operations = [
        migrations.AddField(
            model_name="mvinteraction",
            name="linked_guest",
            field=models.ForeignKey(
                blank=True,
                db_column="linked_guest_id",
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="ontology.mvperson",
            ),
        ),
    ]
