# Generated by Django 5.2.9 on 2026-02-10 11:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ontology", "0117_mvinteraction_linked_guest"),
    ]

    operations = [
        migrations.DeleteModel(
            name="WorkshopDesignHubCarCompanyEmployee",
        ),
        migrations.DeleteModel(
            name="WorkshopDesignHubCarPartIssue",
        ),
        migrations.DeleteModel(
            name="WorkshopDesignHubNycRentalProperty",
        ),
        migrations.RemoveField(
            model_name="workshopdesignhubretailrecommendations",
            name="article_code",
        ),
        migrations.RemoveField(
            model_name="workshopdesignhubretailsales",
            name="article_code",
        ),
        migrations.DeleteModel(
            name="WorkshopDesignHubRetailCampaign",
        ),
        migrations.DeleteModel(
            name="WorkshopDesignHubRetailPriceContext",
        ),
        migrations.DeleteModel(
            name="WorkshopDesignHubRetailPricingAlert",
        ),
        migrations.DeleteModel(
            name="WorkshopDesignHubRetailSalesTimeseries",
        ),
        migrations.DeleteModel(
            name="WorkshopDesignHubRetailRecommendations",
        ),
        migrations.DeleteModel(
            name="WorkshopDesignHubRetailArticle",
        ),
        migrations.DeleteModel(
            name="WorkshopDesignHubRetailSales",
        ),
    ]
