# Generated by Django 5.2.9 on 2026-02-16 15:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ontology", "0118_delete_workshop_models"),
    ]

    operations = [
        migrations.DeleteModel(
            name="metricsActions",
        ),
        migrations.DeleteModel(
            name="metricsGetResources",
        ),
        migrations.DeleteModel(
            name="metricsLogin",
        ),
        migrations.RemoveField(
            model_name="metricsprocesslogs",
            name="process_object_fk",
        ),
        migrations.DeleteModel(
            name="metricsProcesObjects",
        ),
        migrations.DeleteModel(
            name="metricsProcessLogs",
        ),
    ]
