# Generated by Django 5.2.9 on 2026-02-16 15:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ontology", "0119_delete_metric_models"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="machineryapplication",
            name="ltla_code",
        ),
        migrations.RemoveField(
            model_name="machineryapplicationlog",
            name="id",
        ),
        migrations.RemoveField(
            model_name="machinerychecksstatuslogs",
            name="id",
        ),
        migrations.RemoveField(
            model_name="machinerycleanvisastatuslogs",
            name="id",
        ),
        migrations.RemoveField(
            model_name="machineryuam",
            name="accommodation_request",
        ),
        migrations.RemoveField(
            model_name="machineryuam",
            name="ltla_code",
        ),
        migrations.RemoveField(
            model_name="machineryuamlog",
            name="id",
        ),
        migrations.DeleteModel(
            name="MachineryVisaStatus",
        ),
        migrations.DeleteModel(
            name="MachineryVisaStatusLogs",
        ),
        migrations.DeleteModel(
            name="machineryApplication",
        ),
        migrations.DeleteModel(
            name="machineryApplicationLog",
        ),
        migrations.DeleteModel(
            name="MachineryChecksStatus",
        ),
        migrations.DeleteModel(
            name="MachineryChecksStatusLogs",
        ),
        migrations.DeleteModel(
            name="MachineryCleanVisaStatus",
        ),
        migrations.DeleteModel(
            name="MachineryCleanVisaStatusLogs",
        ),
        migrations.DeleteModel(
            name="MachineryUam",
        ),
        migrations.DeleteModel(
            name="MachineryUamLog",
        ),
    ]
