# Generated by Django 5.2.12 on 2026-04-02 12:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ontology", "0121_remove_log_sanity_purpose_extra_safeguarding"),
    ]

    operations = [
        migrations.AddField(
            model_name="mvaccommodationrequest",
            name="requires_checks_status_recalculation",
            field=models.BooleanField(default=False),
        ),
    ]
