# Generated by Django 5.2.13 on 2026-04-28 16:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ontology", "0125_remove_estimatedhostrelationship_accommodation_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="EhrClassification",
        ),
        migrations.DeleteModel(
            name="EntityGroups",
        ),
        migrations.DeleteModel(
            name="ExamplePublicFormOutput",
        ),
        migrations.DeleteModel(
            name="FeatureRequest",
        ),
        migrations.DeleteModel(
            name="Generateda92287c652164c38bfe37ec6f124d305PurposeApprovers",
        ),
        migrations.RemoveField(
            model_name="govnotifyemail",
            name="linked_interaction",
        ),
        migrations.DeleteModel(
            name="GroupMembershipRevocation",
        ),
        migrations.RemoveField(
            model_name="guestevent",
            name="accompanying_person_ids",
        ),
        migrations.RemoveField(
            model_name="guestevent",
            name="person",
        ),
        migrations.RemoveField(
            model_name="guestevent",
            name="sponsorship_certification_number",
        ),
        migrations.RemoveField(
            model_name="guestevent",
            name="visa_application",
        ),
        migrations.DeleteModel(
            name="HfUMetric",
        ),
        migrations.DeleteModel(
            name="GovNotifyEmail",
        ),
        migrations.DeleteModel(
            name="GuestEvent",
        ),
    ]
