# Generated by Django 5.2.11 on 2026-04-28 10:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "ontology",
            "0126_delete_ehrclassification_delete_entitygroups_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="accommodationrequestlaassignmentsuggestion",
            name="accommodation_request",
        ),
        migrations.RemoveField(
            model_name="accommodationrequestlaassignmentsuggestion",
            name="potential_local_authority",
        ),
        migrations.DeleteModel(
            name="AdditionalAccessRule",
        ),
        migrations.RemoveField(
            model_name="buckinghamshireclaimperson",
            name="foundry",
        ),
        migrations.DeleteModel(
            name="CalendarEvents",
        ),
        migrations.DeleteModel(
            name="CatalogueApplication",
        ),
        migrations.RemoveField(
            model_name="cohabitant",
            name="accommodation",
        ),
        migrations.RemoveField(
            model_name="cohabitant",
            name="sponsor",
        ),
        migrations.RemoveField(
            model_name="cohabitant",
            name="sponsorship_certification_number",
        ),
        migrations.RemoveField(
            model_name="commentchannel",
            name="accommodation_request",
        ),
        migrations.RemoveField(
            model_name="commentchannel",
            name="visa_application",
        ),
        migrations.DeleteModel(
            name="DevSponsorshipCertificationAttachmentsTest",
        ),
        migrations.DeleteModel(
            name="AccommodationRequestLaAssignmentSuggestion",
        ),
        migrations.DeleteModel(
            name="BuckinghamshireClaimPerson",
        ),
        migrations.DeleteModel(
            name="Cohabitant",
        ),
        migrations.DeleteModel(
            name="CommentChannel",
        ),
    ]
