# Generated by Django 5.2.9 on 2026-04-30 09:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "ontology",
            "0127_remove_accommodationrequestlaassignmentsuggestion_accommodation_request_and_more",
        ),
    ]

    operations = [
        migrations.DeleteModel(
            name="Manual",
        ),
        migrations.RemoveField(
            model_name="mvorganizationeoi",
            name="host",
        ),
        migrations.DeleteModel(
            name="NotepadDataSnapshot",
        ),
        migrations.DeleteModel(
            name="Notification",
        ),
        migrations.DeleteModel(
            name="OriginalEntityRecord",
        ),
        migrations.DeleteModel(
            name="PbacConfig",
        ),
        migrations.RemoveField(
            model_name="pmrconfidencescore",
            name="record",
        ),
        migrations.DeleteModel(
            name="ProjectPermission",
        ),
        migrations.DeleteModel(
            name="OpsSafeguardingInvestigation",
        ),
        migrations.DeleteModel(
            name="MvOrganizationEoi",
        ),
        migrations.DeleteModel(
            name="PmrConfidenceScore",
        ),
    ]
