# Generated by Django 5.2.13 on 2026-04-30 15:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ontology", "0128_delete_manual_remove_mvorganizationeoi_host_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Q2UtlaPaymentsReconcilation",
        ),
        migrations.RemoveField(
            model_name="reclassificationrequest",
            name="person",
        ),
        migrations.DeleteModel(
            name="Scenario",
        ),
        migrations.DeleteModel(
            name="School",
        ),
        migrations.DeleteModel(
            name="SponsorshipCertificationAttachmentsStaging",
        ),
        migrations.DeleteModel(
            name="Suggestion",
        ),
        migrations.RemoveField(
            model_name="uamproperties",
            name="person",
        ),
        migrations.DeleteModel(
            name="UserPreferences",
        ),
        migrations.DeleteModel(
            name="VirEarlyAdopterUtla",
        ),
        migrations.RemoveField(
            model_name="visapropagationrecord",
            name="accommodation_request",
        ),
        migrations.DeleteModel(
            name="ReclassificationRequest",
        ),
        migrations.DeleteModel(
            name="UamProperties",
        ),
        migrations.DeleteModel(
            name="VisaPropagationRecord",
        ),
    ]
