# Generated by Django 5.2.13 on 2026-05-14 14:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ontology", "0129_delete_q2utlapaymentsreconcilation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sponsorshipcertificationform",
            name="ingestion_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="visaapplication",
            name="ingestion_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
