# Generated by Django 5.2.13 on 2026-05-26 14:51

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ontology", "0130_add_ingestion_time_column"),
    ]

    operations = [
        migrations.CreateModel(
            name="WalesMigrationProcessList",
            fields=[
                ("accommodation_id", models.TextField()),
                ("data_index", models.IntegerField()),
                ("date_added", models.DateTimeField()),
                (
                    "guest_ids",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), size=None
                    ),
                ),
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("input_ar_id", models.TextField()),
                ("iteration", models.IntegerField(default=0)),
                ("output_ar_id", models.TextField()),
                ("reprocess", models.BooleanField(default=None, null=True)),
                ("sponsor_id", models.TextField()),
                ("successful_run", models.BooleanField(default=None, null=True)),
                ("unique_application_number", models.TextField()),
            ],
        ),
    ]
