# Generated by Django 5.2.13 on 2026-05-26 15:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ontology", "0131_walesmigrationprocesslist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="walesmigrationprocesslist",
            name="output_ar_id",
            field=models.TextField(null=True),
        ),
    ]
