# Generated by Django 5.2.13 on 2026-05-27 15:31

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ontology", "0132_alter_walesmigrationprocesslist_output_ar_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="walesmigrationprocesslist",
            name="unique_application_number",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(), size=None
            ),
        ),
    ]
