# Generated by Django 5.2.13 on 2026-05-20 13:21

from django.db import migrations, models


def update_request_status_values(apps, schema_editor):
    vir = apps.get_model("ontology", "VisaInformationRequest")
    for obj in vir.objects.all():
        status = obj.request_status
        if status == "Waiting on LA":
            obj.request_status = "Awaiting LA"
        if status == "Waiting on UKVI":
            obj.request_status = "Awaiting UKVI"
        obj.save()


def reverse_request_status_values(apps, schema_editor):
    vir = apps.get_model("ontology", "VisaInformationRequest")
    for obj in vir.objects.all():
        status = obj.request_status
        if status == "Awaiting LA":
            obj.request_status = "Waiting on LA"
        if status == "Awaiting UKVI":
            obj.request_status = "Waiting on UKVI"
        obj.save()


class Migration(migrations.Migration):
    dependencies = [
        ("ontology", "0133_alter_walesmigrationprocesslist_unique_application_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visainformationrequest",
            name="request_status",
            field=models.TextField(
                blank=True,
                choices=[
                    ("Awaiting UKVI", "Awaiting UKVI"),
                    ("Awaiting LA", "Awaiting LA"),
                    ("Closed", "Closed"),
                ],
                db_column="request_status",
                null=True,
            ),
        ),
        migrations.RunPython(
            update_request_status_values, reverse_request_status_values
        ),
    ]
