# Generated by Django 5.2.13 on 2026-05-28 09:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ontology", "0134_alter_visainformationrequest_request_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mvinteraction",
            name="interaction_contact",
            field=models.TextField(
                blank=True,
                choices=[
                    ("Rematch Required", "Rematch Required"),
                    (
                        "Guest is in temporary accommodation",
                        "Rematch Reason Temp Accommodation",
                    ),
                    (
                        "dluhc-PURPOSE-Resettlement_Workflow_USERS-SCOPE-GENERAL-Central Casework Team",
                        "Central Casework Team",
                    ),
                    (
                        "dluhc-PURPOSE-Resettlement_Workflow_USERS-SCOPE-UKVI -UKVI ",
                        "Ukvi Casework Team",
                    ),
                    (
                        "dluhc-PURPOSE-Resettlement_Workflow_USERS-SCOPE-GENERAL-Border Force",
                        "Border Force Purpose",
                    ),
                    (
                        "Rematch Reverted by Central Casework Team",
                        "Rematch Undo Central Case",
                    ),
                    ("Rematch Reverted", "Rematch Undo"),
                    ("Withdrawn Sponsor", "Withdrawn Sponsor"),
                    ("Reverted Sponsor Withdrawal", "Undo Withdraw Sponsor"),
                    ("Indicated End Date", "Indicated End Date"),
                    (
                        "fd6f1237-782b-4879-8718-7aec87de7f7c",
                        "Safeguarding Team Group Id",
                    ),
                    ("Returned To Programme", "Returned To Programme"),
                    ("Leaving Programme", "Leaving Programme"),
                    ("Rematch Recorded", "Rematch Recorded"),
                    ("Reassignment request created", "Reassignment Request Created"),
                    ("Reassignment accepted", "Reassignment Accepted"),
                    ("Reassignment rejected", "Reassignment Rejected"),
                    ("Safeguarding check updated", "Safeguarding Check Updated"),
                    ("Accommodation is suitable check", "Accommodation Suitable Check"),
                    ("Accommodation exists check", "Accommodation Exists Check"),
                    (
                        "DBS and sponsor suitable check",
                        "Dbs And Sponsor Suitable Check",
                    ),
                    (
                        "Guests have arrived in accommodation check",
                        "Guest Arrived Check",
                    ),
                    ("Guests have arrived", "Guest Arrived"),
                    ("Visa application created", "Visa Application Created"),
                    ("Visa application refused", "Visa Application Refused"),
                    ("Visa application issued", "Visa Application Issued"),
                    ("Record deduplicated", "Record Deduplicated"),
                    ("Deduplication undone", "Record Deduplication Undone"),
                    ("Wales migration", "Wales Migration"),
                ],
                db_column="interaction_contact",
                null=True,
            ),
        ),
    ]
