# Generated by Django 5.2.14 on 2026-06-17 12:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ontology", "0135_alter_mvinteraction_interaction_contact"),
    ]

    operations = [
        migrations.AddField(
            model_name="walesmigrationprocesslist",
            name="to_close",
            field=models.BooleanField(default=False),
        ),
    ]
