# Generated by Django 5.2.14 on 2026-06-23 11:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ontology", "0136_walesmigrationprocesslist_to_close"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sponsorshipcertificationform",
            name="foundry_time",
        ),
        migrations.RemoveField(
            model_name="visaapplication",
            name="foundry_time",
        ),
    ]
