# Generated by Django 5.2.14 on 2026-07-08 15:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ontology", "0137_remove_sponsorshipcertificationform_foundry_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mvaccommodation",
            name="archived_at",
            field=models.DateTimeField(blank=True, db_column="archived_at", null=True),
        ),
        migrations.AddField(
            model_name="mvaccommodation",
            name="is_archived",
            field=models.BooleanField(db_column="is_archived", default=False),
        ),
        migrations.AddField(
            model_name="mvperson",
            name="archived_at",
            field=models.DateTimeField(blank=True, db_column="archived_at", null=True),
        ),
        migrations.AddField(
            model_name="mvperson",
            name="is_archived",
            field=models.BooleanField(db_column="is_archived", default=False),
        ),
        migrations.AddField(
            model_name="mvvolunteer",
            name="archived_at",
            field=models.DateTimeField(blank=True, db_column="archived_at", null=True),
        ),
        migrations.AddField(
            model_name="mvvolunteer",
            name="is_archived",
            field=models.BooleanField(db_column="is_archived", default=False),
        ),
    ]
