# Generated by Django 5.2.15 on 2026-07-23 13:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ontology", "0138_mvaccommodation_archived_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HiddenUnassignedAccommodationRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hidden_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "accommodation_request",
                    models.OneToOneField(
                        db_column="accommodation_request_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hidden_unassigned_record",
                        to="ontology.mvaccommodationrequest",
                    ),
                ),
                (
                    "hidden_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hidden_unassigned_accommodation_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Hidden Unassigned Accommodation Request",
            },
        ),
    ]
