# Generated by Django 5.2.14 on 2026-08-10 13:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ontology", "0139_hiddenunassignedaccommodationrequest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sponsorshipcertificationform",
            name="reference",
            field=models.TextField(
                db_column="reference",
                primary_key=True,
                serialize=False,
                verbose_name="Application number",
            ),
        ),
    ]
