# Generated by Django 5.1.4 on 2025-01-13 12:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_groupinfo"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupinfo",
            name="ltla_name",
            field=models.TextField(blank=True, null=True),
        ),
    ]
