# Generated by Django 5.1.4 on 2025-01-28 15:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_groupinfo_ltla_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupinfo",
            name="gss_code",
            field=models.TextField(blank=True, null=True),
        ),
    ]
