# Generated by Django 5.1.4 on 2025-02-10 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_create_ltla_groups"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupinfo",
            name="is_utla",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="groupinfo",
            name="parent_utla",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounts.groupinfo",
                verbose_name="UTLA",
            ),
        ),
        migrations.AddField(
            model_name="groupinfo",
            name="utla_gss_code",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="groupinfo",
            name="utla_name",
            field=models.TextField(blank=True, null=True),
        ),
    ]
