# Generated by Django 5.1.4 on 2025-04-01 09:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0008_accessrequest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accessrequest",
            name="permissions",
            field=models.TextField(
                choices=[
                    (
                        "READ_ONLY",
                        "Read only user - you only need to see the information and the records",
                    ),
                    (
                        "USER",
                        "User - you need to see all the records to edit, check and make changes to them",
                    ),
                    (
                        "APPROVER",
                        "Approver - you approve the access requests for your team (you cannot access data with this alone)",
                    ),
                ],
                default="USER",
            ),
        ),
        migrations.AlterField(
            model_name="accessrequest",
            name="status",
            field=models.TextField(
                choices=[
                    ("PENDING", "Pending"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                ],
                default="PENDING",
            ),
        ),
    ]
