# Generated by Django 5.1.7 on 2025-04-02 10:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0009_alter_accessrequest_permissions_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="accessrequest",
            name="permissions",
        ),
        migrations.AlterField(
            model_name="accessrequest",
            name="requester",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="requested_access",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="accessrequest",
            name="reviewer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviewed_access",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="accessrequest",
            name="status",
            field=models.TextField(
                choices=[
                    ("PENDING", "Not reviewed"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                ],
                default="PENDING",
            ),
        ),
    ]
