# Generated by Django 5.1.4 on 2025-04-02 13:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0010_remove_accessrequest_permissions_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accessrequest",
            name="rejection_justification",
            field=models.TextField(blank=True, null=True),
        ),
    ]
