# Generated by Django 5.1.7 on 2025-04-09 13:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0011_alter_accessrequest_rejection_justification"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupinfo",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
