# Generated by Django 5.1.7 on 2025-04-09 15:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0012_groupinfo_description"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="GroupProxy",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("auth.group",),
        ),
    ]
