# Generated by Django 5.1.8 on 2025-04-23 14:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0013_groupproxy"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
    ]
