# Generated by Django 5.1.8 on 2025-04-24 13:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0014_alter_user_managers"),
    ]

    operations = [
        migrations.RenameField(
            model_name="accessrequest",
            old_name="local_authority",
            new_name="group_info",
        ),
        migrations.AddField(
            model_name="accessrequest",
            name="group_type",
            field=models.TextField(
                choices=[("LOCAL_AUTHORITY", "Local Authority"), ("OTHER", "Other")],
                default="LOCAL_AUTHORITY",
            ),
            preserve_default=False,
        ),
    ]
