# Generated by Django 5.1.8 on 2025-04-25 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0016_create_scotland_wales_ltla_and_utla_groups"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupinfo",
            name="da_gss_code",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="groupinfo",
            name="da_name",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="groupinfo",
            name="is_da",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="groupinfo",
            name="parent_da",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="da_parent_of",
                to="accounts.groupinfo",
                verbose_name="DA",
            ),
        ),
        migrations.AlterField(
            model_name="groupinfo",
            name="parent_utla",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="utla_parent_of",
                to="accounts.groupinfo",
                verbose_name="UTLA",
            ),
        ),
    ]
