# Generated by Django 5.1.8 on 2025-04-28 10:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0018_create_da_groups"),
    ]

    operations = [
        migrations.AddField(
            model_name="accessrequest",
            name="da_group_type",
            field=models.TextField(
                blank=True,
                choices=[
                    ("CENTRAL_USER", "Central user"),
                    ("LOCAL_AUTHORITY", "Local authority"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="accessrequest",
            name="group_type",
            field=models.TextField(
                choices=[
                    ("LOCAL_AUTHORITY", "Local authority"),
                    ("DEVOLVED_ADMINISTRATION", "Devolved administration"),
                ]
            ),
        ),
    ]
