# Generated by Django 5.1.8 on 2025-04-29 13:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0021_create_mhclg_ops_support_groups"),
    ]

    operations = [
        migrations.AddField(
            model_name="accessrequest",
            name="hidden_by_requester",
            field=models.BooleanField(default=False),
        ),
    ]
