# Generated by Django 5.1.8 on 2025-05-20 08:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0023_rename_accessrequest_updated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="accessrequest",
            name="access_revoked",
            field=models.BooleanField(default=False),
        ),
    ]
