# Generated by Django 5.2 on 2025-06-03 05:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0024_accessrequest_access_revoked"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={},
        ),
        migrations.AddField(
            model_name="user",
            name="entra_oid",
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="entra_tid",
            field=models.UUIDField(null=True),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                fields=("entra_oid", "entra_tid"), name="entra_id"
            ),
        ),
    ]
