# Generated by Django 5.2.9 on 2026-01-12 17:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0028_remove_utla_cumbria"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accessrequest",
            name="group_type",
            field=models.TextField(
                choices=[
                    ("DEV", "Dev"),
                    ("DEVOLVED_ADMINISTRATION", "Devolved administration"),
                    (
                        "DEVOLVED_ADMINISTRATION_EARLY_ADOPTERS",
                        "Early adopters - Devolved administration",
                    ),
                    ("HOME_OFFICE", "Home office operations team"),
                    (
                        "HOME_OFFICE_EARLY_ADOPTERS",
                        "Early adopters - Home office operations team",
                    ),
                    ("LOCAL_AUTHORITY", "Local authority"),
                    (
                        "LOCAL_AUTHORITY_EARLY_ADOPTERS",
                        "Early adopters - Local authority",
                    ),
                    ("MHCLG", "MHCLG operations team"),
                    ("MHCLG_EARLY_ADOPTERS", "Early adopters - MHCLG operations team"),
                    ("SERVICE_SUPPORT", "Service support"),
                    (
                        "SERVICE_SUPPORT_EARLY_ADOPTERS",
                        "Early adopters - Service support",
                    ),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="groupinfo",
            name="group_type",
            field=models.TextField(
                choices=[
                    ("DEV", "Dev"),
                    ("DEVOLVED_ADMINISTRATION", "Devolved administration"),
                    (
                        "DEVOLVED_ADMINISTRATION_EARLY_ADOPTERS",
                        "Early adopters - Devolved administration",
                    ),
                    ("HOME_OFFICE", "Home office operations team"),
                    (
                        "HOME_OFFICE_EARLY_ADOPTERS",
                        "Early adopters - Home office operations team",
                    ),
                    ("LOCAL_AUTHORITY", "Local authority"),
                    (
                        "LOCAL_AUTHORITY_EARLY_ADOPTERS",
                        "Early adopters - Local authority",
                    ),
                    ("MHCLG", "MHCLG operations team"),
                    ("MHCLG_EARLY_ADOPTERS", "Early adopters - MHCLG operations team"),
                    ("SERVICE_SUPPORT", "Service support"),
                    (
                        "SERVICE_SUPPORT_EARLY_ADOPTERS",
                        "Early adopters - Service support",
                    ),
                ]
            ),
        ),
    ]
