# Generated by Django 5.2.16 on 2026-09-22 14:18

from django.db import migrations

ltla_data = [
    ("E06000063", "Cumberland"),
    ("E06000064", "Westmorland and Furness"),
    ("E06000065", "North Yorkshire"),
    ("E06000066", "Somerset"),
]


def create_ltla_group(ltla_name: str, gss_code: str, apps):
    Group = apps.get_model("auth", "Group")
    GroupInfo = apps.get_model("accounts", "GroupInfo")

    group_name = "_".join(["ltla"] + ltla_name.lower().split())

    group, created = Group.objects.get_or_create(name=group_name)

    if created:
        GroupInfo.objects.create(group=group, gss_code=gss_code, ltla_name=ltla_name)


def create_ltla_groups(apps, schema_editor):
    for ltla in ltla_data:
        gss_code, name = ltla
        create_ltla_group(name, gss_code, apps)


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0035_create_second_browser_test_la_group"),
    ]

    operations = [migrations.RunPython(create_ltla_groups)]
