# Generated by Django 5.2.16 on 2026-09-22 14:18

from django.db import migrations

from accounts.enums import GroupType

ltla_data = [
    ("E06000063", "Cumberland"),
    ("E06000064", "Westmorland and Furness"),
    ("E06000065", "North Yorkshire"),
    ("E06000066", "Somerset"),
]


def create_ltla_group(ltla_name: str, gss_code: str, apps):
    Group = apps.get_model("auth", "Group")
    GroupInfo = apps.get_model("accounts", "GroupInfo")

    parent_utla = GroupInfo.objects.get(utla_name=ltla_name, is_utla=True)

    group_name = "_".join(["ltla"] + ltla_name.lower().split())
    group, created = Group.objects.get_or_create(name=group_name)

    if created:
        GroupInfo.objects.create(
            group=group,
            da_name=parent_utla.da_name,
            da_gss_code=parent_utla.da_gss_code,
            utla_name=ltla_name,
            utla_gss_code=parent_utla.utla_gss_code,
            ltla_name=ltla_name,
            gss_code=gss_code,
            parent_da=parent_utla.parent_da,
            parent_utla=parent_utla,
            description="New Unitary Authority from 2023",
            group_type=GroupType.LOCAL_AUTHORITY,
        )


def create_ltla_groups(apps, schema_editor):
    for ltla in ltla_data:
        gss_code, ltla_name = ltla
        create_ltla_group(ltla_name, gss_code, apps)


def remove_ltla_groups(apps, schema_editor):
    Group = apps.get_model("auth", "Group")

    group_names_to_delete = [
        "_".join(["ltla"] + ltla_name.lower().split()) for _, ltla_name in ltla_data
    ]

    Group.objects.filter(name__in=group_names_to_delete).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0035_create_second_browser_test_la_group"),
    ]

    operations = [
        migrations.RunPython(create_ltla_groups, reverse_code=remove_ltla_groups)
    ]
