# Generated by Django 5.2.16 on 2026-09-22 14:52

from django.db import migrations

utla_data = [
    ("E06000066", "Somerset"),
    ("E06000065", "North Yorkshire"),
]


def update_utla_gss_code(utla_name: str, utla_gss_code: str, apps):
    GroupInfo = apps.get_model("accounts", "GroupInfo")

    GroupInfo.objects.filter(utla_name=utla_name).update(utla_gss_code=utla_gss_code)


def attach_new_ltla(utla_name: str, apps):
    GroupInfo = apps.get_model("accounts", "GroupInfo")

    parent_utla = GroupInfo.objects.get(utla_name=utla_name, is_utla=True)

    GroupInfo.objects.filter(ltla_name=utla_name, is_utla=False).update(
        parent_utla=parent_utla,
        utla_name=utla_name,
    )


def update_north_yorkshire_and_somerset_utlas(apps, schema_editor):
    for utla in utla_data:
        utla_gss_code, utla_name = utla
        attach_new_ltla(utla_name, apps)
        update_utla_gss_code(utla_name, utla_gss_code, apps)


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0036_create_new_unitary_la_groups"),
    ]

    operations = [migrations.RunPython(update_north_yorkshire_and_somerset_utlas)]
