name: Build and Test

on:
  pull_request:
  push:
    branches:
      - 'main'
      - 'release-please--branches--main'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment Environment'
        required: true
        default: 'aws-dev'
        type: choice
        options:
          - aws-dev
          - aws-staging
          - aws-prod
  merge_group:

defaults:
  run:
    shell: bash

# Required for OIDC with AWS
permissions:
  id-token: write
  contents: read

jobs:
  notify_slack_test_success:
    name: Notify Slack
    if: ${{ always() }}  # Run even if the deploy job fails
    uses: ./.github/workflows/notify-slack.yml
    with:
      environment: testing
      success_or_failure: success
      job_type: 'Test'
      github_actor: Triggered by Tester Time.
      workflow_run: If you reall want to see the workflow run... good luck finding it
      release_notes: There are NO release notes so stop looking for them!
    secrets:
      SLACK_SUCCESS_WEBHOOK_URL: ${{ secrets.SLACK_SUCCESS_WEBHOOK_URL }}
      SLACK_FAILURE_WEBHOOK_URL: ${{ secrets.SLACK_FAILURE_WEBHOOK_URL }}

  notify_slack_test_failure:
    name: Notify Slack
    if: ${{ always() }}  # Run even if the deploy job fails
    uses: ./.github/workflows/notify-slack.yml
    with:
      environment: testing
      success_or_failure: failure
      job_type: 'Test'
      github_actor: Triggered by Tester Time.
      workflow_run: If you reall want to see the workflow run... good luck finding it
      release_notes: There are NO release notes so stop looking for them!
    secrets:
      SLACK_SUCCESS_WEBHOOK_URL: ${{ secrets.SLACK_SUCCESS_WEBHOOK_URL }}
      SLACK_FAILURE_WEBHOOK_URL: ${{ secrets.SLACK_FAILURE_WEBHOOK_URL }}
