name: Run Unit Tests

on:
  workflow_call:
    inputs:
      session_id:
        description: The session ID to allow restoring from the cache
        type: string
        required: false
      test_args:
        description: Arguments to pass to the test runner
        type: string
        required: false

jobs:
  tests:
    name: Unit tests
    runs-on: ubuntu-latest
    env:
      DB_HOST: 'localhost'
      DB_USERNAME: 'postgres'
      DB_PASSWORD: 'postgres'
    services:
      postgres:
        image: postgres:16.8
        env:
          POSTGRES_PASSWORD: 'postgres'
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Check out code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2

      - name: Setup Python and Poetry + Restore Poetry cache
        uses: ./.github/actions/setup-python-poetry
        with:
          role-session-name: BuildAndTest-Tests-${{ inputs.session_id }}
          aws-region: ${{ secrets.AWS_REGION }}
          aws-role-to-assume: ${{ secrets.AWS_TESTING_ROLE_TO_ASSUME }}
          aws-codeartifact-account-id: ${{ secrets.AWS_CODEARTIFACT_ACCOUNT_ID }}

      - name: Test
        run: |
          poetry run python manage.py collectstatic --noinput
          poetry run test-parallel ${{ inputs.test_args }}
        env:
          SECRET_KEY: 'a_very_long_and_random_string_for_tests'
          ENTRA_AUTHORITY: 'https://login.microsoftonline.com/organizations'
